name: Local
variables:
  - name: baseUrl
    value: http://localhost:3000
  - name: authTokenUser
    value: ""
  - name: exerciseId
    value: f337c68c-a7db-4489-8ccf-461afcc98c96
  - name: tagId
    value: ""
  - name: trainingId
    value: ""
  - name: sessionId
    value: ""
  - name: repeaterId
    value: ""
  - name: coachTrainingId
    value: ""
  - name: programId
    value: ""
  - name: weekNumber
    value: "1"
  - name: weekId
    value: ""
  - name: coachTrainingItemId
    value: ""
  - name: enrollmentToken
    value: ""
  - name: clientUserId
    value: dd4d4657-35b8-4df1-ae01-b391fe235d8e
  - name: userId
    value: ""
  - name: user
    value: local@local.com
  - name: userPwd
    value: coucou
  - name: coachUsername
    value: coach@local.com
  - name: coachPwd
    value: coucou
  - name: authTokenCoach
    value: ""
