// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assessment_definitions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countReferencesToAssessment = `-- name: CountReferencesToAssessment :one
SELECT (
  SELECT COUNT(*) FROM training_items i
  WHERE i.variable_targets::text LIKE '%' || $1::text || '%'
     OR i.loads::text LIKE '%' || $1::text || '%'
     OR i.left_loads::text LIKE '%' || $1::text || '%'
) + (
  SELECT COUNT(*) FROM coach_program_session_overrides o
  WHERE o.overrides::text LIKE '%' || $1::text || '%'
) AS total
`

// How many training items read a number against this assessment, counting both
// the items themselves and the per-item overrides a coach set on a program week.
// The reference lives inside opaque JSON, so it is matched by looking for the id
// rather than by a foreign key.
func (q *Queries) CountReferencesToAssessment(ctx context.Context, assessmentID string) (int32, error) {
	row := q.db.QueryRow(ctx, countReferencesToAssessment, assessmentID)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const createAssessmentDefinition = `-- name: CreateAssessmentDefinition :one
INSERT INTO assessment_definitions (user_id, training_id, label, prompt, unit, per_hand, bodyweight_relative)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, training_id, label, prompt, unit, per_hand, bodyweight_relative, created_at, updated_at
`

type CreateAssessmentDefinitionParams struct {
	UserID             pgtype.UUID
	TrainingID         pgtype.UUID
	Label              string
	Prompt             pgtype.Text
	Unit               string
	PerHand            bool
	BodyweightRelative bool
}

func (q *Queries) CreateAssessmentDefinition(ctx context.Context, arg CreateAssessmentDefinitionParams) (AssessmentDefinition, error) {
	row := q.db.QueryRow(ctx, createAssessmentDefinition,
		arg.UserID,
		arg.TrainingID,
		arg.Label,
		arg.Prompt,
		arg.Unit,
		arg.PerHand,
		arg.BodyweightRelative,
	)
	var i AssessmentDefinition
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TrainingID,
		&i.Label,
		&i.Prompt,
		&i.Unit,
		&i.PerHand,
		&i.BodyweightRelative,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAssessmentDefinition = `-- name: DeleteAssessmentDefinition :exec
DELETE FROM assessment_definitions WHERE id = $1
`

func (q *Queries) DeleteAssessmentDefinition(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAssessmentDefinition, id)
	return err
}

const getAssessmentDefinition = `-- name: GetAssessmentDefinition :one
SELECT id, user_id, training_id, label, prompt, unit, per_hand, bodyweight_relative, created_at, updated_at FROM assessment_definitions WHERE id = $1
`

func (q *Queries) GetAssessmentDefinition(ctx context.Context, id pgtype.UUID) (AssessmentDefinition, error) {
	row := q.db.QueryRow(ctx, getAssessmentDefinition, id)
	var i AssessmentDefinition
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TrainingID,
		&i.Label,
		&i.Prompt,
		&i.Unit,
		&i.PerHand,
		&i.BodyweightRelative,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssessmentDefinitionByTraining = `-- name: GetAssessmentDefinitionByTraining :one
SELECT id, user_id, training_id, label, prompt, unit, per_hand, bodyweight_relative, created_at, updated_at FROM assessment_definitions WHERE training_id = $1
`

func (q *Queries) GetAssessmentDefinitionByTraining(ctx context.Context, trainingID pgtype.UUID) (AssessmentDefinition, error) {
	row := q.db.QueryRow(ctx, getAssessmentDefinitionByTraining, trainingID)
	var i AssessmentDefinition
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TrainingID,
		&i.Label,
		&i.Prompt,
		&i.Unit,
		&i.PerHand,
		&i.BodyweightRelative,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssessmentDefinitions = `-- name: GetAssessmentDefinitions :many
SELECT id, user_id, training_id, label, prompt, unit, per_hand, bodyweight_relative, created_at, updated_at FROM assessment_definitions
WHERE user_id IS NULL OR user_id = $1
ORDER BY user_id NULLS FIRST, label
`

// Every assessment the caller may reference: the ones Crimpy ships, which belong
// to nobody, and their own. Builtins first so a picker lists them in a stable
// order whatever the athlete has written since.
func (q *Queries) GetAssessmentDefinitions(ctx context.Context, userID pgtype.UUID) ([]AssessmentDefinition, error) {
	rows, err := q.db.Query(ctx, getAssessmentDefinitions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssessmentDefinition
	for rows.Next() {
		var i AssessmentDefinition
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TrainingID,
			&i.Label,
			&i.Prompt,
			&i.Unit,
			&i.PerHand,
			&i.BodyweightRelative,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssessmentDefinitionsByIDs = `-- name: GetAssessmentDefinitionsByIDs :many
SELECT id, user_id, training_id, label, prompt, unit, per_hand, bodyweight_relative, created_at, updated_at FROM assessment_definitions
WHERE id = ANY($1::uuid[]) AND (user_id IS NULL OR user_id = $2)
`

type GetAssessmentDefinitionsByIDsParams struct {
	Ids    []pgtype.UUID
	UserID pgtype.UUID
}

// The named definitions, restricted to the ones the caller may reference. A row
// that does not exist, or belongs to somebody else, is simply absent, and the
// caller refuses the reference as unknown rather than reporting which it was.
func (q *Queries) GetAssessmentDefinitionsByIDs(ctx context.Context, arg GetAssessmentDefinitionsByIDsParams) ([]AssessmentDefinition, error) {
	rows, err := q.db.Query(ctx, getAssessmentDefinitionsByIDs, arg.Ids, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssessmentDefinition
	for rows.Next() {
		var i AssessmentDefinition
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TrainingID,
			&i.Label,
			&i.Prompt,
			&i.Unit,
			&i.PerHand,
			&i.BodyweightRelative,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssessmentDefinitionsForPrescription = `-- name: GetAssessmentDefinitionsForPrescription :many
SELECT id, user_id, training_id, label, prompt, unit, per_hand, bodyweight_relative, created_at, updated_at FROM assessment_definitions WHERE id = ANY($1::uuid[])
`

// The definitions a prescription references, named by ids it already holds. No
// user scoping: a coachee legitimately reads the coach's definition for a
// training they were assigned.
func (q *Queries) GetAssessmentDefinitionsForPrescription(ctx context.Context, ids []pgtype.UUID) ([]AssessmentDefinition, error) {
	rows, err := q.db.Query(ctx, getAssessmentDefinitionsForPrescription, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssessmentDefinition
	for rows.Next() {
		var i AssessmentDefinition
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TrainingID,
			&i.Label,
			&i.Prompt,
			&i.Unit,
			&i.PerHand,
			&i.BodyweightRelative,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLockedAssessmentDefinitions = `-- name: GetLockedAssessmentDefinitions :many
SELECT wanted.id::uuid AS id FROM unnest($1::uuid[]) AS wanted(id)
JOIN assessments a ON a.assessment_id = wanted.id
UNION
SELECT wanted.id::uuid AS id FROM unnest($1::uuid[]) AS wanted(id)
JOIN training_items i
  ON i.variable_targets::text LIKE '%' || wanted.id::text || '%'
  OR i.loads::text LIKE '%' || wanted.id::text || '%'
  OR i.left_loads::text LIKE '%' || wanted.id::text || '%'
UNION
SELECT wanted.id::uuid AS id FROM unnest($1::uuid[]) AS wanted(id)
JOIN coach_program_session_overrides o
  ON o.overrides::text LIKE '%' || wanted.id::text || '%'
`

// Which of the named assessments can no longer move their unit or their hands:
// a result was measured under them, or a training item or a program week
// override reads a number against them.
//
// Asked for the whole set at once rather than one assessment at a time. The
// reference half matches an id inside opaque JSON with LIKE, which no index
// serves and so reads the table through; asking it per assessment read the
// table through once per assessment, and a listing asks about every row it
// serves. Driving the scan from the items and testing each one against every
// named id reads it through once whatever the set holds.
func (q *Queries) GetLockedAssessmentDefinitions(ctx context.Context, ids []pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getLockedAssessmentDefinitions, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecordableAssessmentDefinitions = `-- name: GetRecordableAssessmentDefinitions :many
SELECT d.id, d.user_id, d.training_id, d.label, d.prompt, d.unit, d.per_hand, d.bodyweight_relative, d.created_at, d.updated_at, prescribed.program_id
FROM assessment_definitions d
LEFT JOIN LATERAL (
  SELECT p.id AS program_id
  FROM coach_program_week_sessions s
  JOIN coach_program_weeks w ON w.id = s.week_id
  JOIN coach_programs p ON p.id = w.program_id
  WHERE s.training_id = d.training_id AND p.user_id = $1
  ORDER BY (p.start_date <= current_date) DESC, abs(p.start_date - current_date), p.created_at DESC, p.id
  LIMIT 1
) prescribed ON TRUE
WHERE ($2::uuid IS NULL OR d.id = $2::uuid)
  AND (
    d.user_id IS NULL
    OR d.user_id = $1
    OR d.training_id IN (
      SELECT s.training_id
      FROM coach_program_week_sessions s
      JOIN coach_program_weeks w ON w.id = s.week_id
      JOIN coach_programs p ON p.id = w.program_id
      WHERE p.user_id = $1
    )
  )
ORDER BY d.user_id NULLS FIRST, d.label
`

type GetRecordableAssessmentDefinitionsParams struct {
	UserID       pgtype.UUID
	AssessmentID pgtype.UUID
}

type GetRecordableAssessmentDefinitionsRow struct {
	AssessmentDefinition AssessmentDefinition
	ProgramID            pgtype.UUID
}

// The assessments a result may be recorded against: the ones Crimpy ships, the
// caller's own, and a coach's whose training was prescribed to them by a
// program. Distinct from GetAssessmentDefinitions, which serves a catalog to
// pick from and so stops at the builtins and the caller's own.
//
// program_id names the program the prescription was read under, and is null
// when nothing prescribes the training. It is what makes such a row usable: a
// coach's training is only readable under a program of the caller's, so a row
// that reaches the caller by prescription alone carries the id that reads it.
// Several programs may prescribe the same training, and any of them authorizes
// reading it, so the one the athlete is running now is taken: it is that
// program's week overrides that name the assessments the training itself does
// not, and reading the training under a block the athlete has moved on from
// leaves a prescribed percentage with nothing to label it. Started blocks
// first, nearest start date next, which is the current block; a coach who has
// only planned ahead leaves the one starting soonest.
//
// The set the WHERE admits and the set this names have to be the same, or a row
// is listed carrying no program and the app skips an assessment the server
// would accept. They are written apart because a filter that reads this join
// cannot be applied before it, which would run the join for every assessment
// definition in the database rather than for the caller's.
//
// assessment_id narrows the answer to a single member of that set, which is how
// the record path asks whether one assessment may be written against. Omitting
// it asks for the whole set. One query rather than two, so the endpoint that
// lists them and the check that admits a result cannot come to disagree: an
// assessment offered by the first and refused by the second is a dead end the
// athlete only meets once they have already pulled.
//
// The single id form answers with no row for an unknown assessment and for a
// foreign one alike, so neither reports which assessments exist.
func (q *Queries) GetRecordableAssessmentDefinitions(ctx context.Context, arg GetRecordableAssessmentDefinitionsParams) ([]GetRecordableAssessmentDefinitionsRow, error) {
	rows, err := q.db.Query(ctx, getRecordableAssessmentDefinitions, arg.UserID, arg.AssessmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecordableAssessmentDefinitionsRow
	for rows.Next() {
		var i GetRecordableAssessmentDefinitionsRow
		if err := rows.Scan(
			&i.AssessmentDefinition.ID,
			&i.AssessmentDefinition.UserID,
			&i.AssessmentDefinition.TrainingID,
			&i.AssessmentDefinition.Label,
			&i.AssessmentDefinition.Prompt,
			&i.AssessmentDefinition.Unit,
			&i.AssessmentDefinition.PerHand,
			&i.AssessmentDefinition.BodyweightRelative,
			&i.AssessmentDefinition.CreatedAt,
			&i.AssessmentDefinition.UpdatedAt,
			&i.ProgramID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssessmentDefinition = `-- name: UpdateAssessmentDefinition :one
UPDATE assessment_definitions
SET label = $1, prompt = $2, unit = $3, per_hand = $4,
    bodyweight_relative = $5, updated_at = now()
WHERE id = $6
RETURNING id, user_id, training_id, label, prompt, unit, per_hand, bodyweight_relative, created_at, updated_at
`

type UpdateAssessmentDefinitionParams struct {
	Label              string
	Prompt             pgtype.Text
	Unit               string
	PerHand            bool
	BodyweightRelative bool
	ID                 pgtype.UUID
}

func (q *Queries) UpdateAssessmentDefinition(ctx context.Context, arg UpdateAssessmentDefinitionParams) (AssessmentDefinition, error) {
	row := q.db.QueryRow(ctx, updateAssessmentDefinition,
		arg.Label,
		arg.Prompt,
		arg.Unit,
		arg.PerHand,
		arg.BodyweightRelative,
		arg.ID,
	)
	var i AssessmentDefinition
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TrainingID,
		&i.Label,
		&i.Prompt,
		&i.Unit,
		&i.PerHand,
		&i.BodyweightRelative,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
