// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assessment_definitions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRecordableAssessment = `-- name: CountRecordableAssessment :one
SELECT COUNT(*) FROM assessment_definitions d
WHERE d.id = $1
  AND (
    d.user_id IS NULL
    OR d.user_id = $2
    OR EXISTS (
      SELECT 1 FROM coach_program_week_sessions s
      JOIN coach_program_weeks w ON w.id = s.week_id
      JOIN coach_programs p ON p.id = w.program_id
      WHERE s.training_id = d.training_id AND p.user_id = $2
    )
  )
`

type CountRecordableAssessmentParams struct {
	AssessmentID pgtype.UUID
	UserID       pgtype.UUID
}

// An assessment a result may be recorded against: one Crimpy ships, the
// caller's own, or a coach's whose training was prescribed to them by a program.
// Counting rather than selecting keeps an unknown id and a foreign one
// indistinguishable to the caller.
func (q *Queries) CountRecordableAssessment(ctx context.Context, arg CountRecordableAssessmentParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecordableAssessment, arg.AssessmentID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReferencesToAssessment = `-- name: CountReferencesToAssessment :one
SELECT (
  SELECT COUNT(*) FROM training_items i
  WHERE i.variable_targets::text LIKE '%' || $1::text || '%'
     OR i.loads::text LIKE '%' || $1::text || '%'
     OR i.left_loads::text LIKE '%' || $1::text || '%'
) + (
  SELECT COUNT(*) FROM coach_program_session_overrides o
  WHERE o.overrides::text LIKE '%' || $1::text || '%'
) AS total
`

// How many training items read a number against this assessment, counting both
// the items themselves and the per-item overrides a coach set on a program week.
// The reference lives inside opaque JSON, so it is matched by looking for the id
// rather than by a foreign key.
func (q *Queries) CountReferencesToAssessment(ctx context.Context, assessmentID string) (int32, error) {
	row := q.db.QueryRow(ctx, countReferencesToAssessment, assessmentID)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const createAssessmentDefinition = `-- name: CreateAssessmentDefinition :one
INSERT INTO assessment_definitions (user_id, training_id, label, prompt, unit, per_hand)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, training_id, label, prompt, unit, per_hand, created_at, updated_at
`

type CreateAssessmentDefinitionParams struct {
	UserID     pgtype.UUID
	TrainingID pgtype.UUID
	Label      string
	Prompt     pgtype.Text
	Unit       string
	PerHand    bool
}

func (q *Queries) CreateAssessmentDefinition(ctx context.Context, arg CreateAssessmentDefinitionParams) (AssessmentDefinition, error) {
	row := q.db.QueryRow(ctx, createAssessmentDefinition,
		arg.UserID,
		arg.TrainingID,
		arg.Label,
		arg.Prompt,
		arg.Unit,
		arg.PerHand,
	)
	var i AssessmentDefinition
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TrainingID,
		&i.Label,
		&i.Prompt,
		&i.Unit,
		&i.PerHand,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAssessmentDefinition = `-- name: DeleteAssessmentDefinition :exec
DELETE FROM assessment_definitions WHERE id = $1
`

func (q *Queries) DeleteAssessmentDefinition(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAssessmentDefinition, id)
	return err
}

const getAssessmentDefinition = `-- name: GetAssessmentDefinition :one
SELECT id, user_id, training_id, label, prompt, unit, per_hand, created_at, updated_at FROM assessment_definitions WHERE id = $1
`

func (q *Queries) GetAssessmentDefinition(ctx context.Context, id pgtype.UUID) (AssessmentDefinition, error) {
	row := q.db.QueryRow(ctx, getAssessmentDefinition, id)
	var i AssessmentDefinition
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TrainingID,
		&i.Label,
		&i.Prompt,
		&i.Unit,
		&i.PerHand,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssessmentDefinitionByTraining = `-- name: GetAssessmentDefinitionByTraining :one
SELECT id, user_id, training_id, label, prompt, unit, per_hand, created_at, updated_at FROM assessment_definitions WHERE training_id = $1
`

func (q *Queries) GetAssessmentDefinitionByTraining(ctx context.Context, trainingID pgtype.UUID) (AssessmentDefinition, error) {
	row := q.db.QueryRow(ctx, getAssessmentDefinitionByTraining, trainingID)
	var i AssessmentDefinition
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TrainingID,
		&i.Label,
		&i.Prompt,
		&i.Unit,
		&i.PerHand,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssessmentDefinitions = `-- name: GetAssessmentDefinitions :many
SELECT id, user_id, training_id, label, prompt, unit, per_hand, created_at, updated_at FROM assessment_definitions
WHERE user_id IS NULL OR user_id = $1
ORDER BY user_id NULLS FIRST, label
`

// Every assessment the caller may reference: the ones Crimpy ships, which belong
// to nobody, and their own. Builtins first so a picker lists them in a stable
// order whatever the athlete has written since.
func (q *Queries) GetAssessmentDefinitions(ctx context.Context, userID pgtype.UUID) ([]AssessmentDefinition, error) {
	rows, err := q.db.Query(ctx, getAssessmentDefinitions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssessmentDefinition
	for rows.Next() {
		var i AssessmentDefinition
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TrainingID,
			&i.Label,
			&i.Prompt,
			&i.Unit,
			&i.PerHand,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssessmentDefinitionsByIDs = `-- name: GetAssessmentDefinitionsByIDs :many
SELECT id, user_id, training_id, label, prompt, unit, per_hand, created_at, updated_at FROM assessment_definitions
WHERE id = ANY($1::uuid[]) AND (user_id IS NULL OR user_id = $2)
`

type GetAssessmentDefinitionsByIDsParams struct {
	Ids    []pgtype.UUID
	UserID pgtype.UUID
}

// The named definitions, restricted to the ones the caller may reference. A row
// that does not exist, or belongs to somebody else, is simply absent, and the
// caller refuses the reference as unknown rather than reporting which it was.
func (q *Queries) GetAssessmentDefinitionsByIDs(ctx context.Context, arg GetAssessmentDefinitionsByIDsParams) ([]AssessmentDefinition, error) {
	rows, err := q.db.Query(ctx, getAssessmentDefinitionsByIDs, arg.Ids, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssessmentDefinition
	for rows.Next() {
		var i AssessmentDefinition
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TrainingID,
			&i.Label,
			&i.Prompt,
			&i.Unit,
			&i.PerHand,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssessmentDefinitionsForPrescription = `-- name: GetAssessmentDefinitionsForPrescription :many
SELECT id, user_id, training_id, label, prompt, unit, per_hand, created_at, updated_at FROM assessment_definitions WHERE id = ANY($1::uuid[])
`

// The definitions a prescription references, named by ids it already holds. No
// user scoping: a coachee legitimately reads the coach's definition for a
// training they were assigned.
func (q *Queries) GetAssessmentDefinitionsForPrescription(ctx context.Context, ids []pgtype.UUID) ([]AssessmentDefinition, error) {
	rows, err := q.db.Query(ctx, getAssessmentDefinitionsForPrescription, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssessmentDefinition
	for rows.Next() {
		var i AssessmentDefinition
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TrainingID,
			&i.Label,
			&i.Prompt,
			&i.Unit,
			&i.PerHand,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssessmentDefinition = `-- name: UpdateAssessmentDefinition :one
UPDATE assessment_definitions
SET label = $1, prompt = $2, unit = $3, per_hand = $4,
    updated_at = now()
WHERE id = $5
RETURNING id, user_id, training_id, label, prompt, unit, per_hand, created_at, updated_at
`

type UpdateAssessmentDefinitionParams struct {
	Label   string
	Prompt  pgtype.Text
	Unit    string
	PerHand bool
	ID      pgtype.UUID
}

func (q *Queries) UpdateAssessmentDefinition(ctx context.Context, arg UpdateAssessmentDefinitionParams) (AssessmentDefinition, error) {
	row := q.db.QueryRow(ctx, updateAssessmentDefinition,
		arg.Label,
		arg.Prompt,
		arg.Unit,
		arg.PerHand,
		arg.ID,
	)
	var i AssessmentDefinition
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TrainingID,
		&i.Label,
		&i.Prompt,
		&i.Unit,
		&i.PerHand,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
