// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assessments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAssessment = `-- name: CreateAssessment :one
INSERT INTO assessments (user_id, type, right_value, left_value, session_id, grip_position)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, type, right_value, left_value, session_id, grip_position, updated_at
`

type CreateAssessmentParams struct {
	UserID       pgtype.UUID
	Type         int32
	RightValue   pgtype.Float4
	LeftValue    pgtype.Float4
	SessionID    pgtype.UUID
	GripPosition pgtype.Int4
}

func (q *Queries) CreateAssessment(ctx context.Context, arg CreateAssessmentParams) (Assessment, error) {
	row := q.db.QueryRow(ctx, createAssessment,
		arg.UserID,
		arg.Type,
		arg.RightValue,
		arg.LeftValue,
		arg.SessionID,
		arg.GripPosition,
	)
	var i Assessment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.RightValue,
		&i.LeftValue,
		&i.SessionID,
		&i.GripPosition,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAssessment = `-- name: DeleteAssessment :exec
DELETE FROM assessments WHERE id = $1
`

func (q *Queries) DeleteAssessment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAssessment, id)
	return err
}

const getAssessment = `-- name: GetAssessment :one
SELECT id, user_id, type, right_value, left_value, session_id, grip_position, updated_at FROM assessments WHERE id = $1
`

func (q *Queries) GetAssessment(ctx context.Context, id pgtype.UUID) (Assessment, error) {
	row := q.db.QueryRow(ctx, getAssessment, id)
	var i Assessment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.RightValue,
		&i.LeftValue,
		&i.SessionID,
		&i.GripPosition,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionAssessments = `-- name: GetSessionAssessments :many
SELECT id, user_id, type, right_value, left_value, session_id, grip_position, updated_at FROM assessments WHERE session_id = $1
`

func (q *Queries) GetSessionAssessments(ctx context.Context, sessionID pgtype.UUID) ([]Assessment, error) {
	rows, err := q.db.Query(ctx, getSessionAssessments, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Assessment
	for rows.Next() {
		var i Assessment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.RightValue,
			&i.LeftValue,
			&i.SessionID,
			&i.GripPosition,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAssessments = `-- name: GetUserAssessments :many
SELECT a.id, a.user_id, a.type, a.right_value, a.left_value, a.session_id, a.grip_position, a.updated_at, s.date AS session_date FROM assessments a
JOIN sessions s ON a.session_id = s.id
WHERE s.user_id = $1
ORDER BY s.date DESC
`

type GetUserAssessmentsRow struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Type         int32
	RightValue   pgtype.Float4
	LeftValue    pgtype.Float4
	SessionID    pgtype.UUID
	GripPosition pgtype.Int4
	UpdatedAt    pgtype.Timestamptz
	SessionDate  pgtype.Timestamptz
}

func (q *Queries) GetUserAssessments(ctx context.Context, userID pgtype.UUID) ([]GetUserAssessmentsRow, error) {
	rows, err := q.db.Query(ctx, getUserAssessments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserAssessmentsRow
	for rows.Next() {
		var i GetUserAssessmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.RightValue,
			&i.LeftValue,
			&i.SessionID,
			&i.GripPosition,
			&i.UpdatedAt,
			&i.SessionDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserLatestAssessmentValues = `-- name: GetUserLatestAssessmentValues :many
WITH measured AS (
  SELECT a.type, a.right_value, a.left_value, s.date
  FROM assessments a
  JOIN sessions s ON s.id = a.session_id
  WHERE a.user_id = $1
),
last_right AS (
  SELECT DISTINCT ON (type) type, right_value
  FROM measured WHERE right_value IS NOT NULL
  ORDER BY type, date DESC
),
last_left AS (
  SELECT DISTINCT ON (type) type, left_value
  FROM measured WHERE left_value IS NOT NULL
  ORDER BY type, date DESC
)
SELECT
  COALESCE(last_right.type, last_left.type)::int AS type,
  last_right.right_value,
  last_left.left_value
FROM last_right
FULL OUTER JOIN last_left ON last_left.type = last_right.type
ORDER BY 1
`

type GetUserLatestAssessmentValuesRow struct {
	Type       int32
	RightValue pgtype.Float4
	LeftValue  pgtype.Float4
}

// The athlete's assessment results as they stand: the last value measured for
// each assessment and each hand, by the date of the session that recorded it.
// The hands are tracked apart, so a later assessment carrying only one of them
// does not discard the other hand's last measurement, which is how the clients
// resolve a percentage of an assessment.
func (q *Queries) GetUserLatestAssessmentValues(ctx context.Context, userID pgtype.UUID) ([]GetUserLatestAssessmentValuesRow, error) {
	rows, err := q.db.Query(ctx, getUserLatestAssessmentValues, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserLatestAssessmentValuesRow
	for rows.Next() {
		var i GetUserLatestAssessmentValuesRow
		if err := rows.Scan(&i.Type, &i.RightValue, &i.LeftValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
