// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package db

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const insertCoacheeDayActivity = `-- name: InsertCoacheeDayActivity :batchexec
INSERT INTO coachee_day_activities (
  declaration_id, day_of_week, position, label, duration_minutes, when_text, where_text
)
VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
`

type InsertCoacheeDayActivityBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertCoacheeDayActivityParams struct {
	DeclarationID   pgtype.UUID
	DayOfWeek       int32
	Position        int32
	Label           string
	DurationMinutes pgtype.Int4
	WhenText        pgtype.Text
	WhereText       pgtype.Text
}

// Batched rather than issued one at a time: a week may carry as many as
// 7 x maxActivitiesPerDay activities, and a round trip each would hold the
// write transaction open against the request deadline for no reason.
func (q *Queries) InsertCoacheeDayActivity(ctx context.Context, arg []InsertCoacheeDayActivityParams) *InsertCoacheeDayActivityBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.DeclarationID,
			a.DayOfWeek,
			a.Position,
			a.Label,
			a.DurationMinutes,
			a.WhenText,
			a.WhereText,
		}
		batch.Queue(insertCoacheeDayActivity, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertCoacheeDayActivityBatchResults{br, len(arg), false}
}

func (b *InsertCoacheeDayActivityBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertCoacheeDayActivityBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
