// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: builtin_training_weights.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBuiltinTrainingWeight = `-- name: CreateBuiltinTrainingWeight :one
INSERT INTO builtin_training_weights (id, user_id, builtin_training_id, custom_weight_left, custom_weight_right)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, builtin_training_id, custom_weight_left, custom_weight_right, updated_at
`

type CreateBuiltinTrainingWeightParams struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	BuiltinTrainingID pgtype.UUID
	CustomWeightLeft  float32
	CustomWeightRight float32
}

func (q *Queries) CreateBuiltinTrainingWeight(ctx context.Context, arg CreateBuiltinTrainingWeightParams) (BuiltinTrainingWeight, error) {
	row := q.db.QueryRow(ctx, createBuiltinTrainingWeight,
		arg.ID,
		arg.UserID,
		arg.BuiltinTrainingID,
		arg.CustomWeightLeft,
		arg.CustomWeightRight,
	)
	var i BuiltinTrainingWeight
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BuiltinTrainingID,
		&i.CustomWeightLeft,
		&i.CustomWeightRight,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBuiltinTrainingWeight = `-- name: DeleteBuiltinTrainingWeight :exec
DELETE FROM builtin_training_weights WHERE id = $1
`

func (q *Queries) DeleteBuiltinTrainingWeight(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBuiltinTrainingWeight, id)
	return err
}

const getBuiltinTrainingWeight = `-- name: GetBuiltinTrainingWeight :one
SELECT id, user_id, builtin_training_id, custom_weight_left, custom_weight_right, updated_at FROM builtin_training_weights WHERE id = $1
`

func (q *Queries) GetBuiltinTrainingWeight(ctx context.Context, id pgtype.UUID) (BuiltinTrainingWeight, error) {
	row := q.db.QueryRow(ctx, getBuiltinTrainingWeight, id)
	var i BuiltinTrainingWeight
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BuiltinTrainingID,
		&i.CustomWeightLeft,
		&i.CustomWeightRight,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserBuiltinTrainingWeights = `-- name: GetUserBuiltinTrainingWeights :many
SELECT id, user_id, builtin_training_id, custom_weight_left, custom_weight_right, updated_at FROM builtin_training_weights WHERE user_id = $1
`

func (q *Queries) GetUserBuiltinTrainingWeights(ctx context.Context, userID pgtype.UUID) ([]BuiltinTrainingWeight, error) {
	rows, err := q.db.Query(ctx, getUserBuiltinTrainingWeights, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuiltinTrainingWeight
	for rows.Next() {
		var i BuiltinTrainingWeight
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BuiltinTrainingID,
			&i.CustomWeightLeft,
			&i.CustomWeightRight,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBuiltinTrainingWeight = `-- name: UpdateBuiltinTrainingWeight :one
UPDATE builtin_training_weights
SET custom_weight_left = $2, custom_weight_right = $3, updated_at = now()
WHERE id = $1
RETURNING id, user_id, builtin_training_id, custom_weight_left, custom_weight_right, updated_at
`

type UpdateBuiltinTrainingWeightParams struct {
	ID                pgtype.UUID
	CustomWeightLeft  float32
	CustomWeightRight float32
}

func (q *Queries) UpdateBuiltinTrainingWeight(ctx context.Context, arg UpdateBuiltinTrainingWeightParams) (BuiltinTrainingWeight, error) {
	row := q.db.QueryRow(ctx, updateBuiltinTrainingWeight, arg.ID, arg.CustomWeightLeft, arg.CustomWeightRight)
	var i BuiltinTrainingWeight
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BuiltinTrainingID,
		&i.CustomWeightLeft,
		&i.CustomWeightRight,
		&i.UpdatedAt,
	)
	return i, err
}
