// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coach_program_weeks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCoachProgramWeekSession = `-- name: CreateCoachProgramWeekSession :one
INSERT INTO coach_program_week_sessions
  (week_id, training_id, day_of_week, times_per_week, is_everyday, position, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, week_id, training_id, day_of_week, times_per_week, is_everyday, position, notes, created_at, updated_at
`

type CreateCoachProgramWeekSessionParams struct {
	WeekID       pgtype.UUID
	TrainingID   pgtype.UUID
	DayOfWeek    pgtype.Int4
	TimesPerWeek pgtype.Int4
	IsEveryday   bool
	Position     int32
	Notes        pgtype.Text
}

func (q *Queries) CreateCoachProgramWeekSession(ctx context.Context, arg CreateCoachProgramWeekSessionParams) (CoachProgramWeekSession, error) {
	row := q.db.QueryRow(ctx, createCoachProgramWeekSession,
		arg.WeekID,
		arg.TrainingID,
		arg.DayOfWeek,
		arg.TimesPerWeek,
		arg.IsEveryday,
		arg.Position,
		arg.Notes,
	)
	var i CoachProgramWeekSession
	err := row.Scan(
		&i.ID,
		&i.WeekID,
		&i.TrainingID,
		&i.DayOfWeek,
		&i.TimesPerWeek,
		&i.IsEveryday,
		&i.Position,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCoachProgramWeek = `-- name: DeleteCoachProgramWeek :exec
DELETE FROM coach_program_weeks
WHERE program_id = $1 AND week_number = $2
`

type DeleteCoachProgramWeekParams struct {
	ProgramID  pgtype.UUID
	WeekNumber int32
}

func (q *Queries) DeleteCoachProgramWeek(ctx context.Context, arg DeleteCoachProgramWeekParams) error {
	_, err := q.db.Exec(ctx, deleteCoachProgramWeek, arg.ProgramID, arg.WeekNumber)
	return err
}

const deleteCoachProgramWeekSessions = `-- name: DeleteCoachProgramWeekSessions :exec
DELETE FROM coach_program_week_sessions WHERE week_id = $1
`

func (q *Queries) DeleteCoachProgramWeekSessions(ctx context.Context, weekID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCoachProgramWeekSessions, weekID)
	return err
}

const getCoachProgramWeek = `-- name: GetCoachProgramWeek :one
SELECT id, program_id, week_number, notes, created_at, updated_at FROM coach_program_weeks
WHERE program_id = $1 AND week_number = $2
`

type GetCoachProgramWeekParams struct {
	ProgramID  pgtype.UUID
	WeekNumber int32
}

func (q *Queries) GetCoachProgramWeek(ctx context.Context, arg GetCoachProgramWeekParams) (CoachProgramWeek, error) {
	row := q.db.QueryRow(ctx, getCoachProgramWeek, arg.ProgramID, arg.WeekNumber)
	var i CoachProgramWeek
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.WeekNumber,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCoachProgramWeekOverrides = `-- name: GetCoachProgramWeekOverrides :many
SELECT o.id, o.session_id, o.item_id, o.overrides, o.created_at, o.updated_at
FROM coach_program_session_overrides o
JOIN coach_program_week_sessions s ON s.id = o.session_id
WHERE s.week_id = $1
`

func (q *Queries) GetCoachProgramWeekOverrides(ctx context.Context, weekID pgtype.UUID) ([]CoachProgramSessionOverride, error) {
	rows, err := q.db.Query(ctx, getCoachProgramWeekOverrides, weekID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoachProgramSessionOverride
	for rows.Next() {
		var i CoachProgramSessionOverride
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ItemID,
			&i.Overrides,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoachProgramWeekSessions = `-- name: GetCoachProgramWeekSessions :many
SELECT
  s.id,
  s.week_id,
  s.training_id,
  s.day_of_week,
  s.times_per_week,
  s.is_everyday,
  s.position,
  s.notes        AS session_notes,
  s.created_at,
  s.updated_at,
  ct.title         AS training_title,
  ct.training_type AS training_type
FROM coach_program_week_sessions s
JOIN trainings ct ON ct.id = s.training_id
WHERE s.week_id = $1
ORDER BY s.position
`

type GetCoachProgramWeekSessionsRow struct {
	ID            pgtype.UUID
	WeekID        pgtype.UUID
	TrainingID    pgtype.UUID
	DayOfWeek     pgtype.Int4
	TimesPerWeek  pgtype.Int4
	IsEveryday    bool
	Position      int32
	SessionNotes  pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	TrainingTitle string
	TrainingType  string
}

func (q *Queries) GetCoachProgramWeekSessions(ctx context.Context, weekID pgtype.UUID) ([]GetCoachProgramWeekSessionsRow, error) {
	rows, err := q.db.Query(ctx, getCoachProgramWeekSessions, weekID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCoachProgramWeekSessionsRow
	for rows.Next() {
		var i GetCoachProgramWeekSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.WeekID,
			&i.TrainingID,
			&i.DayOfWeek,
			&i.TimesPerWeek,
			&i.IsEveryday,
			&i.Position,
			&i.SessionNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrainingTitle,
			&i.TrainingType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoachProgramWeeks = `-- name: GetCoachProgramWeeks :many
SELECT id, program_id, week_number, notes, created_at, updated_at FROM coach_program_weeks
WHERE program_id = $1
ORDER BY week_number
`

func (q *Queries) GetCoachProgramWeeks(ctx context.Context, programID pgtype.UUID) ([]CoachProgramWeek, error) {
	rows, err := q.db.Query(ctx, getCoachProgramWeeks, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoachProgramWeek
	for rows.Next() {
		var i CoachProgramWeek
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.WeekNumber,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCoachProgramSessionOverride = `-- name: UpsertCoachProgramSessionOverride :one
INSERT INTO coach_program_session_overrides (session_id, item_id, overrides)
VALUES ($1, $2, $3)
ON CONFLICT (session_id, item_id) DO UPDATE
  SET overrides = EXCLUDED.overrides, updated_at = now()
RETURNING id, session_id, item_id, overrides, created_at, updated_at
`

type UpsertCoachProgramSessionOverrideParams struct {
	SessionID pgtype.UUID
	ItemID    pgtype.UUID
	Overrides []byte
}

func (q *Queries) UpsertCoachProgramSessionOverride(ctx context.Context, arg UpsertCoachProgramSessionOverrideParams) (CoachProgramSessionOverride, error) {
	row := q.db.QueryRow(ctx, upsertCoachProgramSessionOverride, arg.SessionID, arg.ItemID, arg.Overrides)
	var i CoachProgramSessionOverride
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ItemID,
		&i.Overrides,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCoachProgramWeek = `-- name: UpsertCoachProgramWeek :one
INSERT INTO coach_program_weeks (program_id, week_number, notes)
VALUES ($1, $2, $3)
ON CONFLICT (program_id, week_number) DO UPDATE
  SET notes = EXCLUDED.notes, updated_at = now()
RETURNING id, program_id, week_number, notes, created_at, updated_at
`

type UpsertCoachProgramWeekParams struct {
	ProgramID  pgtype.UUID
	WeekNumber int32
	Notes      pgtype.Text
}

func (q *Queries) UpsertCoachProgramWeek(ctx context.Context, arg UpsertCoachProgramWeekParams) (CoachProgramWeek, error) {
	row := q.db.QueryRow(ctx, upsertCoachProgramWeek, arg.ProgramID, arg.WeekNumber, arg.Notes)
	var i CoachProgramWeek
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.WeekNumber,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
