// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coachee_availability.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCoacheeWeekActivities = `-- name: DeleteCoacheeWeekActivities :exec
DELETE FROM coachee_day_activities
WHERE declaration_id = $1
`

func (q *Queries) DeleteCoacheeWeekActivities(ctx context.Context, declarationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCoacheeWeekActivities, declarationID)
	return err
}

const getCoacheeWeekDeclaration = `-- name: GetCoacheeWeekDeclaration :one
SELECT id, user_id, week_start, created_at, updated_at FROM coachee_week_declarations
WHERE user_id = $1 AND week_start = $2
`

type GetCoacheeWeekDeclarationParams struct {
	UserID    pgtype.UUID
	WeekStart pgtype.Date
}

func (q *Queries) GetCoacheeWeekDeclaration(ctx context.Context, arg GetCoacheeWeekDeclarationParams) (CoacheeWeekDeclaration, error) {
	row := q.db.QueryRow(ctx, getCoacheeWeekDeclaration, arg.UserID, arg.WeekStart)
	var i CoacheeWeekDeclaration
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WeekStart,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCoacheeDayActivity = `-- name: InsertCoacheeDayActivity :exec
INSERT INTO coachee_day_activities (
  declaration_id, day_of_week, position, label, duration_minutes, when_text, where_text
)
VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
`

type InsertCoacheeDayActivityParams struct {
	DeclarationID   pgtype.UUID
	DayOfWeek       int32
	Position        int32
	Label           string
	DurationMinutes pgtype.Int4
	WhenText        pgtype.Text
	WhereText       pgtype.Text
}

func (q *Queries) InsertCoacheeDayActivity(ctx context.Context, arg InsertCoacheeDayActivityParams) error {
	_, err := q.db.Exec(ctx, insertCoacheeDayActivity,
		arg.DeclarationID,
		arg.DayOfWeek,
		arg.Position,
		arg.Label,
		arg.DurationMinutes,
		arg.WhenText,
		arg.WhereText,
	)
	return err
}

const listCoacheeDayActivities = `-- name: ListCoacheeDayActivities :many
SELECT a.id, a.declaration_id, a.day_of_week, a.position, a.label, a.duration_minutes, a.when_text, a.where_text, a.created_at FROM coachee_day_activities a
JOIN coachee_week_declarations d ON d.id = a.declaration_id
WHERE d.user_id = $1
ORDER BY d.week_start, a.day_of_week, a.position
`

// Every activity the athlete holds, across every week they declared, ordered so
// it zips straight onto the declarations above.
func (q *Queries) ListCoacheeDayActivities(ctx context.Context, userID pgtype.UUID) ([]CoacheeDayActivity, error) {
	rows, err := q.db.Query(ctx, listCoacheeDayActivities, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoacheeDayActivity
	for rows.Next() {
		var i CoacheeDayActivity
		if err := rows.Scan(
			&i.ID,
			&i.DeclarationID,
			&i.DayOfWeek,
			&i.Position,
			&i.Label,
			&i.DurationMinutes,
			&i.WhenText,
			&i.WhereText,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoacheeWeekDayActivities = `-- name: ListCoacheeWeekDayActivities :many
SELECT id, declaration_id, day_of_week, position, label, duration_minutes, when_text, where_text, created_at FROM coachee_day_activities
WHERE declaration_id = $1
ORDER BY day_of_week, position
`

func (q *Queries) ListCoacheeWeekDayActivities(ctx context.Context, declarationID pgtype.UUID) ([]CoacheeDayActivity, error) {
	rows, err := q.db.Query(ctx, listCoacheeWeekDayActivities, declarationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoacheeDayActivity
	for rows.Next() {
		var i CoacheeDayActivity
		if err := rows.Scan(
			&i.ID,
			&i.DeclarationID,
			&i.DayOfWeek,
			&i.Position,
			&i.Label,
			&i.DurationMinutes,
			&i.WhenText,
			&i.WhereText,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoacheeWeekDeclarations = `-- name: ListCoacheeWeekDeclarations :many
SELECT id, user_id, week_start, created_at, updated_at FROM coachee_week_declarations
WHERE user_id = $1
ORDER BY week_start
`

func (q *Queries) ListCoacheeWeekDeclarations(ctx context.Context, userID pgtype.UUID) ([]CoacheeWeekDeclaration, error) {
	rows, err := q.db.Query(ctx, listCoacheeWeekDeclarations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoacheeWeekDeclaration
	for rows.Next() {
		var i CoacheeWeekDeclaration
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WeekStart,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCoacheeWeekDeclaration = `-- name: UpsertCoacheeWeekDeclaration :one
INSERT INTO coachee_week_declarations (user_id, week_start)
VALUES ($1, $2)
ON CONFLICT (user_id, week_start) DO UPDATE
  SET updated_at = now()
RETURNING id, user_id, week_start, created_at, updated_at
`

type UpsertCoacheeWeekDeclarationParams struct {
	UserID    pgtype.UUID
	WeekStart pgtype.Date
}

// Declaring a week the athlete has already declared is a re-answer, not a new
// one, so the row keeps its identity and only moves its updated_at. That is
// what the coach feed dates the event by.
func (q *Queries) UpsertCoacheeWeekDeclaration(ctx context.Context, arg UpsertCoacheeWeekDeclarationParams) (CoacheeWeekDeclaration, error) {
	row := q.db.QueryRow(ctx, upsertCoacheeWeekDeclaration, arg.UserID, arg.WeekStart)
	var i CoacheeWeekDeclaration
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WeekStart,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
