// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coach_programs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCoachProgram = `-- name: CreateCoachProgram :one
INSERT INTO coach_programs (coach_id, user_id, name, objective, start_date, duration_weeks)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, coach_id, user_id, name, objective, start_date, duration_weeks, created_at, updated_at
`

type CreateCoachProgramParams struct {
	CoachID       pgtype.UUID
	UserID        pgtype.UUID
	Name          string
	Objective     pgtype.Text
	StartDate     pgtype.Date
	DurationWeeks pgtype.Int4
}

func (q *Queries) CreateCoachProgram(ctx context.Context, arg CreateCoachProgramParams) (CoachProgram, error) {
	row := q.db.QueryRow(ctx, createCoachProgram,
		arg.CoachID,
		arg.UserID,
		arg.Name,
		arg.Objective,
		arg.StartDate,
		arg.DurationWeeks,
	)
	var i CoachProgram
	err := row.Scan(
		&i.ID,
		&i.CoachID,
		&i.UserID,
		&i.Name,
		&i.Objective,
		&i.StartDate,
		&i.DurationWeeks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCoachProgramSlot = `-- name: CreateCoachProgramSlot :one
INSERT INTO coach_program_slots (program_id, training_id, day_of_week, times_per_week, position)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, program_id, training_id, day_of_week, times_per_week, position, created_at
`

type CreateCoachProgramSlotParams struct {
	ProgramID    pgtype.UUID
	TrainingID   pgtype.UUID
	DayOfWeek    pgtype.Int4
	TimesPerWeek pgtype.Int4
	Position     int32
}

func (q *Queries) CreateCoachProgramSlot(ctx context.Context, arg CreateCoachProgramSlotParams) (CoachProgramSlot, error) {
	row := q.db.QueryRow(ctx, createCoachProgramSlot,
		arg.ProgramID,
		arg.TrainingID,
		arg.DayOfWeek,
		arg.TimesPerWeek,
		arg.Position,
	)
	var i CoachProgramSlot
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.TrainingID,
		&i.DayOfWeek,
		&i.TimesPerWeek,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCoachProgram = `-- name: DeleteCoachProgram :exec
DELETE FROM coach_programs WHERE id = $1
`

func (q *Queries) DeleteCoachProgram(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCoachProgram, id)
	return err
}

const deleteCoachProgramSlots = `-- name: DeleteCoachProgramSlots :exec
DELETE FROM coach_program_slots WHERE program_id = $1
`

func (q *Queries) DeleteCoachProgramSlots(ctx context.Context, programID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCoachProgramSlots, programID)
	return err
}

const getCoachProgram = `-- name: GetCoachProgram :one
SELECT id, coach_id, user_id, name, objective, start_date, duration_weeks, created_at, updated_at FROM coach_programs WHERE id = $1
`

func (q *Queries) GetCoachProgram(ctx context.Context, id pgtype.UUID) (CoachProgram, error) {
	row := q.db.QueryRow(ctx, getCoachProgram, id)
	var i CoachProgram
	err := row.Scan(
		&i.ID,
		&i.CoachID,
		&i.UserID,
		&i.Name,
		&i.Objective,
		&i.StartDate,
		&i.DurationWeeks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCoachProgramSlots = `-- name: GetCoachProgramSlots :many
SELECT
  cps.id,
  cps.program_id,
  cps.training_id,
  cps.day_of_week,
  cps.times_per_week,
  cps.position,
  cps.created_at,
  ct.title          AS training_title,
  ct.training_type  AS training_type
FROM coach_program_slots cps
JOIN coach_trainings ct ON ct.id = cps.training_id
WHERE cps.program_id = $1
ORDER BY cps.position
`

type GetCoachProgramSlotsRow struct {
	ID            pgtype.UUID
	ProgramID     pgtype.UUID
	TrainingID    pgtype.UUID
	DayOfWeek     pgtype.Int4
	TimesPerWeek  pgtype.Int4
	Position      int32
	CreatedAt     pgtype.Timestamptz
	TrainingTitle string
	TrainingType  string
}

func (q *Queries) GetCoachProgramSlots(ctx context.Context, programID pgtype.UUID) ([]GetCoachProgramSlotsRow, error) {
	rows, err := q.db.Query(ctx, getCoachProgramSlots, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCoachProgramSlotsRow
	for rows.Next() {
		var i GetCoachProgramSlotsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.TrainingID,
			&i.DayOfWeek,
			&i.TimesPerWeek,
			&i.Position,
			&i.CreatedAt,
			&i.TrainingTitle,
			&i.TrainingType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoachProgramsForClient = `-- name: GetCoachProgramsForClient :many
SELECT id, coach_id, user_id, name, objective, start_date, duration_weeks, created_at, updated_at FROM coach_programs
WHERE coach_id = $1 AND user_id = $2
ORDER BY start_date DESC
`

type GetCoachProgramsForClientParams struct {
	CoachID pgtype.UUID
	UserID  pgtype.UUID
}

func (q *Queries) GetCoachProgramsForClient(ctx context.Context, arg GetCoachProgramsForClientParams) ([]CoachProgram, error) {
	rows, err := q.db.Query(ctx, getCoachProgramsForClient, arg.CoachID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoachProgram
	for rows.Next() {
		var i CoachProgram
		if err := rows.Scan(
			&i.ID,
			&i.CoachID,
			&i.UserID,
			&i.Name,
			&i.Objective,
			&i.StartDate,
			&i.DurationWeeks,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMyPrograms = `-- name: GetMyPrograms :many
SELECT id, coach_id, user_id, name, objective, start_date, duration_weeks, created_at, updated_at FROM coach_programs WHERE user_id = $1 ORDER BY start_date DESC
`

func (q *Queries) GetMyPrograms(ctx context.Context, userID pgtype.UUID) ([]CoachProgram, error) {
	rows, err := q.db.Query(ctx, getMyPrograms, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoachProgram
	for rows.Next() {
		var i CoachProgram
		if err := rows.Scan(
			&i.ID,
			&i.CoachID,
			&i.UserID,
			&i.Name,
			&i.Objective,
			&i.StartDate,
			&i.DurationWeeks,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCoachProgram = `-- name: UpdateCoachProgram :one
UPDATE coach_programs
SET name = $1, objective = $2, start_date = $3,
    duration_weeks = $4, updated_at = now()
WHERE id = $5
RETURNING id, coach_id, user_id, name, objective, start_date, duration_weeks, created_at, updated_at
`

type UpdateCoachProgramParams struct {
	Name          string
	Objective     pgtype.Text
	StartDate     pgtype.Date
	DurationWeeks pgtype.Int4
	ID            pgtype.UUID
}

func (q *Queries) UpdateCoachProgram(ctx context.Context, arg UpdateCoachProgramParams) (CoachProgram, error) {
	row := q.db.QueryRow(ctx, updateCoachProgram,
		arg.Name,
		arg.Objective,
		arg.StartDate,
		arg.DurationWeeks,
		arg.ID,
	)
	var i CoachProgram
	err := row.Scan(
		&i.ID,
		&i.CoachID,
		&i.UserID,
		&i.Name,
		&i.Objective,
		&i.StartDate,
		&i.DurationWeeks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
