// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coach_trainings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCoachTraining = `-- name: CreateCoachTraining :one
INSERT INTO coach_trainings (coach_id, title, description, training_type, goal, comment)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, coach_id, title, description, training_type, goal, comment, created_at, updated_at
`

type CreateCoachTrainingParams struct {
	CoachID      pgtype.UUID
	Title        string
	Description  pgtype.Text
	TrainingType string
	Goal         string
	Comment      string
}

func (q *Queries) CreateCoachTraining(ctx context.Context, arg CreateCoachTrainingParams) (CoachTraining, error) {
	row := q.db.QueryRow(ctx, createCoachTraining,
		arg.CoachID,
		arg.Title,
		arg.Description,
		arg.TrainingType,
		arg.Goal,
		arg.Comment,
	)
	var i CoachTraining
	err := row.Scan(
		&i.ID,
		&i.CoachID,
		&i.Title,
		&i.Description,
		&i.TrainingType,
		&i.Goal,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCoachTrainingItem = `-- name: CreateCoachTrainingItem :one
INSERT INTO coach_training_items (
  training_id, parent_id, type, position,
  cycles, cycle_rest_seconds,
  reps, duration, rest_seconds,
  exercise_id,
  hb_worktime_seconds, both_hands,
  loads, left_loads, hand_positions, edge_sizes_mm,
  section_title
) VALUES (
  $1, $2, $3, $4,
  $5, $6,
  $7, $8, $9,
  $10,
  $11, $12,
  $13, $14, $15, $16,
  $17
)
RETURNING id, training_id, parent_id, type, position, cycles, cycle_rest_seconds, reps, duration, rest_seconds, exercise_id, hb_worktime_seconds, both_hands, loads, left_loads, hand_positions, edge_sizes_mm, section_title, created_at, updated_at
`

type CreateCoachTrainingItemParams struct {
	TrainingID        pgtype.UUID
	ParentID          pgtype.UUID
	Type              string
	Position          int32
	Cycles            pgtype.Int4
	CycleRestSeconds  pgtype.Int4
	Reps              pgtype.Int4
	Duration          pgtype.Int4
	RestSeconds       pgtype.Int4
	ExerciseID        pgtype.UUID
	HbWorktimeSeconds pgtype.Int4
	BothHands         pgtype.Bool
	Loads             []byte
	LeftLoads         []byte
	HandPositions     []byte
	EdgeSizesMm       []byte
	SectionTitle      pgtype.Text
}

func (q *Queries) CreateCoachTrainingItem(ctx context.Context, arg CreateCoachTrainingItemParams) (CoachTrainingItem, error) {
	row := q.db.QueryRow(ctx, createCoachTrainingItem,
		arg.TrainingID,
		arg.ParentID,
		arg.Type,
		arg.Position,
		arg.Cycles,
		arg.CycleRestSeconds,
		arg.Reps,
		arg.Duration,
		arg.RestSeconds,
		arg.ExerciseID,
		arg.HbWorktimeSeconds,
		arg.BothHands,
		arg.Loads,
		arg.LeftLoads,
		arg.HandPositions,
		arg.EdgeSizesMm,
		arg.SectionTitle,
	)
	var i CoachTrainingItem
	err := row.Scan(
		&i.ID,
		&i.TrainingID,
		&i.ParentID,
		&i.Type,
		&i.Position,
		&i.Cycles,
		&i.CycleRestSeconds,
		&i.Reps,
		&i.Duration,
		&i.RestSeconds,
		&i.ExerciseID,
		&i.HbWorktimeSeconds,
		&i.BothHands,
		&i.Loads,
		&i.LeftLoads,
		&i.HandPositions,
		&i.EdgeSizesMm,
		&i.SectionTitle,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCoachTraining = `-- name: DeleteCoachTraining :exec
DELETE FROM coach_trainings WHERE id = $1
`

func (q *Queries) DeleteCoachTraining(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCoachTraining, id)
	return err
}

const deleteCoachTrainingItems = `-- name: DeleteCoachTrainingItems :exec
DELETE FROM coach_training_items WHERE training_id = $1
`

func (q *Queries) DeleteCoachTrainingItems(ctx context.Context, trainingID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCoachTrainingItems, trainingID)
	return err
}

const getCoachTraining = `-- name: GetCoachTraining :one
SELECT id, coach_id, title, description, training_type, goal, comment, created_at, updated_at FROM coach_trainings WHERE id = $1
`

func (q *Queries) GetCoachTraining(ctx context.Context, id pgtype.UUID) (CoachTraining, error) {
	row := q.db.QueryRow(ctx, getCoachTraining, id)
	var i CoachTraining
	err := row.Scan(
		&i.ID,
		&i.CoachID,
		&i.Title,
		&i.Description,
		&i.TrainingType,
		&i.Goal,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCoachTrainingItems = `-- name: GetCoachTrainingItems :many
SELECT id, training_id, parent_id, type, position, cycles, cycle_rest_seconds, reps, duration, rest_seconds, exercise_id, hb_worktime_seconds, both_hands, loads, left_loads, hand_positions, edge_sizes_mm, section_title, created_at, updated_at FROM coach_training_items WHERE training_id = $1 ORDER BY position
`

func (q *Queries) GetCoachTrainingItems(ctx context.Context, trainingID pgtype.UUID) ([]CoachTrainingItem, error) {
	rows, err := q.db.Query(ctx, getCoachTrainingItems, trainingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoachTrainingItem
	for rows.Next() {
		var i CoachTrainingItem
		if err := rows.Scan(
			&i.ID,
			&i.TrainingID,
			&i.ParentID,
			&i.Type,
			&i.Position,
			&i.Cycles,
			&i.CycleRestSeconds,
			&i.Reps,
			&i.Duration,
			&i.RestSeconds,
			&i.ExerciseID,
			&i.HbWorktimeSeconds,
			&i.BothHands,
			&i.Loads,
			&i.LeftLoads,
			&i.HandPositions,
			&i.EdgeSizesMm,
			&i.SectionTitle,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoachTrainings = `-- name: GetCoachTrainings :many
SELECT id, coach_id, title, description, training_type, goal, comment, created_at, updated_at FROM coach_trainings WHERE coach_id = $1 ORDER BY title
`

func (q *Queries) GetCoachTrainings(ctx context.Context, coachID pgtype.UUID) ([]CoachTraining, error) {
	rows, err := q.db.Query(ctx, getCoachTrainings, coachID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoachTraining
	for rows.Next() {
		var i CoachTraining
		if err := rows.Scan(
			&i.ID,
			&i.CoachID,
			&i.Title,
			&i.Description,
			&i.TrainingType,
			&i.Goal,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCoachTraining = `-- name: UpdateCoachTraining :one
UPDATE coach_trainings
SET title = $1, description = $2, training_type = $3, goal = $4, comment = $5, updated_at = now()
WHERE id = $6
RETURNING id, coach_id, title, description, training_type, goal, comment, created_at, updated_at
`

type UpdateCoachTrainingParams struct {
	Title        string
	Description  pgtype.Text
	TrainingType string
	Goal         string
	Comment      string
	ID           pgtype.UUID
}

func (q *Queries) UpdateCoachTraining(ctx context.Context, arg UpdateCoachTrainingParams) (CoachTraining, error) {
	row := q.db.QueryRow(ctx, updateCoachTraining,
		arg.Title,
		arg.Description,
		arg.TrainingType,
		arg.Goal,
		arg.Comment,
		arg.ID,
	)
	var i CoachTraining
	err := row.Scan(
		&i.ID,
		&i.CoachID,
		&i.Title,
		&i.Description,
		&i.TrainingType,
		&i.Goal,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
