// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coach_program_weeks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPlayedSessionsInProgram = `-- name: CountPlayedSessionsInProgram :one
SELECT COUNT(*) FROM sessions played
JOIN coach_program_week_sessions s ON s.id = played.program_session_id
JOIN coach_program_weeks w ON w.id = s.week_id
WHERE w.program_id = $1 AND played.origin = 'played'
`

func (q *Queries) CountPlayedSessionsInProgram(ctx context.Context, programID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPlayedSessionsInProgram, programID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPlayedSessionsInWeek = `-- name: CountPlayedSessionsInWeek :one
SELECT COUNT(*) FROM sessions played
JOIN coach_program_week_sessions s ON s.id = played.program_session_id
JOIN coach_program_weeks w ON w.id = s.week_id
WHERE w.program_id = $1 AND w.week_number = $2
  AND played.origin = 'played'
`

type CountPlayedSessionsInWeekParams struct {
	ProgramID  pgtype.UUID
	WeekNumber int32
}

func (q *Queries) CountPlayedSessionsInWeek(ctx context.Context, arg CountPlayedSessionsInWeekParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPlayedSessionsInWeek, arg.ProgramID, arg.WeekNumber)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCoachProgramWeekSession = `-- name: CreateCoachProgramWeekSession :one
INSERT INTO coach_program_week_sessions
  (week_id, training_id, day_of_week, times_per_week, is_everyday, position, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, week_id, training_id, day_of_week, times_per_week, is_everyday, position, notes, created_at, updated_at
`

type CreateCoachProgramWeekSessionParams struct {
	WeekID       pgtype.UUID
	TrainingID   pgtype.UUID
	DayOfWeek    pgtype.Int4
	TimesPerWeek pgtype.Int4
	IsEveryday   bool
	Position     int32
	Notes        pgtype.Text
}

func (q *Queries) CreateCoachProgramWeekSession(ctx context.Context, arg CreateCoachProgramWeekSessionParams) (CoachProgramWeekSession, error) {
	row := q.db.QueryRow(ctx, createCoachProgramWeekSession,
		arg.WeekID,
		arg.TrainingID,
		arg.DayOfWeek,
		arg.TimesPerWeek,
		arg.IsEveryday,
		arg.Position,
		arg.Notes,
	)
	var i CoachProgramWeekSession
	err := row.Scan(
		&i.ID,
		&i.WeekID,
		&i.TrainingID,
		&i.DayOfWeek,
		&i.TimesPerWeek,
		&i.IsEveryday,
		&i.Position,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCoachProgramSessionOverridesNotIn = `-- name: DeleteCoachProgramSessionOverridesNotIn :exec
DELETE FROM coach_program_session_overrides
WHERE session_id = $1 AND NOT (item_id = ANY($2::uuid[]))
`

type DeleteCoachProgramSessionOverridesNotInParams struct {
	SessionID   pgtype.UUID
	KeptItemIds []pgtype.UUID
}

func (q *Queries) DeleteCoachProgramSessionOverridesNotIn(ctx context.Context, arg DeleteCoachProgramSessionOverridesNotInParams) error {
	_, err := q.db.Exec(ctx, deleteCoachProgramSessionOverridesNotIn, arg.SessionID, arg.KeptItemIds)
	return err
}

const deleteCoachProgramWeek = `-- name: DeleteCoachProgramWeek :exec
DELETE FROM coach_program_weeks
WHERE program_id = $1 AND week_number = $2
`

type DeleteCoachProgramWeekParams struct {
	ProgramID  pgtype.UUID
	WeekNumber int32
}

func (q *Queries) DeleteCoachProgramWeek(ctx context.Context, arg DeleteCoachProgramWeekParams) error {
	_, err := q.db.Exec(ctx, deleteCoachProgramWeek, arg.ProgramID, arg.WeekNumber)
	return err
}

const deleteCoachProgramWeekSessionsNotIn = `-- name: DeleteCoachProgramWeekSessionsNotIn :exec
DELETE FROM coach_program_week_sessions
WHERE week_id = $1 AND NOT (id = ANY($2::uuid[]))
`

type DeleteCoachProgramWeekSessionsNotInParams struct {
	WeekID  pgtype.UUID
	KeptIds []pgtype.UUID
}

func (q *Queries) DeleteCoachProgramWeekSessionsNotIn(ctx context.Context, arg DeleteCoachProgramWeekSessionsNotInParams) error {
	_, err := q.db.Exec(ctx, deleteCoachProgramWeekSessionsNotIn, arg.WeekID, arg.KeptIds)
	return err
}

const getCoachProgramSessionOverrides = `-- name: GetCoachProgramSessionOverrides :many
SELECT id, session_id, item_id, overrides, created_at, updated_at FROM coach_program_session_overrides
WHERE session_id = $1
`

func (q *Queries) GetCoachProgramSessionOverrides(ctx context.Context, sessionID pgtype.UUID) ([]CoachProgramSessionOverride, error) {
	rows, err := q.db.Query(ctx, getCoachProgramSessionOverrides, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoachProgramSessionOverride
	for rows.Next() {
		var i CoachProgramSessionOverride
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ItemID,
			&i.Overrides,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoachProgramWeek = `-- name: GetCoachProgramWeek :one
SELECT id, program_id, week_number, notes, created_at, updated_at FROM coach_program_weeks
WHERE program_id = $1 AND week_number = $2
`

type GetCoachProgramWeekParams struct {
	ProgramID  pgtype.UUID
	WeekNumber int32
}

func (q *Queries) GetCoachProgramWeek(ctx context.Context, arg GetCoachProgramWeekParams) (CoachProgramWeek, error) {
	row := q.db.QueryRow(ctx, getCoachProgramWeek, arg.ProgramID, arg.WeekNumber)
	var i CoachProgramWeek
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.WeekNumber,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCoachProgramWeekOverrides = `-- name: GetCoachProgramWeekOverrides :many
SELECT o.id, o.session_id, o.item_id, o.overrides, o.created_at, o.updated_at
FROM coach_program_session_overrides o
JOIN coach_program_week_sessions s ON s.id = o.session_id
WHERE s.week_id = $1
`

func (q *Queries) GetCoachProgramWeekOverrides(ctx context.Context, weekID pgtype.UUID) ([]CoachProgramSessionOverride, error) {
	rows, err := q.db.Query(ctx, getCoachProgramWeekOverrides, weekID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoachProgramSessionOverride
	for rows.Next() {
		var i CoachProgramSessionOverride
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ItemID,
			&i.Overrides,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoachProgramWeekSession = `-- name: GetCoachProgramWeekSession :one
SELECT id, week_id, training_id, day_of_week, times_per_week, is_everyday, position, notes, created_at, updated_at FROM coach_program_week_sessions WHERE id = $1
`

func (q *Queries) GetCoachProgramWeekSession(ctx context.Context, id pgtype.UUID) (CoachProgramWeekSession, error) {
	row := q.db.QueryRow(ctx, getCoachProgramWeekSession, id)
	var i CoachProgramWeekSession
	err := row.Scan(
		&i.ID,
		&i.WeekID,
		&i.TrainingID,
		&i.DayOfWeek,
		&i.TimesPerWeek,
		&i.IsEveryday,
		&i.Position,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCoachProgramWeekSessions = `-- name: GetCoachProgramWeekSessions :many
SELECT
  s.id,
  s.week_id,
  s.training_id,
  s.day_of_week,
  s.times_per_week,
  s.is_everyday,
  s.position,
  s.notes        AS session_notes,
  s.created_at,
  s.updated_at,
  ct.title         AS training_title,
  ct.training_type AS training_type,
  -- Locked once played: the prescription must keep describing what was played.
  -- Only a played session counts. A logged one may not hold the link at all
  -- (sessions_logged_has_no_program_session_check), and treating it as locking
  -- would hand an athlete a way to freeze their coach's week by hand.
  EXISTS (
    SELECT 1 FROM sessions played
    WHERE played.program_session_id = s.id AND played.origin = 'played'
  ) AS is_locked
FROM coach_program_week_sessions s
JOIN trainings ct ON ct.id = s.training_id
WHERE s.week_id = $1
ORDER BY s.position
`

type GetCoachProgramWeekSessionsRow struct {
	ID            pgtype.UUID
	WeekID        pgtype.UUID
	TrainingID    pgtype.UUID
	DayOfWeek     pgtype.Int4
	TimesPerWeek  pgtype.Int4
	IsEveryday    bool
	Position      int32
	SessionNotes  pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	TrainingTitle string
	TrainingType  string
	IsLocked      bool
}

func (q *Queries) GetCoachProgramWeekSessions(ctx context.Context, weekID pgtype.UUID) ([]GetCoachProgramWeekSessionsRow, error) {
	rows, err := q.db.Query(ctx, getCoachProgramWeekSessions, weekID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCoachProgramWeekSessionsRow
	for rows.Next() {
		var i GetCoachProgramWeekSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.WeekID,
			&i.TrainingID,
			&i.DayOfWeek,
			&i.TimesPerWeek,
			&i.IsEveryday,
			&i.Position,
			&i.SessionNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrainingTitle,
			&i.TrainingType,
			&i.IsLocked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoachProgramWeeks = `-- name: GetCoachProgramWeeks :many
SELECT id, program_id, week_number, notes, created_at, updated_at FROM coach_program_weeks
WHERE program_id = $1
ORDER BY week_number
`

func (q *Queries) GetCoachProgramWeeks(ctx context.Context, programID pgtype.UUID) ([]CoachProgramWeek, error) {
	rows, err := q.db.Query(ctx, getCoachProgramWeeks, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoachProgramWeek
	for rows.Next() {
		var i CoachProgramWeek
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.WeekNumber,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCoachProgramWeekSessions = `-- name: LockCoachProgramWeekSessions :many
SELECT id FROM coach_program_week_sessions
WHERE week_id = $1
FOR UPDATE
`

// Takes the row locks the freeze check reads under, so a session played between
// the check and the delete cannot slip past it. FOR UPDATE is the only mode that
// conflicts with the FOR KEY SHARE the sessions FK takes.
func (q *Queries) LockCoachProgramWeekSessions(ctx context.Context, weekID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, lockCoachProgramWeekSessions, weekID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCoachProgramWeekSession = `-- name: UpdateCoachProgramWeekSession :one
UPDATE coach_program_week_sessions
SET training_id    = $1,
    day_of_week    = $2,
    times_per_week = $3,
    is_everyday    = $4,
    position       = $5,
    notes          = $6,
    updated_at     = now()
WHERE id = $7 AND week_id = $8
RETURNING id, week_id, training_id, day_of_week, times_per_week, is_everyday, position, notes, created_at, updated_at
`

type UpdateCoachProgramWeekSessionParams struct {
	TrainingID   pgtype.UUID
	DayOfWeek    pgtype.Int4
	TimesPerWeek pgtype.Int4
	IsEveryday   bool
	Position     int32
	Notes        pgtype.Text
	ID           pgtype.UUID
	WeekID       pgtype.UUID
}

func (q *Queries) UpdateCoachProgramWeekSession(ctx context.Context, arg UpdateCoachProgramWeekSessionParams) (CoachProgramWeekSession, error) {
	row := q.db.QueryRow(ctx, updateCoachProgramWeekSession,
		arg.TrainingID,
		arg.DayOfWeek,
		arg.TimesPerWeek,
		arg.IsEveryday,
		arg.Position,
		arg.Notes,
		arg.ID,
		arg.WeekID,
	)
	var i CoachProgramWeekSession
	err := row.Scan(
		&i.ID,
		&i.WeekID,
		&i.TrainingID,
		&i.DayOfWeek,
		&i.TimesPerWeek,
		&i.IsEveryday,
		&i.Position,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCoachProgramSessionOverride = `-- name: UpsertCoachProgramSessionOverride :one
INSERT INTO coach_program_session_overrides (session_id, item_id, overrides)
VALUES ($1, $2, $3)
ON CONFLICT (session_id, item_id) DO UPDATE
  SET overrides = EXCLUDED.overrides, updated_at = now()
RETURNING id, session_id, item_id, overrides, created_at, updated_at
`

type UpsertCoachProgramSessionOverrideParams struct {
	SessionID pgtype.UUID
	ItemID    pgtype.UUID
	Overrides []byte
}

func (q *Queries) UpsertCoachProgramSessionOverride(ctx context.Context, arg UpsertCoachProgramSessionOverrideParams) (CoachProgramSessionOverride, error) {
	row := q.db.QueryRow(ctx, upsertCoachProgramSessionOverride, arg.SessionID, arg.ItemID, arg.Overrides)
	var i CoachProgramSessionOverride
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ItemID,
		&i.Overrides,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCoachProgramWeek = `-- name: UpsertCoachProgramWeek :one
INSERT INTO coach_program_weeks (program_id, week_number, notes)
VALUES ($1, $2, $3)
ON CONFLICT (program_id, week_number) DO UPDATE
  SET notes = EXCLUDED.notes, updated_at = now()
RETURNING id, program_id, week_number, notes, created_at, updated_at
`

type UpsertCoachProgramWeekParams struct {
	ProgramID  pgtype.UUID
	WeekNumber int32
	Notes      pgtype.Text
}

func (q *Queries) UpsertCoachProgramWeek(ctx context.Context, arg UpsertCoachProgramWeekParams) (CoachProgramWeek, error) {
	row := q.db.QueryRow(ctx, upsertCoachProgramWeek, arg.ProgramID, arg.WeekNumber, arg.Notes)
	var i CoachProgramWeek
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.WeekNumber,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
