// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coach_sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCoachSession = `-- name: CreateCoachSession :one
INSERT INTO coach_sessions (coach_id, title, description)
VALUES ($1, $2, $3)
RETURNING id, coach_id, title, description, created_at, updated_at
`

type CreateCoachSessionParams struct {
	CoachID     pgtype.UUID
	Title       string
	Description pgtype.Text
}

func (q *Queries) CreateCoachSession(ctx context.Context, arg CreateCoachSessionParams) (CoachSession, error) {
	row := q.db.QueryRow(ctx, createCoachSession, arg.CoachID, arg.Title, arg.Description)
	var i CoachSession
	err := row.Scan(
		&i.ID,
		&i.CoachID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCoachSessionItem = `-- name: CreateCoachSessionItem :one
INSERT INTO coach_session_items (
  session_id, parent_id, type, position,
  cycles, cycle_rest_seconds,
  reps, duration, rest_seconds,
  exercise_id,
  hb_worktime_seconds, both_hands,
  loads, left_loads, hand_positions, edge_sizes_mm,
  section_title
) VALUES (
  $1, $2, $3, $4,
  $5, $6,
  $7, $8, $9,
  $10,
  $11, $12,
  $13, $14, $15, $16,
  $17
)
RETURNING id, session_id, parent_id, type, position, cycles, cycle_rest_seconds, reps, duration, rest_seconds, exercise_id, hb_worktime_seconds, both_hands, loads, left_loads, hand_positions, edge_sizes_mm, section_title, created_at, updated_at
`

type CreateCoachSessionItemParams struct {
	SessionID         pgtype.UUID
	ParentID          pgtype.UUID
	Type              string
	Position          int32
	Cycles            pgtype.Int4
	CycleRestSeconds  pgtype.Int4
	Reps              pgtype.Int4
	Duration          pgtype.Int4
	RestSeconds       pgtype.Int4
	ExerciseID        pgtype.UUID
	HbWorktimeSeconds pgtype.Int4
	BothHands         pgtype.Bool
	Loads             []byte
	LeftLoads         []byte
	HandPositions     []byte
	EdgeSizesMm       []byte
	SectionTitle      pgtype.Text
}

func (q *Queries) CreateCoachSessionItem(ctx context.Context, arg CreateCoachSessionItemParams) (CoachSessionItem, error) {
	row := q.db.QueryRow(ctx, createCoachSessionItem,
		arg.SessionID,
		arg.ParentID,
		arg.Type,
		arg.Position,
		arg.Cycles,
		arg.CycleRestSeconds,
		arg.Reps,
		arg.Duration,
		arg.RestSeconds,
		arg.ExerciseID,
		arg.HbWorktimeSeconds,
		arg.BothHands,
		arg.Loads,
		arg.LeftLoads,
		arg.HandPositions,
		arg.EdgeSizesMm,
		arg.SectionTitle,
	)
	var i CoachSessionItem
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ParentID,
		&i.Type,
		&i.Position,
		&i.Cycles,
		&i.CycleRestSeconds,
		&i.Reps,
		&i.Duration,
		&i.RestSeconds,
		&i.ExerciseID,
		&i.HbWorktimeSeconds,
		&i.BothHands,
		&i.Loads,
		&i.LeftLoads,
		&i.HandPositions,
		&i.EdgeSizesMm,
		&i.SectionTitle,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCoachSession = `-- name: DeleteCoachSession :exec
DELETE FROM coach_sessions WHERE id = $1
`

func (q *Queries) DeleteCoachSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCoachSession, id)
	return err
}

const deleteCoachSessionItems = `-- name: DeleteCoachSessionItems :exec
DELETE FROM coach_session_items WHERE session_id = $1
`

func (q *Queries) DeleteCoachSessionItems(ctx context.Context, sessionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCoachSessionItems, sessionID)
	return err
}

const getCoachSession = `-- name: GetCoachSession :one
SELECT id, coach_id, title, description, created_at, updated_at FROM coach_sessions WHERE id = $1
`

func (q *Queries) GetCoachSession(ctx context.Context, id pgtype.UUID) (CoachSession, error) {
	row := q.db.QueryRow(ctx, getCoachSession, id)
	var i CoachSession
	err := row.Scan(
		&i.ID,
		&i.CoachID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCoachSessionItems = `-- name: GetCoachSessionItems :many
SELECT id, session_id, parent_id, type, position, cycles, cycle_rest_seconds, reps, duration, rest_seconds, exercise_id, hb_worktime_seconds, both_hands, loads, left_loads, hand_positions, edge_sizes_mm, section_title, created_at, updated_at FROM coach_session_items WHERE session_id = $1 ORDER BY position
`

func (q *Queries) GetCoachSessionItems(ctx context.Context, sessionID pgtype.UUID) ([]CoachSessionItem, error) {
	rows, err := q.db.Query(ctx, getCoachSessionItems, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoachSessionItem
	for rows.Next() {
		var i CoachSessionItem
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ParentID,
			&i.Type,
			&i.Position,
			&i.Cycles,
			&i.CycleRestSeconds,
			&i.Reps,
			&i.Duration,
			&i.RestSeconds,
			&i.ExerciseID,
			&i.HbWorktimeSeconds,
			&i.BothHands,
			&i.Loads,
			&i.LeftLoads,
			&i.HandPositions,
			&i.EdgeSizesMm,
			&i.SectionTitle,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoachSessions = `-- name: GetCoachSessions :many
SELECT id, coach_id, title, description, created_at, updated_at FROM coach_sessions WHERE coach_id = $1 ORDER BY title
`

func (q *Queries) GetCoachSessions(ctx context.Context, coachID pgtype.UUID) ([]CoachSession, error) {
	rows, err := q.db.Query(ctx, getCoachSessions, coachID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoachSession
	for rows.Next() {
		var i CoachSession
		if err := rows.Scan(
			&i.ID,
			&i.CoachID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCoachSession = `-- name: UpdateCoachSession :one
UPDATE coach_sessions
SET title = $1, description = $2, updated_at = now()
WHERE id = $3
RETURNING id, coach_id, title, description, created_at, updated_at
`

type UpdateCoachSessionParams struct {
	Title       string
	Description pgtype.Text
	ID          pgtype.UUID
}

func (q *Queries) UpdateCoachSession(ctx context.Context, arg UpdateCoachSessionParams) (CoachSession, error) {
	row := q.db.QueryRow(ctx, updateCoachSession, arg.Title, arg.Description, arg.ID)
	var i CoachSession
	err := row.Scan(
		&i.ID,
		&i.CoachID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
