// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coach_availability_reminders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAvailabilityReminderForUser = `-- name: GetAvailabilityReminderForUser :one
SELECT r.coach_id, r.enabled, r.day_of_week, r.hour, r.minute, r.created_at, r.updated_at FROM coach_availability_reminders r
JOIN coach_enrollments e ON e.coach_id = r.coach_id
WHERE e.user_id = $1
`

func (q *Queries) GetAvailabilityReminderForUser(ctx context.Context, userID pgtype.UUID) (CoachAvailabilityReminder, error) {
	row := q.db.QueryRow(ctx, getAvailabilityReminderForUser, userID)
	var i CoachAvailabilityReminder
	err := row.Scan(
		&i.CoachID,
		&i.Enabled,
		&i.DayOfWeek,
		&i.Hour,
		&i.Minute,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCoachAvailabilityReminder = `-- name: GetCoachAvailabilityReminder :one
SELECT coach_id, enabled, day_of_week, hour, minute, created_at, updated_at FROM coach_availability_reminders
WHERE coach_id = $1
`

func (q *Queries) GetCoachAvailabilityReminder(ctx context.Context, coachID pgtype.UUID) (CoachAvailabilityReminder, error) {
	row := q.db.QueryRow(ctx, getCoachAvailabilityReminder, coachID)
	var i CoachAvailabilityReminder
	err := row.Scan(
		&i.CoachID,
		&i.Enabled,
		&i.DayOfWeek,
		&i.Hour,
		&i.Minute,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCoachAvailabilityReminder = `-- name: UpsertCoachAvailabilityReminder :one
INSERT INTO coach_availability_reminders (
  coach_id, enabled, day_of_week, hour, minute
)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (coach_id) DO UPDATE
  SET enabled     = EXCLUDED.enabled,
      day_of_week = EXCLUDED.day_of_week,
      hour        = EXCLUDED.hour,
      minute      = EXCLUDED.minute,
      updated_at  = now()
RETURNING coach_id, enabled, day_of_week, hour, minute, created_at, updated_at
`

type UpsertCoachAvailabilityReminderParams struct {
	CoachID   pgtype.UUID
	Enabled   bool
	DayOfWeek int32
	Hour      int32
	Minute    int32
}

func (q *Queries) UpsertCoachAvailabilityReminder(ctx context.Context, arg UpsertCoachAvailabilityReminderParams) (CoachAvailabilityReminder, error) {
	row := q.db.QueryRow(ctx, upsertCoachAvailabilityReminder,
		arg.CoachID,
		arg.Enabled,
		arg.DayOfWeek,
		arg.Hour,
		arg.Minute,
	)
	var i CoachAvailabilityReminder
	err := row.Scan(
		&i.CoachID,
		&i.Enabled,
		&i.DayOfWeek,
		&i.Hour,
		&i.Minute,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
