// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coachee_availability.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCoacheeAvailability = `-- name: GetCoacheeAvailability :many
SELECT id, user_id, week_start, day_of_week, is_available, duration_minutes, note, created_at, updated_at FROM coachee_day_availabilities
WHERE user_id = $1
ORDER BY week_start, day_of_week
`

func (q *Queries) GetCoacheeAvailability(ctx context.Context, userID pgtype.UUID) ([]CoacheeDayAvailability, error) {
	rows, err := q.db.Query(ctx, getCoacheeAvailability, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoacheeDayAvailability
	for rows.Next() {
		var i CoacheeDayAvailability
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WeekStart,
			&i.DayOfWeek,
			&i.IsAvailable,
			&i.DurationMinutes,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoacheeWeekAvailability = `-- name: GetCoacheeWeekAvailability :many
SELECT id, user_id, week_start, day_of_week, is_available, duration_minutes, note, created_at, updated_at FROM coachee_day_availabilities
WHERE user_id = $1 AND week_start = $2
ORDER BY day_of_week
`

type GetCoacheeWeekAvailabilityParams struct {
	UserID    pgtype.UUID
	WeekStart pgtype.Date
}

func (q *Queries) GetCoacheeWeekAvailability(ctx context.Context, arg GetCoacheeWeekAvailabilityParams) ([]CoacheeDayAvailability, error) {
	rows, err := q.db.Query(ctx, getCoacheeWeekAvailability, arg.UserID, arg.WeekStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoacheeDayAvailability
	for rows.Next() {
		var i CoacheeDayAvailability
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WeekStart,
			&i.DayOfWeek,
			&i.IsAvailable,
			&i.DurationMinutes,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCoacheeDayAvailability = `-- name: UpsertCoacheeDayAvailability :one
INSERT INTO coachee_day_availabilities (
  user_id, week_start, day_of_week, is_available, duration_minutes, note
)
VALUES (
  $1, $2, $3, $4, $5, $6
)
ON CONFLICT (user_id, week_start, day_of_week) DO UPDATE
  SET is_available     = EXCLUDED.is_available,
      duration_minutes = EXCLUDED.duration_minutes,
      note             = EXCLUDED.note,
      updated_at       = now()
RETURNING id, user_id, week_start, day_of_week, is_available, duration_minutes, note, created_at, updated_at
`

type UpsertCoacheeDayAvailabilityParams struct {
	UserID          pgtype.UUID
	WeekStart       pgtype.Date
	DayOfWeek       int32
	IsAvailable     bool
	DurationMinutes pgtype.Int4
	Note            pgtype.Text
}

func (q *Queries) UpsertCoacheeDayAvailability(ctx context.Context, arg UpsertCoacheeDayAvailabilityParams) (CoacheeDayAvailability, error) {
	row := q.db.QueryRow(ctx, upsertCoacheeDayAvailability,
		arg.UserID,
		arg.WeekStart,
		arg.DayOfWeek,
		arg.IsAvailable,
		arg.DurationMinutes,
		arg.Note,
	)
	var i CoacheeDayAvailability
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WeekStart,
		&i.DayOfWeek,
		&i.IsAvailable,
		&i.DurationMinutes,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
