// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coach_todo_settings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCoachTodoSettings = `-- name: GetCoachTodoSettings :one
SELECT coach_id, empty_week_day_of_week, empty_week_hour, empty_week_minute, created_at, updated_at FROM coach_todo_settings
WHERE coach_id = $1
`

func (q *Queries) GetCoachTodoSettings(ctx context.Context, coachID pgtype.UUID) (CoachTodoSetting, error) {
	row := q.db.QueryRow(ctx, getCoachTodoSettings, coachID)
	var i CoachTodoSetting
	err := row.Scan(
		&i.CoachID,
		&i.EmptyWeekDayOfWeek,
		&i.EmptyWeekHour,
		&i.EmptyWeekMinute,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCoachTodoSettings = `-- name: UpsertCoachTodoSettings :one
INSERT INTO coach_todo_settings (
  coach_id, empty_week_day_of_week, empty_week_hour, empty_week_minute
)
VALUES ($1, $2, $3, $4)
ON CONFLICT (coach_id) DO UPDATE
  SET empty_week_day_of_week = EXCLUDED.empty_week_day_of_week,
      empty_week_hour        = EXCLUDED.empty_week_hour,
      empty_week_minute      = EXCLUDED.empty_week_minute,
      updated_at             = now()
RETURNING coach_id, empty_week_day_of_week, empty_week_hour, empty_week_minute, created_at, updated_at
`

type UpsertCoachTodoSettingsParams struct {
	CoachID            pgtype.UUID
	EmptyWeekDayOfWeek int32
	EmptyWeekHour      int32
	EmptyWeekMinute    int32
}

func (q *Queries) UpsertCoachTodoSettings(ctx context.Context, arg UpsertCoachTodoSettingsParams) (CoachTodoSetting, error) {
	row := q.db.QueryRow(ctx, upsertCoachTodoSettings,
		arg.CoachID,
		arg.EmptyWeekDayOfWeek,
		arg.EmptyWeekHour,
		arg.EmptyWeekMinute,
	)
	var i CoachTodoSetting
	err := row.Scan(
		&i.CoachID,
		&i.EmptyWeekDayOfWeek,
		&i.EmptyWeekHour,
		&i.EmptyWeekMinute,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
