// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coach_programs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMyProgramTraining = `-- name: CountMyProgramTraining :one
SELECT COUNT(*) FROM coach_program_week_sessions s
JOIN coach_program_weeks w ON w.id = s.week_id
JOIN coach_programs p ON p.id = w.program_id
WHERE p.id = $1 AND p.user_id = $2 AND s.training_id = $3
`

type CountMyProgramTrainingParams struct {
	ProgramID  pgtype.UUID
	UserID     pgtype.UUID
	TrainingID pgtype.UUID
}

func (q *Queries) CountMyProgramTraining(ctx context.Context, arg CountMyProgramTrainingParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMyProgramTraining, arg.ProgramID, arg.UserID, arg.TrainingID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCoachProgram = `-- name: CreateCoachProgram :one
INSERT INTO coach_programs (coach_id, user_id, name, objective, start_date, duration_weeks)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, coach_id, user_id, name, objective, start_date, duration_weeks, created_at, updated_at
`

type CreateCoachProgramParams struct {
	CoachID       pgtype.UUID
	UserID        pgtype.UUID
	Name          string
	Objective     pgtype.Text
	StartDate     pgtype.Date
	DurationWeeks pgtype.Int4
}

func (q *Queries) CreateCoachProgram(ctx context.Context, arg CreateCoachProgramParams) (CoachProgram, error) {
	row := q.db.QueryRow(ctx, createCoachProgram,
		arg.CoachID,
		arg.UserID,
		arg.Name,
		arg.Objective,
		arg.StartDate,
		arg.DurationWeeks,
	)
	var i CoachProgram
	err := row.Scan(
		&i.ID,
		&i.CoachID,
		&i.UserID,
		&i.Name,
		&i.Objective,
		&i.StartDate,
		&i.DurationWeeks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCoachProgram = `-- name: DeleteCoachProgram :exec
DELETE FROM coach_programs WHERE id = $1
`

func (q *Queries) DeleteCoachProgram(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCoachProgram, id)
	return err
}

const getCoachProgram = `-- name: GetCoachProgram :one
SELECT id, coach_id, user_id, name, objective, start_date, duration_weeks, created_at, updated_at FROM coach_programs WHERE id = $1
`

func (q *Queries) GetCoachProgram(ctx context.Context, id pgtype.UUID) (CoachProgram, error) {
	row := q.db.QueryRow(ctx, getCoachProgram, id)
	var i CoachProgram
	err := row.Scan(
		&i.ID,
		&i.CoachID,
		&i.UserID,
		&i.Name,
		&i.Objective,
		&i.StartDate,
		&i.DurationWeeks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCoachProgramsForClient = `-- name: GetCoachProgramsForClient :many
SELECT id, coach_id, user_id, name, objective, start_date, duration_weeks, created_at, updated_at FROM coach_programs
WHERE coach_id = $1 AND user_id = $2
ORDER BY start_date DESC
`

type GetCoachProgramsForClientParams struct {
	CoachID pgtype.UUID
	UserID  pgtype.UUID
}

func (q *Queries) GetCoachProgramsForClient(ctx context.Context, arg GetCoachProgramsForClientParams) ([]CoachProgram, error) {
	rows, err := q.db.Query(ctx, getCoachProgramsForClient, arg.CoachID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoachProgram
	for rows.Next() {
		var i CoachProgram
		if err := rows.Scan(
			&i.ID,
			&i.CoachID,
			&i.UserID,
			&i.Name,
			&i.Objective,
			&i.StartDate,
			&i.DurationWeeks,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMyPrograms = `-- name: GetMyPrograms :many
SELECT id, coach_id, user_id, name, objective, start_date, duration_weeks, created_at, updated_at FROM coach_programs WHERE user_id = $1 ORDER BY start_date DESC
`

func (q *Queries) GetMyPrograms(ctx context.Context, userID pgtype.UUID) ([]CoachProgram, error) {
	rows, err := q.db.Query(ctx, getMyPrograms, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoachProgram
	for rows.Next() {
		var i CoachProgram
		if err := rows.Scan(
			&i.ID,
			&i.CoachID,
			&i.UserID,
			&i.Name,
			&i.Objective,
			&i.StartDate,
			&i.DurationWeeks,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCoachProgram = `-- name: UpdateCoachProgram :one
UPDATE coach_programs
SET name = $1, objective = $2, start_date = $3,
    duration_weeks = $4, updated_at = now()
WHERE id = $5
RETURNING id, coach_id, user_id, name, objective, start_date, duration_weeks, created_at, updated_at
`

type UpdateCoachProgramParams struct {
	Name          string
	Objective     pgtype.Text
	StartDate     pgtype.Date
	DurationWeeks pgtype.Int4
	ID            pgtype.UUID
}

func (q *Queries) UpdateCoachProgram(ctx context.Context, arg UpdateCoachProgramParams) (CoachProgram, error) {
	row := q.db.QueryRow(ctx, updateCoachProgram,
		arg.Name,
		arg.Objective,
		arg.StartDate,
		arg.DurationWeeks,
		arg.ID,
	)
	var i CoachProgram
	err := row.Scan(
		&i.ID,
		&i.CoachID,
		&i.UserID,
		&i.Name,
		&i.Objective,
		&i.StartDate,
		&i.DurationWeeks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
