// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coach_feed.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCoachPendingSessionFeedback = `-- name: CountCoachPendingSessionFeedback :one
SELECT COUNT(*) FROM sessions s
JOIN coach_enrollments e ON e.user_id = s.user_id
WHERE e.coach_id = $1
  AND (
    s.notes <> ''
    OR EXISTS (
      SELECT 1 FROM session_item_results r
      WHERE r.session_id = s.id AND r.note IS NOT NULL
    )
  )
  AND s.coach_reply IS NULL
`

// How many sessions are waiting on an answer in all. The list above is capped,
// so without this the badge counting it would stop rising at the cap and read as
// a total it is not. Counts the same sessions the list holds, item notes
// included, or the badge and the list would disagree about what is waiting.
func (q *Queries) CountCoachPendingSessionFeedback(ctx context.Context, coachID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCoachPendingSessionFeedback, coachID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCoachSessionsInWindow = `-- name: CountCoachSessionsInWindow :one
SELECT COUNT(*) FROM sessions s
JOIN coach_enrollments e ON e.user_id = s.user_id
WHERE e.coach_id = $1
  AND s.date >= $2
  AND s.date < $3
`

type CountCoachSessionsInWindowParams struct {
	CoachID     pgtype.UUID
	WindowStart pgtype.Timestamptz
	WindowEnd   pgtype.Timestamptz
}

// How many sessions the coach's athletes did in one window. The dashboard shows
// it for the current week, whose bounds only the caller's timezone offset can
// place, which is why the window arrives as two instants rather than a week.
func (q *Queries) CountCoachSessionsInWindow(ctx context.Context, arg CountCoachSessionsInWindowParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCoachSessionsInWindow, arg.CoachID, arg.WindowStart, arg.WindowEnd)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCoachEmptyProgramWeeks = `-- name: GetCoachEmptyProgramWeeks :many
WITH target AS (
  SELECT $2::date AS week_start
)
SELECT
  p.id        AS program_id,
  p.name      AS program_name,
  p.user_id   AS user_id,
  u.firstname AS user_firstname,
  u.lastname  AS user_lastname,
  (((t.week_start - p.start_date) / 7) + 1)::integer AS week_number
FROM coach_programs p
JOIN coach_enrollments e ON e.user_id = p.user_id AND e.coach_id = p.coach_id
JOIN users u ON u.id = p.user_id
CROSS JOIN target t
WHERE p.coach_id = $1
  AND p.start_date <= t.week_start
  AND (p.duration_weeks IS NULL
       OR t.week_start < p.start_date + (p.duration_weeks * 7))
  AND NOT EXISTS (
    SELECT 1
    FROM coach_program_weeks w
    JOIN coach_program_week_sessions cs ON cs.week_id = w.id
    WHERE w.program_id = p.id
      AND w.week_number = ((t.week_start - p.start_date) / 7) + 1
  )
ORDER BY u.lastname, u.firstname, p.name
`

type GetCoachEmptyProgramWeeksParams struct {
	CoachID   pgtype.UUID
	WeekStart pgtype.Date
}

type GetCoachEmptyProgramWeeksRow struct {
	ProgramID     pgtype.UUID
	ProgramName   string
	UserID        pgtype.UUID
	UserFirstname string
	UserLastname  string
	WeekNumber    int32
}

// The coach's programs that cover the calendar week starting @week_start and
// have no session prescribed in it. Start dates are Mondays, so the program week
// that calendar week falls in is the whole weeks elapsed since the program
// started, plus one. Joined to the enrollment like every other query here: a
// program outlives the enrollment it was written under, and an unenrolled
// athlete's empty week is one the coach can no longer open, let alone fill.
func (q *Queries) GetCoachEmptyProgramWeeks(ctx context.Context, arg GetCoachEmptyProgramWeeksParams) ([]GetCoachEmptyProgramWeeksRow, error) {
	rows, err := q.db.Query(ctx, getCoachEmptyProgramWeeks, arg.CoachID, arg.WeekStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCoachEmptyProgramWeeksRow
	for rows.Next() {
		var i GetCoachEmptyProgramWeeksRow
		if err := rows.Scan(
			&i.ProgramID,
			&i.ProgramName,
			&i.UserID,
			&i.UserFirstname,
			&i.UserLastname,
			&i.WeekNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoachFeed = `-- name: GetCoachFeed :many
SELECT
  'coachee_enrolled'::text AS kind,
  e.enrolled_at            AS occurred_at,
  e.user_id                AS user_id,
  u.firstname              AS user_firstname,
  u.lastname               AS user_lastname,
  NULL::uuid               AS session_id,
  NULL::text               AS title,
  NULL::integer            AS activity,
  NULL::text               AS origin,
  NULL::text               AS note,
  NULL::date               AS week_start
FROM coach_enrollments e
JOIN users u ON u.id = e.user_id
WHERE e.coach_id = $2
  AND e.enrolled_at < COALESCE($3::timestamptz, 'infinity')

UNION ALL

SELECT
  'session_completed',
  s.date,
  s.user_id,
  u.firstname,
  u.lastname,
  s.id,
  s.name,
  s.activity,
  s.origin,
  NULLIF(s.notes, ''),
  NULL::date
FROM sessions s
JOIN coach_enrollments e ON e.user_id = s.user_id
JOIN users u ON u.id = s.user_id
WHERE e.coach_id = $2
  AND s.date < COALESCE($3::timestamptz, 'infinity')

UNION ALL

SELECT
  'availability_declared',
  d.updated_at,
  d.user_id,
  u.firstname,
  u.lastname,
  NULL::uuid,
  NULL::text,
  NULL::integer,
  NULL::text,
  NULL::text,
  d.week_start
FROM coachee_week_declarations d
JOIN coach_enrollments e ON e.user_id = d.user_id
JOIN users u ON u.id = d.user_id
WHERE e.coach_id = $2
  AND d.updated_at < COALESCE($3::timestamptz, 'infinity')

ORDER BY occurred_at DESC
LIMIT $1
`

type GetCoachFeedParams struct {
	RowLimit int32
	CoachID  pgtype.UUID
	Before   pgtype.Timestamptz
}

type GetCoachFeedRow struct {
	Kind          string
	OccurredAt    pgtype.Timestamptz
	UserID        pgtype.UUID
	UserFirstname string
	UserLastname  string
	SessionID     pgtype.UUID
	Title         pgtype.Text
	Activity      pgtype.Int4
	Origin        pgtype.Text
	Note          pgtype.Text
	WeekStart     pgtype.Date
}

// The coach feed, derived on read rather than appended to by every write path,
// so it needs no backfill and cannot silently miss an event a handler forgot to
// record. One row per thing that happened to one of the coach's coachees. The
// optional before cursor walks the list backwards: pass the occurred_at of the
// oldest row already held to get the page under it. The branch carrying a NULL
// in every optional column comes first so the union reads as nullable there.
// A declared week is one event, dated by the declaration row rather than by
// what is planned inside it: a week declared empty is still an answer the coach
// wants to see go past.
func (q *Queries) GetCoachFeed(ctx context.Context, arg GetCoachFeedParams) ([]GetCoachFeedRow, error) {
	rows, err := q.db.Query(ctx, getCoachFeed, arg.RowLimit, arg.CoachID, arg.Before)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCoachFeedRow
	for rows.Next() {
		var i GetCoachFeedRow
		if err := rows.Scan(
			&i.Kind,
			&i.OccurredAt,
			&i.UserID,
			&i.UserFirstname,
			&i.UserLastname,
			&i.SessionID,
			&i.Title,
			&i.Activity,
			&i.Origin,
			&i.Note,
			&i.WeekStart,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoachPendingSessionFeedback = `-- name: GetCoachPendingSessionFeedback :many
SELECT
  s.id         AS session_id,
  s.user_id    AS user_id,
  u.firstname  AS user_firstname,
  u.lastname   AS user_lastname,
  s.name       AS session_name,
  s.date       AS session_date,
  s.activity   AS activity,
  -- One of the lines the athlete wrote, lowest pass first, preferring the note
  -- on the session itself when there is one. A session raised by an item note
  -- alone carries an empty "notes", and the row is a preview the coach clicks
  -- through, so handing them a blank line would list the session and say
  -- nothing about why.
  --
  -- Which item's line surfaces is not the prescription order: that lives in the
  -- frozen snapshot and not in a column, and every row of one batch shares an
  -- "updated_at", so there is no better key to sort on. The key is unique
  -- within a session, so the pick is at least stable between reads.
  COALESCE(
    NULLIF(s.notes, ''),
    (
      SELECT r.note FROM session_item_results r
      WHERE r.session_id = s.id AND r.note IS NOT NULL
      ORDER BY r.occurrence, r.training_item_id
      LIMIT 1
    ),
    ''
  )::text AS notes
FROM sessions s
JOIN coach_enrollments e ON e.user_id = s.user_id
JOIN users u ON u.id = s.user_id
WHERE e.coach_id = $1
  AND (
    s.notes <> ''
    OR EXISTS (
      SELECT 1 FROM session_item_results r
      WHERE r.session_id = s.id AND r.note IS NOT NULL
    )
  )
  AND s.coach_reply IS NULL
ORDER BY s.date DESC
LIMIT $2
`

type GetCoachPendingSessionFeedbackParams struct {
	CoachID  pgtype.UUID
	RowLimit int32
}

type GetCoachPendingSessionFeedbackRow struct {
	SessionID     pgtype.UUID
	UserID        pgtype.UUID
	UserFirstname string
	UserLastname  string
	SessionName   string
	SessionDate   pgtype.Timestamptz
	Activity      int32
	Notes         string
}

// The sessions whose notes the coach has not answered. The athlete wrote
// something and is waiting, which is the first thing the TODO owes them.
//
// "Wrote something" is either of the two places they can write it: the note on
// the session, and a note against one of the items they were prescribed. The
// second is the line per exercise the whole coaching loop runs on, and an
// athlete who annotates their sets and leaves the session box empty is the
// ordinary case rather than a corner one, so a feed reading only the session
// note would quietly never mention them.
func (q *Queries) GetCoachPendingSessionFeedback(ctx context.Context, arg GetCoachPendingSessionFeedbackParams) ([]GetCoachPendingSessionFeedbackRow, error) {
	rows, err := q.db.Query(ctx, getCoachPendingSessionFeedback, arg.CoachID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCoachPendingSessionFeedbackRow
	for rows.Next() {
		var i GetCoachPendingSessionFeedbackRow
		if err := rows.Scan(
			&i.SessionID,
			&i.UserID,
			&i.UserFirstname,
			&i.UserLastname,
			&i.SessionName,
			&i.SessionDate,
			&i.Activity,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
