// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coachee_availability.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCoacheeWeekActivities = `-- name: DeleteCoacheeWeekActivities :exec
DELETE FROM coachee_day_activities
WHERE declaration_id = $1
`

func (q *Queries) DeleteCoacheeWeekActivities(ctx context.Context, declarationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCoacheeWeekActivities, declarationID)
	return err
}

const getCoacheeWeekDeclaration = `-- name: GetCoacheeWeekDeclaration :one
SELECT id, user_id, week_start, created_at, updated_at FROM coachee_week_declarations
WHERE user_id = $1 AND week_start = $2
`

type GetCoacheeWeekDeclarationParams struct {
	UserID    pgtype.UUID
	WeekStart pgtype.Date
}

func (q *Queries) GetCoacheeWeekDeclaration(ctx context.Context, arg GetCoacheeWeekDeclarationParams) (CoacheeWeekDeclaration, error) {
	row := q.db.QueryRow(ctx, getCoacheeWeekDeclaration, arg.UserID, arg.WeekStart)
	var i CoacheeWeekDeclaration
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WeekStart,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCoacheeDayActivities = `-- name: ListCoacheeDayActivities :many
SELECT a.id, a.declaration_id, a.day_of_week, a.position, a.label, a.duration_minutes, a.when_text, a.where_text, a.created_at FROM coachee_day_activities a
JOIN coachee_week_declarations d ON d.id = a.declaration_id
WHERE d.user_id = $1
  AND d.week_start >= COALESCE($2::date, '-infinity')
  AND d.week_start <= COALESCE($3::date, 'infinity')
ORDER BY d.week_start, a.day_of_week, a.position
`

type ListCoacheeDayActivitiesParams struct {
	UserID   pgtype.UUID
	FromWeek pgtype.Date
	ToWeek   pgtype.Date
}

// The activities of the weeks the window above keeps, ordered so it zips
// straight onto the declarations. The two filters must be given the same
// bounds, or a week would come back without what was planned in it.
func (q *Queries) ListCoacheeDayActivities(ctx context.Context, arg ListCoacheeDayActivitiesParams) ([]CoacheeDayActivity, error) {
	rows, err := q.db.Query(ctx, listCoacheeDayActivities, arg.UserID, arg.FromWeek, arg.ToWeek)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoacheeDayActivity
	for rows.Next() {
		var i CoacheeDayActivity
		if err := rows.Scan(
			&i.ID,
			&i.DeclarationID,
			&i.DayOfWeek,
			&i.Position,
			&i.Label,
			&i.DurationMinutes,
			&i.WhenText,
			&i.WhereText,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoacheeDeclaredWeekStarts = `-- name: ListCoacheeDeclaredWeekStarts :many
SELECT week_start FROM coachee_week_declarations
WHERE user_id = $1
ORDER BY week_start
`

// Every week the athlete ever declared, as dates alone and never windowed.
// The app plans its declaration reminders off this: a nudge is dropped for a
// week already answered, so a list missing one nudges the athlete about a week
// they have already sent. It carries no activities, so answering it in full
// costs one small row per declared week.
func (q *Queries) ListCoacheeDeclaredWeekStarts(ctx context.Context, userID pgtype.UUID) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, listCoacheeDeclaredWeekStarts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Date
	for rows.Next() {
		var week_start pgtype.Date
		if err := rows.Scan(&week_start); err != nil {
			return nil, err
		}
		items = append(items, week_start)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoacheeWeekDayActivities = `-- name: ListCoacheeWeekDayActivities :many
SELECT id, declaration_id, day_of_week, position, label, duration_minutes, when_text, where_text, created_at FROM coachee_day_activities
WHERE declaration_id = $1
ORDER BY day_of_week, position
`

func (q *Queries) ListCoacheeWeekDayActivities(ctx context.Context, declarationID pgtype.UUID) ([]CoacheeDayActivity, error) {
	rows, err := q.db.Query(ctx, listCoacheeWeekDayActivities, declarationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoacheeDayActivity
	for rows.Next() {
		var i CoacheeDayActivity
		if err := rows.Scan(
			&i.ID,
			&i.DeclarationID,
			&i.DayOfWeek,
			&i.Position,
			&i.Label,
			&i.DurationMinutes,
			&i.WhenText,
			&i.WhereText,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoacheeWeekDeclarations = `-- name: ListCoacheeWeekDeclarations :many
SELECT id, user_id, week_start, created_at, updated_at FROM (
  SELECT id, user_id, week_start, created_at, updated_at FROM coachee_week_declarations
  WHERE user_id = $1
    AND week_start >= COALESCE($2::date, '-infinity')
    AND week_start <= COALESCE($3::date, 'infinity')
  ORDER BY week_start DESC
  LIMIT $4
) recent
ORDER BY week_start
`

type ListCoacheeWeekDeclarationsParams struct {
	UserID   pgtype.UUID
	FromWeek pgtype.Date
	ToWeek   pgtype.Date
	RowLimit int32
}

// The window is optional on each end. A caller that sends neither gets every
// week the athlete declared, which is what the clients read before the window
// existed, so an older build keeps working unchanged.
//
// row_limit is what keeps "every week" finite. It cuts the far end rather than
// the near one: the inner order takes the most recent weeks, which is what
// every caller renders, and the outer one hands them back oldest first, the
// order the activities zip onto.
func (q *Queries) ListCoacheeWeekDeclarations(ctx context.Context, arg ListCoacheeWeekDeclarationsParams) ([]CoacheeWeekDeclaration, error) {
	rows, err := q.db.Query(ctx, listCoacheeWeekDeclarations,
		arg.UserID,
		arg.FromWeek,
		arg.ToWeek,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoacheeWeekDeclaration
	for rows.Next() {
		var i CoacheeWeekDeclaration
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WeekStart,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCoacheeWeekDeclaration = `-- name: UpsertCoacheeWeekDeclaration :one
INSERT INTO coachee_week_declarations (user_id, week_start)
VALUES ($1, $2)
ON CONFLICT (user_id, week_start) DO UPDATE
  SET updated_at = now()
RETURNING id, user_id, week_start, created_at, updated_at
`

type UpsertCoacheeWeekDeclarationParams struct {
	UserID    pgtype.UUID
	WeekStart pgtype.Date
}

// Declaring a week the athlete has already declared is a re-answer, not a new
// one, so the row keeps its identity and only moves its updated_at. That is
// what the coach feed dates the event by.
func (q *Queries) UpsertCoacheeWeekDeclaration(ctx context.Context, arg UpsertCoacheeWeekDeclarationParams) (CoacheeWeekDeclaration, error) {
	row := q.db.QueryRow(ctx, upsertCoacheeWeekDeclaration, arg.UserID, arg.WeekStart)
	var i CoacheeWeekDeclaration
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WeekStart,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
