// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: enrollment.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCoachEnrollment = `-- name: CreateCoachEnrollment :one
INSERT INTO coach_enrollments (coach_id, user_id)
VALUES ($1, $2)
RETURNING id, coach_id, user_id, enrolled_at
`

type CreateCoachEnrollmentParams struct {
	CoachID pgtype.UUID
	UserID  pgtype.UUID
}

func (q *Queries) CreateCoachEnrollment(ctx context.Context, arg CreateCoachEnrollmentParams) (CoachEnrollment, error) {
	row := q.db.QueryRow(ctx, createCoachEnrollment, arg.CoachID, arg.UserID)
	var i CoachEnrollment
	err := row.Scan(
		&i.ID,
		&i.CoachID,
		&i.UserID,
		&i.EnrolledAt,
	)
	return i, err
}

const createEnrollmentToken = `-- name: CreateEnrollmentToken :one
INSERT INTO enrollment_tokens (coach_id, token, expires_at)
VALUES ($1, $2, $3)
RETURNING id, coach_id, token, expires_at, used_at, used_by
`

type CreateEnrollmentTokenParams struct {
	CoachID   pgtype.UUID
	Token     string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateEnrollmentToken(ctx context.Context, arg CreateEnrollmentTokenParams) (EnrollmentToken, error) {
	row := q.db.QueryRow(ctx, createEnrollmentToken, arg.CoachID, arg.Token, arg.ExpiresAt)
	var i EnrollmentToken
	err := row.Scan(
		&i.ID,
		&i.CoachID,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.UsedBy,
	)
	return i, err
}

const deleteCoachEnrollment = `-- name: DeleteCoachEnrollment :execresult
DELETE FROM coach_enrollments WHERE coach_id = $1 AND user_id = $2
`

type DeleteCoachEnrollmentParams struct {
	CoachID pgtype.UUID
	UserID  pgtype.UUID
}

func (q *Queries) DeleteCoachEnrollment(ctx context.Context, arg DeleteCoachEnrollmentParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteCoachEnrollment, arg.CoachID, arg.UserID)
}

const deleteUserEnrollment = `-- name: DeleteUserEnrollment :execresult
DELETE FROM coach_enrollments WHERE user_id = $1
`

func (q *Queries) DeleteUserEnrollment(ctx context.Context, userID pgtype.UUID) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteUserEnrollment, userID)
}

const getCoachEnrollmentTokens = `-- name: GetCoachEnrollmentTokens :many
SELECT id, coach_id, token, expires_at, used_at, used_by FROM enrollment_tokens
WHERE coach_id = $1
ORDER BY expires_at DESC
`

func (q *Queries) GetCoachEnrollmentTokens(ctx context.Context, coachID pgtype.UUID) ([]EnrollmentToken, error) {
	rows, err := q.db.Query(ctx, getCoachEnrollmentTokens, coachID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnrollmentToken
	for rows.Next() {
		var i EnrollmentToken
		if err := rows.Scan(
			&i.ID,
			&i.CoachID,
			&i.Token,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.UsedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnrollmentByUser = `-- name: GetEnrollmentByUser :one
SELECT
    ce.id,
    ce.coach_id,
    ce.user_id,
    ce.enrolled_at,
    u.firstname AS coach_firstname,
    u.lastname  AS coach_lastname,
    u.email     AS coach_email
FROM coach_enrollments ce
JOIN users u ON u.id = ce.coach_id
WHERE ce.user_id = $1
`

type GetEnrollmentByUserRow struct {
	ID             pgtype.UUID
	CoachID        pgtype.UUID
	UserID         pgtype.UUID
	EnrolledAt     pgtype.Timestamptz
	CoachFirstname string
	CoachLastname  string
	CoachEmail     string
}

func (q *Queries) GetEnrollmentByUser(ctx context.Context, userID pgtype.UUID) (GetEnrollmentByUserRow, error) {
	row := q.db.QueryRow(ctx, getEnrollmentByUser, userID)
	var i GetEnrollmentByUserRow
	err := row.Scan(
		&i.ID,
		&i.CoachID,
		&i.UserID,
		&i.EnrolledAt,
		&i.CoachFirstname,
		&i.CoachLastname,
		&i.CoachEmail,
	)
	return i, err
}

const getEnrollmentTokenByValue = `-- name: GetEnrollmentTokenByValue :one
SELECT
    et.id,
    et.coach_id,
    et.token,
    et.expires_at,
    et.used_at,
    et.used_by,
    u.firstname AS coach_firstname,
    u.lastname  AS coach_lastname,
    u.email     AS coach_email
FROM enrollment_tokens et
JOIN users u ON u.id = et.coach_id
WHERE et.token = $1
`

type GetEnrollmentTokenByValueRow struct {
	ID             pgtype.UUID
	CoachID        pgtype.UUID
	Token          string
	ExpiresAt      pgtype.Timestamptz
	UsedAt         pgtype.Timestamptz
	UsedBy         pgtype.UUID
	CoachFirstname string
	CoachLastname  string
	CoachEmail     string
}

func (q *Queries) GetEnrollmentTokenByValue(ctx context.Context, token string) (GetEnrollmentTokenByValueRow, error) {
	row := q.db.QueryRow(ctx, getEnrollmentTokenByValue, token)
	var i GetEnrollmentTokenByValueRow
	err := row.Scan(
		&i.ID,
		&i.CoachID,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.UsedBy,
		&i.CoachFirstname,
		&i.CoachLastname,
		&i.CoachEmail,
	)
	return i, err
}

const getEnrollmentsByCoach = `-- name: GetEnrollmentsByCoach :many
SELECT
    ce.id,
    ce.coach_id,
    ce.user_id,
    ce.enrolled_at,
    u.firstname AS user_firstname,
    u.lastname  AS user_lastname,
    u.email     AS user_email
FROM coach_enrollments ce
JOIN users u ON u.id = ce.user_id
WHERE ce.coach_id = $1
ORDER BY ce.enrolled_at DESC
`

type GetEnrollmentsByCoachRow struct {
	ID            pgtype.UUID
	CoachID       pgtype.UUID
	UserID        pgtype.UUID
	EnrolledAt    pgtype.Timestamptz
	UserFirstname string
	UserLastname  string
	UserEmail     string
}

func (q *Queries) GetEnrollmentsByCoach(ctx context.Context, coachID pgtype.UUID) ([]GetEnrollmentsByCoachRow, error) {
	rows, err := q.db.Query(ctx, getEnrollmentsByCoach, coachID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEnrollmentsByCoachRow
	for rows.Next() {
		var i GetEnrollmentsByCoachRow
		if err := rows.Scan(
			&i.ID,
			&i.CoachID,
			&i.UserID,
			&i.EnrolledAt,
			&i.UserFirstname,
			&i.UserLastname,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const useEnrollmentToken = `-- name: UseEnrollmentToken :exec
UPDATE enrollment_tokens
SET used_at = NOW(), used_by = $2
WHERE token = $1
`

type UseEnrollmentTokenParams struct {
	Token  string
	UsedBy pgtype.UUID
}

func (q *Queries) UseEnrollmentToken(ctx context.Context, arg UseEnrollmentTokenParams) error {
	_, err := q.db.Exec(ctx, useEnrollmentToken, arg.Token, arg.UsedBy)
	return err
}
