// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exercises.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCoachExercises = `-- name: CountCoachExercises :one
SELECT COUNT(*) FROM exercises
WHERE coach_id = $1
  AND name ILIKE '%' || $2::text || '%'
  AND (array_length($3::uuid[], 1) IS NULL OR EXISTS (
    SELECT 1 FROM exercise_tags WHERE exercise_id = exercises.id AND tag_id = ANY($3::uuid[])
  ))
`

type CountCoachExercisesParams struct {
	CoachID    pgtype.UUID
	NameFilter string
	TagIds     []pgtype.UUID
}

func (q *Queries) CountCoachExercises(ctx context.Context, arg CountCoachExercisesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCoachExercises, arg.CoachID, arg.NameFilter, arg.TagIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countExercisesOwnedBy = `-- name: CountExercisesOwnedBy :one
SELECT COUNT(*) FROM exercises
WHERE id = ANY($1::uuid[]) AND coach_id = $2
`

type CountExercisesOwnedByParams struct {
	Ids     []pgtype.UUID
	CoachID pgtype.UUID
}

// Counts how many of @ids the owner actually holds, so a training that
// references an exercise can be refused before it stores a reference to
// somebody else's. A missing id counts the same as an unowned one: both mean
// the caller cannot name it.
func (q *Queries) CountExercisesOwnedBy(ctx context.Context, arg CountExercisesOwnedByParams) (int64, error) {
	row := q.db.QueryRow(ctx, countExercisesOwnedBy, arg.Ids, arg.CoachID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExercise = `-- name: CreateExercise :one
INSERT INTO exercises (coach_id, name, description, comment, video_link)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, coach_id, name, description, comment, video_link, is_favorite, created_at, updated_at
`

type CreateExerciseParams struct {
	CoachID     pgtype.UUID
	Name        string
	Description pgtype.Text
	Comment     pgtype.Text
	VideoLink   pgtype.Text
}

func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error) {
	row := q.db.QueryRow(ctx, createExercise,
		arg.CoachID,
		arg.Name,
		arg.Description,
		arg.Comment,
		arg.VideoLink,
	)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.CoachID,
		&i.Name,
		&i.Description,
		&i.Comment,
		&i.VideoLink,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExercise = `-- name: DeleteExercise :exec
DELETE FROM exercises WHERE id = $1
`

func (q *Queries) DeleteExercise(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteExercise, id)
	return err
}

const getCoachFavoriteExercises = `-- name: GetCoachFavoriteExercises :many
SELECT id, coach_id, name, description, comment, video_link, is_favorite, created_at, updated_at FROM exercises WHERE coach_id = $1 AND is_favorite = true ORDER BY name
`

func (q *Queries) GetCoachFavoriteExercises(ctx context.Context, coachID pgtype.UUID) ([]Exercise, error) {
	rows, err := q.db.Query(ctx, getCoachFavoriteExercises, coachID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.CoachID,
			&i.Name,
			&i.Description,
			&i.Comment,
			&i.VideoLink,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExercise = `-- name: GetExercise :one
SELECT id, coach_id, name, description, comment, video_link, is_favorite, created_at, updated_at FROM exercises WHERE id = $1
`

func (q *Queries) GetExercise(ctx context.Context, id pgtype.UUID) (Exercise, error) {
	row := q.db.QueryRow(ctx, getExercise, id)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.CoachID,
		&i.Name,
		&i.Description,
		&i.Comment,
		&i.VideoLink,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchCoachExercises = `-- name: SearchCoachExercises :many
SELECT id, coach_id, name, description, comment, video_link, is_favorite, created_at, updated_at FROM exercises
WHERE coach_id = $1
  AND name ILIKE '%' || $2::text || '%'
  AND (array_length($3::uuid[], 1) IS NULL OR EXISTS (
    SELECT 1 FROM exercise_tags WHERE exercise_id = exercises.id AND tag_id = ANY($3::uuid[])
  ))
ORDER BY name
LIMIT $5 OFFSET $4
`

type SearchCoachExercisesParams struct {
	CoachID    pgtype.UUID
	NameFilter string
	TagIds     []pgtype.UUID
	Off        int32
	Lim        int32
}

func (q *Queries) SearchCoachExercises(ctx context.Context, arg SearchCoachExercisesParams) ([]Exercise, error) {
	rows, err := q.db.Query(ctx, searchCoachExercises,
		arg.CoachID,
		arg.NameFilter,
		arg.TagIds,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.CoachID,
			&i.Name,
			&i.Description,
			&i.Comment,
			&i.VideoLink,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setExerciseFavorite = `-- name: SetExerciseFavorite :one
UPDATE exercises SET is_favorite = $1, updated_at = now()
WHERE id = $2
RETURNING id, coach_id, name, description, comment, video_link, is_favorite, created_at, updated_at
`

type SetExerciseFavoriteParams struct {
	IsFavorite bool
	ID         pgtype.UUID
}

func (q *Queries) SetExerciseFavorite(ctx context.Context, arg SetExerciseFavoriteParams) (Exercise, error) {
	row := q.db.QueryRow(ctx, setExerciseFavorite, arg.IsFavorite, arg.ID)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.CoachID,
		&i.Name,
		&i.Description,
		&i.Comment,
		&i.VideoLink,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateExercise = `-- name: UpdateExercise :one
UPDATE exercises
SET name = $1, description = $2, comment = $3, video_link = $4, updated_at = now()
WHERE id = $5
RETURNING id, coach_id, name, description, comment, video_link, is_favorite, created_at, updated_at
`

type UpdateExerciseParams struct {
	Name        string
	Description pgtype.Text
	Comment     pgtype.Text
	VideoLink   pgtype.Text
	ID          pgtype.UUID
}

func (q *Queries) UpdateExercise(ctx context.Context, arg UpdateExerciseParams) (Exercise, error) {
	row := q.db.QueryRow(ctx, updateExercise,
		arg.Name,
		arg.Description,
		arg.Comment,
		arg.VideoLink,
		arg.ID,
	)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.CoachID,
		&i.Name,
		&i.Description,
		&i.Comment,
		&i.VideoLink,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
