// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exercises.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExercise = `-- name: CreateExercise :one
INSERT INTO exercises (coach_id, name, description, comment, video_link)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, coach_id, name, description, comment, video_link, is_favorite, created_at, updated_at
`

type CreateExerciseParams struct {
	CoachID     pgtype.UUID
	Name        string
	Description pgtype.Text
	Comment     pgtype.Text
	VideoLink   pgtype.Text
}

func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error) {
	row := q.db.QueryRow(ctx, createExercise,
		arg.CoachID,
		arg.Name,
		arg.Description,
		arg.Comment,
		arg.VideoLink,
	)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.CoachID,
		&i.Name,
		&i.Description,
		&i.Comment,
		&i.VideoLink,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExercise = `-- name: DeleteExercise :exec
DELETE FROM exercises WHERE id = $1
`

func (q *Queries) DeleteExercise(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteExercise, id)
	return err
}

const getCoachExercises = `-- name: GetCoachExercises :many
SELECT id, coach_id, name, description, comment, video_link, is_favorite, created_at, updated_at FROM exercises WHERE coach_id = $1 ORDER BY name
`

func (q *Queries) GetCoachExercises(ctx context.Context, coachID pgtype.UUID) ([]Exercise, error) {
	rows, err := q.db.Query(ctx, getCoachExercises, coachID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.CoachID,
			&i.Name,
			&i.Description,
			&i.Comment,
			&i.VideoLink,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoachFavoriteExercises = `-- name: GetCoachFavoriteExercises :many
SELECT id, coach_id, name, description, comment, video_link, is_favorite, created_at, updated_at FROM exercises WHERE coach_id = $1 AND is_favorite = true ORDER BY name
`

func (q *Queries) GetCoachFavoriteExercises(ctx context.Context, coachID pgtype.UUID) ([]Exercise, error) {
	rows, err := q.db.Query(ctx, getCoachFavoriteExercises, coachID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.CoachID,
			&i.Name,
			&i.Description,
			&i.Comment,
			&i.VideoLink,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExercise = `-- name: GetExercise :one
SELECT id, coach_id, name, description, comment, video_link, is_favorite, created_at, updated_at FROM exercises WHERE id = $1
`

func (q *Queries) GetExercise(ctx context.Context, id pgtype.UUID) (Exercise, error) {
	row := q.db.QueryRow(ctx, getExercise, id)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.CoachID,
		&i.Name,
		&i.Description,
		&i.Comment,
		&i.VideoLink,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setExerciseFavorite = `-- name: SetExerciseFavorite :one
UPDATE exercises SET is_favorite = $1, updated_at = now()
WHERE id = $2
RETURNING id, coach_id, name, description, comment, video_link, is_favorite, created_at, updated_at
`

type SetExerciseFavoriteParams struct {
	IsFavorite bool
	ID         pgtype.UUID
}

func (q *Queries) SetExerciseFavorite(ctx context.Context, arg SetExerciseFavoriteParams) (Exercise, error) {
	row := q.db.QueryRow(ctx, setExerciseFavorite, arg.IsFavorite, arg.ID)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.CoachID,
		&i.Name,
		&i.Description,
		&i.Comment,
		&i.VideoLink,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateExercise = `-- name: UpdateExercise :one
UPDATE exercises
SET name = $1, description = $2, comment = $3, video_link = $4, updated_at = now()
WHERE id = $5
RETURNING id, coach_id, name, description, comment, video_link, is_favorite, created_at, updated_at
`

type UpdateExerciseParams struct {
	Name        string
	Description pgtype.Text
	Comment     pgtype.Text
	VideoLink   pgtype.Text
	ID          pgtype.UUID
}

func (q *Queries) UpdateExercise(ctx context.Context, arg UpdateExerciseParams) (Exercise, error) {
	row := q.db.QueryRow(ctx, updateExercise,
		arg.Name,
		arg.Description,
		arg.Comment,
		arg.VideoLink,
		arg.ID,
	)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.CoachID,
		&i.Name,
		&i.Description,
		&i.Comment,
		&i.VideoLink,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
