// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Assessment struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	AssessmentID pgtype.UUID
	RightValue   pgtype.Float4
	LeftValue    pgtype.Float4
	SessionID    pgtype.UUID
	GripPosition pgtype.Int4
	UpdatedAt    pgtype.Timestamptz
}

type AssessmentDefinition struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	TrainingID pgtype.UUID
	Label      string
	Prompt     pgtype.Text
	Unit       string
	PerHand    bool
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type BuiltinTrainingWeight struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	BuiltinTrainingID pgtype.UUID
	CustomWeightLeft  float32
	CustomWeightRight float32
	UpdatedAt         pgtype.Timestamptz
}

type CoachAvailabilityReminder struct {
	CoachID   pgtype.UUID
	Enabled   bool
	DayOfWeek int32
	Hour      int32
	Minute    int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type CoachEnrollment struct {
	ID         pgtype.UUID
	CoachID    pgtype.UUID
	UserID     pgtype.UUID
	EnrolledAt pgtype.Timestamptz
}

type CoachProgram struct {
	ID            pgtype.UUID
	CoachID       pgtype.UUID
	UserID        pgtype.UUID
	Name          string
	Objective     pgtype.Text
	StartDate     pgtype.Date
	DurationWeeks pgtype.Int4
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type CoachProgramSessionOverride struct {
	ID        pgtype.UUID
	SessionID pgtype.UUID
	ItemID    pgtype.UUID
	Overrides []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type CoachProgramWeek struct {
	ID         pgtype.UUID
	ProgramID  pgtype.UUID
	WeekNumber int32
	Notes      pgtype.Text
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type CoachProgramWeekSession struct {
	ID           pgtype.UUID
	WeekID       pgtype.UUID
	TrainingID   pgtype.UUID
	DayOfWeek    pgtype.Int4
	TimesPerWeek pgtype.Int4
	IsEveryday   bool
	Position     int32
	Notes        pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type CoachTodoSetting struct {
	CoachID            pgtype.UUID
	EmptyWeekDayOfWeek int32
	EmptyWeekHour      int32
	EmptyWeekMinute    int32
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type CoacheeDayAvailability struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	WeekStart       pgtype.Date
	DayOfWeek       int32
	IsAvailable     bool
	DurationMinutes pgtype.Int4
	Note            pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type EnrollmentToken struct {
	ID        pgtype.UUID
	CoachID   pgtype.UUID
	Token     string
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	UsedBy    pgtype.UUID
}

type Exercise struct {
	ID          pgtype.UUID
	CoachID     pgtype.UUID
	Name        string
	Description pgtype.Text
	Comment     pgtype.Text
	VideoLink   pgtype.Text
	IsFavorite  bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ExerciseTag struct {
	ExerciseID pgtype.UUID
	TagID      pgtype.UUID
}

type PinnedBuiltinTraining struct {
	BuiltinTrainingID pgtype.UUID
	UserID            pgtype.UUID
	UpdatedAt         pgtype.Timestamptz
}

type RefreshToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	Revoked   bool
	CreatedAt pgtype.Timestamptz
}

type RepData struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	AverageWeight    float32
	SessionID        pgtype.UUID
	IsRest           bool
	Hand             string
	Duration         int32
	TargetWeight     float32
	Index            int32
	GripPosition     int32
	EdgeSizeMm       pgtype.Int4
	TrainingItemID   pgtype.UUID
	TargetUnmeasured bool
	UpdatedAt        pgtype.Timestamptz
}

type SensorConfig struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Name      string
	Index     int64
	Tare      float32
	Coef      float32
	UpdatedAt pgtype.Timestamptz
}

type Session struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	Name             string
	Notes            string
	Date             pgtype.Timestamptz
	IsAssessment     bool
	Activity         int32
	Origin           string
	TrainingID       pgtype.UUID
	ProgramSessionID pgtype.UUID
	Prescription     []byte
	Samples          []byte
	Duration         int32
	CoachReply       pgtype.Text
	CoachReplyAt     pgtype.Timestamptz
	CoachReplyReadAt pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type SessionItemResult struct {
	ID             pgtype.UUID
	SessionID      pgtype.UUID
	UserID         pgtype.UUID
	TrainingItemID pgtype.UUID
	Occurrence     int32
	Field          string
	Value          int32
	UpdatedAt      pgtype.Timestamptz
}

type Tag struct {
	ID        pgtype.UUID
	CoachID   pgtype.UUID
	Name      string
	Color     string
	IsBuiltin bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Training struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Title        string
	Description  pgtype.Text
	TrainingType string
	Goal         pgtype.Text
	Comment      pgtype.Text
	IsFavorite   bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type TrainingItem struct {
	ID               pgtype.UUID
	TrainingID       pgtype.UUID
	ParentID         pgtype.UUID
	Type             string
	Position         int32
	Cycles           pgtype.Int4
	CycleRestSeconds pgtype.Int4
	IntervalSeconds  pgtype.Int4
	Reps             pgtype.Int4
	RepsIsMax        bool
	Duration         pgtype.Int4
	RestSeconds      pgtype.Int4
	ExerciseID       pgtype.UUID
	WorktimeSeconds  pgtype.Int4
	Hand             pgtype.Text
	Granularity      pgtype.Text
	FreeText         pgtype.Text
	Comment          pgtype.Text
	Loads            []byte
	LeftLoads        []byte
	HandPositions    []byte
	EdgeSizesMm      []byte
	LoadIsMax        bool
	VariableTargets  []byte
	GroupTitle       pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type User struct {
	ID                         pgtype.UUID
	Email                      string
	Password                   string
	Firstname                  string
	Lastname                   string
	IsAdmin                    bool
	IsCoach                    bool
	CoachValidated             bool
	EmailVerified              bool
	VerificationToken          pgtype.Text
	VerificationTokenExpiresAt pgtype.Timestamptz
	VerificationEmailSentAt    pgtype.Timestamptz
	CreatedAt                  pgtype.Timestamptz
	LastSeenAt                 pgtype.Timestamptz
}
