// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Assessment struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Type         int32
	RightValue   pgtype.Float4
	LeftValue    pgtype.Float4
	SessionID    pgtype.UUID
	GripPosition pgtype.Int4
	UpdatedAt    pgtype.Timestamptz
}

type BuiltinTrainingWeight struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	BuiltinTraningID  pgtype.UUID
	CustomWeightLeft  float32
	CustomWeightRight float32
	UpdatedAt         pgtype.Timestamptz
}

type CoachEnrollment struct {
	ID         pgtype.UUID
	CoachID    pgtype.UUID
	UserID     pgtype.UUID
	EnrolledAt pgtype.Timestamptz
}

type CoachProgram struct {
	ID            pgtype.UUID
	CoachID       pgtype.UUID
	UserID        pgtype.UUID
	Name          string
	Objective     pgtype.Text
	StartDate     pgtype.Date
	DurationWeeks pgtype.Int4
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type CoachProgramSessionOverride struct {
	ID        pgtype.UUID
	SessionID pgtype.UUID
	ItemID    pgtype.UUID
	Overrides []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type CoachProgramWeek struct {
	ID         pgtype.UUID
	ProgramID  pgtype.UUID
	WeekNumber int32
	Notes      pgtype.Text
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type CoachProgramWeekSession struct {
	ID           pgtype.UUID
	WeekID       pgtype.UUID
	TrainingID   pgtype.UUID
	DayOfWeek    pgtype.Int4
	TimesPerWeek pgtype.Int4
	IsEveryday   bool
	Position     int32
	Notes        pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type EnrollmentToken struct {
	ID        pgtype.UUID
	CoachID   pgtype.UUID
	Token     string
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	UsedBy    pgtype.UUID
}

type Exercise struct {
	ID          pgtype.UUID
	CoachID     pgtype.UUID
	Name        string
	Description pgtype.Text
	Comment     pgtype.Text
	VideoLink   pgtype.Text
	IsFavorite  bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ExerciseTag struct {
	ExerciseID pgtype.UUID
	TagID      pgtype.UUID
}

type PinnedBuiltinTraining struct {
	BuiltinTrainingID pgtype.UUID
	UserID            pgtype.UUID
	UpdatedAt         pgtype.Timestamptz
}

type RefreshToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	Revoked   bool
	CreatedAt pgtype.Timestamptz
}

type RepData struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	AverageWeight float32
	SessionID     pgtype.UUID
	IsRest        bool
	RightHand     bool
	Duration      int32
	TargetWeight  float32
	Index         int32
	GripPosition  int32
	UpdatedAt     pgtype.Timestamptz
}

type SensorConfig struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Name      string
	Index     int64
	Tare      float32
	Coef      float32
	UpdatedAt pgtype.Timestamptz
}

type Session struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	Name              string
	Notes             string
	Date              pgtype.Timestamptz
	IsAssessment      bool
	SessionType       int32
	Duration          int32
	RepeaterSets      pgtype.Int4
	RepeaterReps      pgtype.Int4
	RepeaterWorkTime  pgtype.Int4
	RepeaterRestTime  pgtype.Int4
	RepeaterSetRest   pgtype.Int4
	RepeaterSplitHand pgtype.Bool
	UpdatedAt         pgtype.Timestamptz
}

type Tag struct {
	ID        pgtype.UUID
	CoachID   pgtype.UUID
	Name      string
	Color     string
	IsBuiltin bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Training struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Title        string
	Description  pgtype.Text
	TrainingType string
	Goal         pgtype.Text
	Comment      pgtype.Text
	IsFavorite   bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type TrainingItem struct {
	ID               pgtype.UUID
	TrainingID       pgtype.UUID
	ParentID         pgtype.UUID
	Type             string
	Position         int32
	Cycles           pgtype.Int4
	CycleRestSeconds pgtype.Int4
	Reps             pgtype.Int4
	Duration         pgtype.Int4
	RestSeconds      pgtype.Int4
	ExerciseID       pgtype.UUID
	WorktimeSeconds  pgtype.Int4
	Hand             pgtype.Text
	FreeText         pgtype.Text
	Comment          pgtype.Text
	Loads            []byte
	LeftLoads        []byte
	HandPositions    []byte
	EdgeSizesMm      []byte
	LoadIsMax        bool
	SectionTitle     pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type User struct {
	ID                         pgtype.UUID
	Email                      string
	Password                   string
	Firstname                  string
	Lastname                   string
	IsAdmin                    bool
	IsCoach                    bool
	CoachValidated             bool
	EmailVerified              bool
	VerificationToken          pgtype.Text
	VerificationTokenExpiresAt pgtype.Timestamptz
	VerificationEmailSentAt    pgtype.Timestamptz
	CreatedAt                  pgtype.Timestamptz
	LastSeenAt                 pgtype.Timestamptz
}
