// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pinned_builtin_trainings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserPinnedBuiltinTrainings = `-- name: GetUserPinnedBuiltinTrainings :many
SELECT builtin_training_id, user_id, updated_at FROM pinned_builtin_trainings WHERE user_id = $1 ORDER BY updated_at DESC
`

func (q *Queries) GetUserPinnedBuiltinTrainings(ctx context.Context, userID pgtype.UUID) ([]PinnedBuiltinTraining, error) {
	rows, err := q.db.Query(ctx, getUserPinnedBuiltinTrainings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PinnedBuiltinTraining
	for rows.Next() {
		var i PinnedBuiltinTraining
		if err := rows.Scan(&i.BuiltinTrainingID, &i.UserID, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pinBuiltinTraining = `-- name: PinBuiltinTraining :one
INSERT INTO pinned_builtin_trainings (builtin_training_id, user_id)
VALUES ($1, $2)
ON CONFLICT (builtin_training_id, user_id) DO UPDATE SET updated_at = now()
RETURNING builtin_training_id, user_id, updated_at
`

type PinBuiltinTrainingParams struct {
	BuiltinTrainingID pgtype.UUID
	UserID            pgtype.UUID
}

func (q *Queries) PinBuiltinTraining(ctx context.Context, arg PinBuiltinTrainingParams) (PinnedBuiltinTraining, error) {
	row := q.db.QueryRow(ctx, pinBuiltinTraining, arg.BuiltinTrainingID, arg.UserID)
	var i PinnedBuiltinTraining
	err := row.Scan(&i.BuiltinTrainingID, &i.UserID, &i.UpdatedAt)
	return i, err
}

const unpinBuiltinTraining = `-- name: UnpinBuiltinTraining :exec
DELETE FROM pinned_builtin_trainings WHERE builtin_training_id = $1 AND user_id = $2
`

type UnpinBuiltinTrainingParams struct {
	BuiltinTrainingID pgtype.UUID
	UserID            pgtype.UUID
}

func (q *Queries) UnpinBuiltinTraining(ctx context.Context, arg UnpinBuiltinTrainingParams) error {
	_, err := q.db.Exec(ctx, unpinBuiltinTraining, arg.BuiltinTrainingID, arg.UserID)
	return err
}
