// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rep_datas.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRepData = `-- name: CreateRepData :one
INSERT INTO rep_datas (
  user_id, average_weight, session_id, is_rest, right_hand, duration, target_weight, index, grip_position, edge_size_mm, training_item_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, user_id, average_weight, session_id, is_rest, right_hand, duration, target_weight, index, grip_position, edge_size_mm, training_item_id, updated_at
`

type CreateRepDataParams struct {
	UserID         pgtype.UUID
	AverageWeight  float32
	SessionID      pgtype.UUID
	IsRest         bool
	RightHand      bool
	Duration       int32
	TargetWeight   float32
	Index          int32
	GripPosition   int32
	EdgeSizeMm     pgtype.Int4
	TrainingItemID pgtype.UUID
}

func (q *Queries) CreateRepData(ctx context.Context, arg CreateRepDataParams) (RepData, error) {
	row := q.db.QueryRow(ctx, createRepData,
		arg.UserID,
		arg.AverageWeight,
		arg.SessionID,
		arg.IsRest,
		arg.RightHand,
		arg.Duration,
		arg.TargetWeight,
		arg.Index,
		arg.GripPosition,
		arg.EdgeSizeMm,
		arg.TrainingItemID,
	)
	var i RepData
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AverageWeight,
		&i.SessionID,
		&i.IsRest,
		&i.RightHand,
		&i.Duration,
		&i.TargetWeight,
		&i.Index,
		&i.GripPosition,
		&i.EdgeSizeMm,
		&i.TrainingItemID,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionRepDatas = `-- name: GetSessionRepDatas :many
SELECT id, user_id, average_weight, session_id, is_rest, right_hand, duration, target_weight, index, grip_position, edge_size_mm, training_item_id, updated_at FROM rep_datas WHERE session_id = $1 ORDER BY index
`

func (q *Queries) GetSessionRepDatas(ctx context.Context, sessionID pgtype.UUID) ([]RepData, error) {
	rows, err := q.db.Query(ctx, getSessionRepDatas, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepData
	for rows.Next() {
		var i RepData
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AverageWeight,
			&i.SessionID,
			&i.IsRest,
			&i.RightHand,
			&i.Duration,
			&i.TargetWeight,
			&i.Index,
			&i.GripPosition,
			&i.EdgeSizeMm,
			&i.TrainingItemID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
