// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repeaters.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRepeater = `-- name: CreateRepeater :one
INSERT INTO repeaters (
  user_id, sets, reps, worktime, resttime, set_rest,
  target_weight_right, target_weight_left, split_hand, grip_position
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, sets, reps, worktime, resttime, set_rest, target_weight_right, target_weight_left, split_hand, grip_position, updated_at, deleted_at, sync_version, server_updated_at
`

type CreateRepeaterParams struct {
	UserID            pgtype.UUID
	Sets              int32
	Reps              int32
	Worktime          int32
	Resttime          int32
	SetRest           int32
	TargetWeightRight pgtype.Float4
	TargetWeightLeft  pgtype.Float4
	SplitHand         bool
	GripPosition      int32
}

func (q *Queries) CreateRepeater(ctx context.Context, arg CreateRepeaterParams) (Repeater, error) {
	row := q.db.QueryRow(ctx, createRepeater,
		arg.UserID,
		arg.Sets,
		arg.Reps,
		arg.Worktime,
		arg.Resttime,
		arg.SetRest,
		arg.TargetWeightRight,
		arg.TargetWeightLeft,
		arg.SplitHand,
		arg.GripPosition,
	)
	var i Repeater
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Sets,
		&i.Reps,
		&i.Worktime,
		&i.Resttime,
		&i.SetRest,
		&i.TargetWeightRight,
		&i.TargetWeightLeft,
		&i.SplitHand,
		&i.GripPosition,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SyncVersion,
		&i.ServerUpdatedAt,
	)
	return i, err
}

const deleteRepeater = `-- name: DeleteRepeater :exec
DELETE FROM repeaters WHERE id = $1
`

func (q *Queries) DeleteRepeater(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRepeater, id)
	return err
}

const getRepeater = `-- name: GetRepeater :one
SELECT id, user_id, sets, reps, worktime, resttime, set_rest, target_weight_right, target_weight_left, split_hand, grip_position, updated_at, deleted_at, sync_version, server_updated_at FROM repeaters WHERE id = $1
`

func (q *Queries) GetRepeater(ctx context.Context, id pgtype.UUID) (Repeater, error) {
	row := q.db.QueryRow(ctx, getRepeater, id)
	var i Repeater
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Sets,
		&i.Reps,
		&i.Worktime,
		&i.Resttime,
		&i.SetRest,
		&i.TargetWeightRight,
		&i.TargetWeightLeft,
		&i.SplitHand,
		&i.GripPosition,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SyncVersion,
		&i.ServerUpdatedAt,
	)
	return i, err
}

const updateRepeater = `-- name: UpdateRepeater :one
UPDATE repeaters
SET sets = $2, reps = $3, worktime = $4, resttime = $5, set_rest = $6,
    target_weight_right = $7, target_weight_left = $8, split_hand = $9, grip_position = $10
WHERE id = $1
RETURNING id, user_id, sets, reps, worktime, resttime, set_rest, target_weight_right, target_weight_left, split_hand, grip_position, updated_at, deleted_at, sync_version, server_updated_at
`

type UpdateRepeaterParams struct {
	ID                pgtype.UUID
	Sets              int32
	Reps              int32
	Worktime          int32
	Resttime          int32
	SetRest           int32
	TargetWeightRight pgtype.Float4
	TargetWeightLeft  pgtype.Float4
	SplitHand         bool
	GripPosition      int32
}

func (q *Queries) UpdateRepeater(ctx context.Context, arg UpdateRepeaterParams) (Repeater, error) {
	row := q.db.QueryRow(ctx, updateRepeater,
		arg.ID,
		arg.Sets,
		arg.Reps,
		arg.Worktime,
		arg.Resttime,
		arg.SetRest,
		arg.TargetWeightRight,
		arg.TargetWeightLeft,
		arg.SplitHand,
		arg.GripPosition,
	)
	var i Repeater
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Sets,
		&i.Reps,
		&i.Worktime,
		&i.Resttime,
		&i.SetRest,
		&i.TargetWeightRight,
		&i.TargetWeightLeft,
		&i.SplitHand,
		&i.GripPosition,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SyncVersion,
		&i.ServerUpdatedAt,
	)
	return i, err
}
