// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sensor_configs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSensorConfig = `-- name: CreateSensorConfig :one
INSERT INTO sensor_configs (id, user_id, name, index, tare, coef)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, index, tare, coef, updated_at
`

type CreateSensorConfigParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
	Name   string
	Index  int64
	Tare   float32
	Coef   float32
}

func (q *Queries) CreateSensorConfig(ctx context.Context, arg CreateSensorConfigParams) (SensorConfig, error) {
	row := q.db.QueryRow(ctx, createSensorConfig,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Index,
		arg.Tare,
		arg.Coef,
	)
	var i SensorConfig
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Index,
		&i.Tare,
		&i.Coef,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSensorConfig = `-- name: DeleteSensorConfig :exec
DELETE FROM sensor_configs WHERE id = $1
`

func (q *Queries) DeleteSensorConfig(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSensorConfig, id)
	return err
}

const getSensorConfig = `-- name: GetSensorConfig :one
SELECT id, user_id, name, index, tare, coef, updated_at FROM sensor_configs WHERE id = $1
`

func (q *Queries) GetSensorConfig(ctx context.Context, id pgtype.UUID) (SensorConfig, error) {
	row := q.db.QueryRow(ctx, getSensorConfig, id)
	var i SensorConfig
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Index,
		&i.Tare,
		&i.Coef,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSensorConfigs = `-- name: GetUserSensorConfigs :many
SELECT id, user_id, name, index, tare, coef, updated_at FROM sensor_configs WHERE user_id = $1 ORDER BY index
`

func (q *Queries) GetUserSensorConfigs(ctx context.Context, userID pgtype.UUID) ([]SensorConfig, error) {
	rows, err := q.db.Query(ctx, getUserSensorConfigs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SensorConfig
	for rows.Next() {
		var i SensorConfig
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Index,
			&i.Tare,
			&i.Coef,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSensorConfig = `-- name: UpdateSensorConfig :one
UPDATE sensor_configs
SET name = $2, index = $3, tare = $4, coef = $5, updated_at = now()
WHERE id = $1
RETURNING id, user_id, name, index, tare, coef, updated_at
`

type UpdateSensorConfigParams struct {
	ID    pgtype.UUID
	Name  string
	Index int64
	Tare  float32
	Coef  float32
}

func (q *Queries) UpdateSensorConfig(ctx context.Context, arg UpdateSensorConfigParams) (SensorConfig, error) {
	row := q.db.QueryRow(ctx, updateSensorConfig,
		arg.ID,
		arg.Name,
		arg.Index,
		arg.Tare,
		arg.Coef,
	)
	var i SensorConfig
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Index,
		&i.Tare,
		&i.Coef,
		&i.UpdatedAt,
	)
	return i, err
}
