// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
  user_id, name, notes, is_assessment, session_type, duration, date,
  repeater_sets, repeater_reps, repeater_work_time, repeater_rest_time,
  repeater_set_rest, repeater_split_hand
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
) RETURNING id, user_id, name, notes, date, is_assessment, session_type, duration, repeater_sets, repeater_reps, repeater_work_time, repeater_rest_time, repeater_set_rest, repeater_split_hand, updated_at
`

type CreateSessionParams struct {
	UserID            pgtype.UUID
	Name              string
	Notes             string
	IsAssessment      bool
	SessionType       int32
	Duration          int32
	Date              pgtype.Timestamptz
	RepeaterSets      pgtype.Int4
	RepeaterReps      pgtype.Int4
	RepeaterWorkTime  pgtype.Int4
	RepeaterRestTime  pgtype.Int4
	RepeaterSetRest   pgtype.Int4
	RepeaterSplitHand pgtype.Bool
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.Name,
		arg.Notes,
		arg.IsAssessment,
		arg.SessionType,
		arg.Duration,
		arg.Date,
		arg.RepeaterSets,
		arg.RepeaterReps,
		arg.RepeaterWorkTime,
		arg.RepeaterRestTime,
		arg.RepeaterSetRest,
		arg.RepeaterSplitHand,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Notes,
		&i.Date,
		&i.IsAssessment,
		&i.SessionType,
		&i.Duration,
		&i.RepeaterSets,
		&i.RepeaterReps,
		&i.RepeaterWorkTime,
		&i.RepeaterRestTime,
		&i.RepeaterSetRest,
		&i.RepeaterSplitHand,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, name, notes, date, is_assessment, session_type, duration, repeater_sets, repeater_reps, repeater_work_time, repeater_rest_time, repeater_set_rest, repeater_split_hand, updated_at FROM sessions WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Notes,
		&i.Date,
		&i.IsAssessment,
		&i.SessionType,
		&i.Duration,
		&i.RepeaterSets,
		&i.RepeaterReps,
		&i.RepeaterWorkTime,
		&i.RepeaterRestTime,
		&i.RepeaterSetRest,
		&i.RepeaterSplitHand,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSessions = `-- name: GetUserSessions :many
SELECT id, user_id, name, notes, date, is_assessment, session_type, duration, repeater_sets, repeater_reps, repeater_work_time, repeater_rest_time, repeater_set_rest, repeater_split_hand, updated_at FROM sessions WHERE user_id = $1 ORDER BY date DESC
`

func (q *Queries) GetUserSessions(ctx context.Context, userID pgtype.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, getUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Notes,
			&i.Date,
			&i.IsAssessment,
			&i.SessionType,
			&i.Duration,
			&i.RepeaterSets,
			&i.RepeaterReps,
			&i.RepeaterWorkTime,
			&i.RepeaterRestTime,
			&i.RepeaterSetRest,
			&i.RepeaterSplitHand,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSession = `-- name: UpdateSession :one
UPDATE sessions
SET name = $2, notes = $3, duration = $4
WHERE id = $1
RETURNING id, user_id, name, notes, date, is_assessment, session_type, duration, repeater_sets, repeater_reps, repeater_work_time, repeater_rest_time, repeater_set_rest, repeater_split_hand, updated_at
`

type UpdateSessionParams struct {
	ID       pgtype.UUID
	Name     string
	Notes    string
	Duration int32
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSession,
		arg.ID,
		arg.Name,
		arg.Notes,
		arg.Duration,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Notes,
		&i.Date,
		&i.IsAssessment,
		&i.SessionType,
		&i.Duration,
		&i.RepeaterSets,
		&i.RepeaterReps,
		&i.RepeaterWorkTime,
		&i.RepeaterRestTime,
		&i.RepeaterSetRest,
		&i.RepeaterSplitHand,
		&i.UpdatedAt,
	)
	return i, err
}
