// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAccessibleProgramSession = `-- name: CountAccessibleProgramSession :one
SELECT COUNT(*) FROM coach_program_week_sessions
JOIN coach_program_weeks ON coach_program_weeks.id = coach_program_week_sessions.week_id
JOIN coach_programs ON coach_programs.id = coach_program_weeks.program_id
WHERE coach_program_week_sessions.id = $1
  AND coach_programs.user_id = $2
`

type CountAccessibleProgramSessionParams struct {
	ProgramSessionID pgtype.UUID
	UserID           pgtype.UUID
}

// A prescribed session is the caller's when it sits in a program assigned to them.
func (q *Queries) CountAccessibleProgramSession(ctx context.Context, arg CountAccessibleProgramSessionParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAccessibleProgramSession, arg.ProgramSessionID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAccessibleTraining = `-- name: CountAccessibleTraining :one
SELECT COUNT(*) FROM trainings
WHERE trainings.id = $1
  AND (
    trainings.user_id = $2
    OR EXISTS (
      SELECT 1 FROM coach_program_week_sessions
      JOIN coach_program_weeks ON coach_program_weeks.id = coach_program_week_sessions.week_id
      JOIN coach_programs ON coach_programs.id = coach_program_weeks.program_id
      WHERE coach_program_week_sessions.training_id = trainings.id
        AND coach_programs.user_id = $2
    )
  )
`

type CountAccessibleTrainingParams struct {
	TrainingID pgtype.UUID
	UserID     pgtype.UUID
}

// A training a session may claim to have been played from: the caller's own, or
// one prescribed to them by a program. Counting rather than selecting keeps an
// unknown id and a foreign one indistinguishable to the caller.
func (q *Queries) CountAccessibleTraining(ctx context.Context, arg CountAccessibleTrainingParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAccessibleTraining, arg.TrainingID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
  user_id, name, notes, is_assessment, activity, origin, training_id,
  program_session_id, prescription, samples, duration, date
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
) RETURNING id, user_id, name, notes, date, is_assessment, activity, origin, training_id, program_session_id, prescription, samples, duration, updated_at
`

type CreateSessionParams struct {
	UserID           pgtype.UUID
	Name             string
	Notes            string
	IsAssessment     bool
	Activity         int32
	Origin           string
	TrainingID       pgtype.UUID
	ProgramSessionID pgtype.UUID
	Prescription     []byte
	Samples          []byte
	Duration         int32
	Date             pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.Name,
		arg.Notes,
		arg.IsAssessment,
		arg.Activity,
		arg.Origin,
		arg.TrainingID,
		arg.ProgramSessionID,
		arg.Prescription,
		arg.Samples,
		arg.Duration,
		arg.Date,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Notes,
		&i.Date,
		&i.IsAssessment,
		&i.Activity,
		&i.Origin,
		&i.TrainingID,
		&i.ProgramSessionID,
		&i.Prescription,
		&i.Samples,
		&i.Duration,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, name, notes, date, is_assessment, activity, origin, training_id, program_session_id, prescription, samples, duration, updated_at FROM sessions WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Notes,
		&i.Date,
		&i.IsAssessment,
		&i.Activity,
		&i.Origin,
		&i.TrainingID,
		&i.ProgramSessionID,
		&i.Prescription,
		&i.Samples,
		&i.Duration,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSessions = `-- name: GetUserSessions :many
SELECT
  sessions.id,
  sessions.user_id,
  sessions.name,
  sessions.notes,
  sessions.date,
  sessions.is_assessment,
  sessions.activity,
  sessions.origin,
  sessions.training_id,
  sessions.program_session_id,
  sessions.duration,
  sessions.updated_at,
  COUNT(rep_datas.id) AS rep_count
FROM sessions
LEFT JOIN rep_datas ON rep_datas.session_id = sessions.id
WHERE sessions.user_id = $1
GROUP BY sessions.id
ORDER BY sessions.date DESC
`

type GetUserSessionsRow struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	Name             string
	Notes            string
	Date             pgtype.Timestamptz
	IsAssessment     bool
	Activity         int32
	Origin           string
	TrainingID       pgtype.UUID
	ProgramSessionID pgtype.UUID
	Duration         int32
	UpdatedAt        pgtype.Timestamptz
	RepCount         int64
}

// Carries the rep count so the history list can say how many reps a session
// holds without fetching every rep of every session. The columns are listed out
// rather than starred so the prescription snapshot stays off the list: it is a
// whole training per row, it is only read by the detail screen, and a history of
// a few hundred played sessions would otherwise ship megabytes to render a list.
func (q *Queries) GetUserSessions(ctx context.Context, userID pgtype.UUID) ([]GetUserSessionsRow, error) {
	rows, err := q.db.Query(ctx, getUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserSessionsRow
	for rows.Next() {
		var i GetUserSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Notes,
			&i.Date,
			&i.IsAssessment,
			&i.Activity,
			&i.Origin,
			&i.TrainingID,
			&i.ProgramSessionID,
			&i.Duration,
			&i.UpdatedAt,
			&i.RepCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSession = `-- name: UpdateSession :one
UPDATE sessions
SET name = $2, notes = $3, duration = $4, date = COALESCE($5, date),
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, name, notes, date, is_assessment, activity, origin, training_id, program_session_id, prescription, samples, duration, updated_at
`

type UpdateSessionParams struct {
	ID       pgtype.UUID
	Name     string
	Notes    string
	Duration int32
	Date     pgtype.Timestamptz
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSession,
		arg.ID,
		arg.Name,
		arg.Notes,
		arg.Duration,
		arg.Date,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Notes,
		&i.Date,
		&i.IsAssessment,
		&i.Activity,
		&i.Origin,
		&i.TrainingID,
		&i.ProgramSessionID,
		&i.Prescription,
		&i.Samples,
		&i.Duration,
		&i.UpdatedAt,
	)
	return i, err
}
