// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAssessmentByID = `-- name: GetAssessmentByID :one
SELECT id, type, right_value, left_value, session_id, grip_position, created_at, updated_at, deleted_at, device_id, sync_version, server_updated_at, user_id FROM assessments WHERE id = $1::uuid AND user_id = $2::uuid
`

type GetAssessmentByIDParams struct {
	Column1 pgtype.UUID
	Column2 pgtype.UUID
}

func (q *Queries) GetAssessmentByID(ctx context.Context, arg GetAssessmentByIDParams) (Assessment, error) {
	row := q.db.QueryRow(ctx, getAssessmentByID, arg.Column1, arg.Column2)
	var i Assessment
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.RightValue,
		&i.LeftValue,
		&i.SessionID,
		&i.GripPosition,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeviceID,
		&i.SyncVersion,
		&i.ServerUpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getAssessmentsSinceVersion = `-- name: GetAssessmentsSinceVersion :many
SELECT id, type, right_value, left_value, session_id, grip_position, created_at, updated_at, deleted_at, device_id, sync_version, server_updated_at, user_id FROM assessments
WHERE user_id = $1::uuid
AND sync_version > $2::bigint
ORDER BY sync_version ASC
`

type GetAssessmentsSinceVersionParams struct {
	Column1 pgtype.UUID
	Column2 int64
}

func (q *Queries) GetAssessmentsSinceVersion(ctx context.Context, arg GetAssessmentsSinceVersionParams) ([]Assessment, error) {
	rows, err := q.db.Query(ctx, getAssessmentsSinceVersion, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Assessment
	for rows.Next() {
		var i Assessment
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.RightValue,
			&i.LeftValue,
			&i.SessionID,
			&i.GripPosition,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeviceID,
			&i.SyncVersion,
			&i.ServerUpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRepDataByID = `-- name: GetRepDataByID :one
SELECT id, average_weight, session_id, is_rest, right_hand, duration, target_weight, index, grip_position, created_at, updated_at, deleted_at, device_id, sync_version, server_updated_at, user_id FROM rep_datas WHERE id = $1::uuid AND user_id = $2::uuid
`

type GetRepDataByIDParams struct {
	Column1 pgtype.UUID
	Column2 pgtype.UUID
}

func (q *Queries) GetRepDataByID(ctx context.Context, arg GetRepDataByIDParams) (RepData, error) {
	row := q.db.QueryRow(ctx, getRepDataByID, arg.Column1, arg.Column2)
	var i RepData
	err := row.Scan(
		&i.ID,
		&i.AverageWeight,
		&i.SessionID,
		&i.IsRest,
		&i.RightHand,
		&i.Duration,
		&i.TargetWeight,
		&i.Index,
		&i.GripPosition,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeviceID,
		&i.SyncVersion,
		&i.ServerUpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getRepDatasSinceVersion = `-- name: GetRepDatasSinceVersion :many
SELECT id, average_weight, session_id, is_rest, right_hand, duration, target_weight, index, grip_position, created_at, updated_at, deleted_at, device_id, sync_version, server_updated_at, user_id FROM rep_datas
WHERE user_id = $1::uuid
AND sync_version > $2::bigint
ORDER BY sync_version ASC
`

type GetRepDatasSinceVersionParams struct {
	Column1 pgtype.UUID
	Column2 int64
}

func (q *Queries) GetRepDatasSinceVersion(ctx context.Context, arg GetRepDatasSinceVersionParams) ([]RepData, error) {
	rows, err := q.db.Query(ctx, getRepDatasSinceVersion, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepData
	for rows.Next() {
		var i RepData
		if err := rows.Scan(
			&i.ID,
			&i.AverageWeight,
			&i.SessionID,
			&i.IsRest,
			&i.RightHand,
			&i.Duration,
			&i.TargetWeight,
			&i.Index,
			&i.GripPosition,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeviceID,
			&i.SyncVersion,
			&i.ServerUpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRepTemplateByID = `-- name: GetRepTemplateByID :one
SELECT id, is_rest, right_hand, duration, training_id, target_weight, index, grip_position, created_at, updated_at, deleted_at, device_id, sync_version, server_updated_at, user_id FROM rep_templates WHERE id = $1::uuid AND user_id = $2::uuid
`

type GetRepTemplateByIDParams struct {
	Column1 pgtype.UUID
	Column2 pgtype.UUID
}

func (q *Queries) GetRepTemplateByID(ctx context.Context, arg GetRepTemplateByIDParams) (RepTemplate, error) {
	row := q.db.QueryRow(ctx, getRepTemplateByID, arg.Column1, arg.Column2)
	var i RepTemplate
	err := row.Scan(
		&i.ID,
		&i.IsRest,
		&i.RightHand,
		&i.Duration,
		&i.TrainingID,
		&i.TargetWeight,
		&i.Index,
		&i.GripPosition,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeviceID,
		&i.SyncVersion,
		&i.ServerUpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getRepTemplatesSinceVersion = `-- name: GetRepTemplatesSinceVersion :many
SELECT id, is_rest, right_hand, duration, training_id, target_weight, index, grip_position, created_at, updated_at, deleted_at, device_id, sync_version, server_updated_at, user_id FROM rep_templates
WHERE user_id = $1::uuid
AND sync_version > $2::bigint
ORDER BY sync_version ASC
`

type GetRepTemplatesSinceVersionParams struct {
	Column1 pgtype.UUID
	Column2 int64
}

func (q *Queries) GetRepTemplatesSinceVersion(ctx context.Context, arg GetRepTemplatesSinceVersionParams) ([]RepTemplate, error) {
	rows, err := q.db.Query(ctx, getRepTemplatesSinceVersion, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepTemplate
	for rows.Next() {
		var i RepTemplate
		if err := rows.Scan(
			&i.ID,
			&i.IsRest,
			&i.RightHand,
			&i.Duration,
			&i.TrainingID,
			&i.TargetWeight,
			&i.Index,
			&i.GripPosition,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeviceID,
			&i.SyncVersion,
			&i.ServerUpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRepeaterByID = `-- name: GetRepeaterByID :one
SELECT id, sets, reps, worktime, resttime, set_rest, target_weight_right, target_weight_left, split_hand, grip_position, created_at, updated_at, deleted_at, device_id, sync_version, server_updated_at, user_id FROM repeaters WHERE id = $1::uuid AND user_id = $2::uuid
`

type GetRepeaterByIDParams struct {
	Column1 pgtype.UUID
	Column2 pgtype.UUID
}

func (q *Queries) GetRepeaterByID(ctx context.Context, arg GetRepeaterByIDParams) (Repeater, error) {
	row := q.db.QueryRow(ctx, getRepeaterByID, arg.Column1, arg.Column2)
	var i Repeater
	err := row.Scan(
		&i.ID,
		&i.Sets,
		&i.Reps,
		&i.Worktime,
		&i.Resttime,
		&i.SetRest,
		&i.TargetWeightRight,
		&i.TargetWeightLeft,
		&i.SplitHand,
		&i.GripPosition,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeviceID,
		&i.SyncVersion,
		&i.ServerUpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getRepeatersSinceVersion = `-- name: GetRepeatersSinceVersion :many
SELECT id, sets, reps, worktime, resttime, set_rest, target_weight_right, target_weight_left, split_hand, grip_position, created_at, updated_at, deleted_at, device_id, sync_version, server_updated_at, user_id FROM repeaters
WHERE user_id = $1::uuid
AND sync_version > $2::bigint
ORDER BY sync_version ASC
`

type GetRepeatersSinceVersionParams struct {
	Column1 pgtype.UUID
	Column2 int64
}

func (q *Queries) GetRepeatersSinceVersion(ctx context.Context, arg GetRepeatersSinceVersionParams) ([]Repeater, error) {
	rows, err := q.db.Query(ctx, getRepeatersSinceVersion, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repeater
	for rows.Next() {
		var i Repeater
		if err := rows.Scan(
			&i.ID,
			&i.Sets,
			&i.Reps,
			&i.Worktime,
			&i.Resttime,
			&i.SetRest,
			&i.TargetWeightRight,
			&i.TargetWeightLeft,
			&i.SplitHand,
			&i.GripPosition,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeviceID,
			&i.SyncVersion,
			&i.ServerUpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, name, notes, date, is_assessment, session_type, duration, repeater_sets, repeater_reps, repeater_work_time, repeater_rest_time, repeater_set_rest, repeater_split_hand, created_at, updated_at, deleted_at, device_id, sync_version, server_updated_at FROM sessions WHERE id = $1::uuid AND user_id = $2::uuid
`

type GetSessionByIDParams struct {
	Column1 pgtype.UUID
	Column2 pgtype.UUID
}

func (q *Queries) GetSessionByID(ctx context.Context, arg GetSessionByIDParams) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, arg.Column1, arg.Column2)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Notes,
		&i.Date,
		&i.IsAssessment,
		&i.SessionType,
		&i.Duration,
		&i.RepeaterSets,
		&i.RepeaterReps,
		&i.RepeaterWorkTime,
		&i.RepeaterRestTime,
		&i.RepeaterSetRest,
		&i.RepeaterSplitHand,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeviceID,
		&i.SyncVersion,
		&i.ServerUpdatedAt,
	)
	return i, err
}

const getSessionsSinceVersion = `-- name: GetSessionsSinceVersion :many
SELECT id, user_id, name, notes, date, is_assessment, session_type, duration, repeater_sets, repeater_reps, repeater_work_time, repeater_rest_time, repeater_set_rest, repeater_split_hand, created_at, updated_at, deleted_at, device_id, sync_version, server_updated_at FROM sessions
WHERE user_id = $1::uuid
AND sync_version > $2::bigint
ORDER BY sync_version ASC
`

type GetSessionsSinceVersionParams struct {
	Column1 pgtype.UUID
	Column2 int64
}

func (q *Queries) GetSessionsSinceVersion(ctx context.Context, arg GetSessionsSinceVersionParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, getSessionsSinceVersion, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Notes,
			&i.Date,
			&i.IsAssessment,
			&i.SessionType,
			&i.Duration,
			&i.RepeaterSets,
			&i.RepeaterReps,
			&i.RepeaterWorkTime,
			&i.RepeaterRestTime,
			&i.RepeaterSetRest,
			&i.RepeaterSplitHand,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeviceID,
			&i.SyncVersion,
			&i.ServerUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSyncSummary = `-- name: GetSyncSummary :one
SELECT
  $1::uuid as user_id,
  (SELECT COUNT(*) FROM sessions WHERE user_id = $1::uuid AND deleted_at IS NULL) as sessions_count,
  (SELECT COUNT(*) FROM assessments WHERE user_id = $1::uuid AND deleted_at IS NULL) as assessments_count,
  (SELECT COUNT(*) FROM trainings WHERE user_id = $1::uuid AND deleted_at IS NULL) as trainings_count,
  (SELECT COUNT(*) FROM repeaters WHERE user_id = $1::uuid AND deleted_at IS NULL) as repeaters_count,
  (SELECT COUNT(*) FROM rep_templates WHERE user_id = $1::uuid AND deleted_at IS NULL) as rep_templates_count,
  (SELECT COUNT(*) FROM rep_datas WHERE user_id = $1::uuid AND deleted_at IS NULL) as rep_datas_count,
  COALESCE((
    SELECT MAX(sync_version) FROM (
      SELECT MAX(sync_version) as sync_version FROM sessions WHERE user_id = $1::uuid
      UNION ALL
      SELECT MAX(sync_version) FROM assessments WHERE user_id = $1::uuid
      UNION ALL
      SELECT MAX(sync_version) FROM trainings WHERE user_id = $1::uuid
      UNION ALL
      SELECT MAX(sync_version) FROM repeaters WHERE user_id = $1::uuid
      UNION ALL
      SELECT MAX(sync_version) FROM rep_templates WHERE user_id = $1::uuid
      UNION ALL
      SELECT MAX(sync_version) FROM rep_datas WHERE user_id = $1::uuid
    ) as all_versions
  ), 0) as last_sync_version
`

type GetSyncSummaryRow struct {
	UserID            pgtype.UUID
	SessionsCount     int64
	AssessmentsCount  int64
	TrainingsCount    int64
	RepeatersCount    int64
	RepTemplatesCount int64
	RepDatasCount     int64
	LastSyncVersion   interface{}
}

func (q *Queries) GetSyncSummary(ctx context.Context, dollar_1 pgtype.UUID) (GetSyncSummaryRow, error) {
	row := q.db.QueryRow(ctx, getSyncSummary, dollar_1)
	var i GetSyncSummaryRow
	err := row.Scan(
		&i.UserID,
		&i.SessionsCount,
		&i.AssessmentsCount,
		&i.TrainingsCount,
		&i.RepeatersCount,
		&i.RepTemplatesCount,
		&i.RepDatasCount,
		&i.LastSyncVersion,
	)
	return i, err
}

const getTrainingByID = `-- name: GetTrainingByID :one
SELECT id, user_id, name, repeater_id, is_favorite, is_assessment, created_at, updated_at, deleted_at, device_id, sync_version, server_updated_at FROM trainings WHERE id = $1::uuid AND user_id = $2::uuid
`

type GetTrainingByIDParams struct {
	Column1 pgtype.UUID
	Column2 pgtype.UUID
}

func (q *Queries) GetTrainingByID(ctx context.Context, arg GetTrainingByIDParams) (Training, error) {
	row := q.db.QueryRow(ctx, getTrainingByID, arg.Column1, arg.Column2)
	var i Training
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.RepeaterID,
		&i.IsFavorite,
		&i.IsAssessment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeviceID,
		&i.SyncVersion,
		&i.ServerUpdatedAt,
	)
	return i, err
}

const getTrainingsSinceVersion = `-- name: GetTrainingsSinceVersion :many
SELECT id, user_id, name, repeater_id, is_favorite, is_assessment, created_at, updated_at, deleted_at, device_id, sync_version, server_updated_at FROM trainings
WHERE user_id = $1::uuid
AND sync_version > $2::bigint
ORDER BY sync_version ASC
`

type GetTrainingsSinceVersionParams struct {
	Column1 pgtype.UUID
	Column2 int64
}

func (q *Queries) GetTrainingsSinceVersion(ctx context.Context, arg GetTrainingsSinceVersionParams) ([]Training, error) {
	rows, err := q.db.Query(ctx, getTrainingsSinceVersion, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Training
	for rows.Next() {
		var i Training
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.RepeaterID,
			&i.IsFavorite,
			&i.IsAssessment,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeviceID,
			&i.SyncVersion,
			&i.ServerUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserLastSeen = `-- name: UpdateUserLastSeen :exec
UPDATE users SET last_seen_at = now() WHERE id = $1::uuid
`

func (q *Queries) UpdateUserLastSeen(ctx context.Context, dollar_1 pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateUserLastSeen, dollar_1)
	return err
}

const upsertAssessment = `-- name: UpsertAssessment :one
INSERT INTO assessments (
  id, user_id, type, right_value, left_value, session_id, grip_position,
  created_at, updated_at, deleted_at, device_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
ON CONFLICT (id) DO UPDATE SET
  type = EXCLUDED.type,
  right_value = EXCLUDED.right_value,
  left_value = EXCLUDED.left_value,
  session_id = EXCLUDED.session_id,
  grip_position = EXCLUDED.grip_position,
  updated_at = EXCLUDED.updated_at,
  deleted_at = EXCLUDED.deleted_at,
  device_id = EXCLUDED.device_id
WHERE assessments.user_id = $2::uuid AND EXCLUDED.updated_at > assessments.server_updated_at
RETURNING id, type, right_value, left_value, session_id, grip_position, created_at, updated_at, deleted_at, device_id, sync_version, server_updated_at, user_id
`

type UpsertAssessmentParams struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Type         int32
	RightValue   pgtype.Float4
	LeftValue    pgtype.Float4
	SessionID    pgtype.UUID
	GripPosition pgtype.Int4
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	DeviceID     pgtype.UUID
}

func (q *Queries) UpsertAssessment(ctx context.Context, arg UpsertAssessmentParams) (Assessment, error) {
	row := q.db.QueryRow(ctx, upsertAssessment,
		arg.ID,
		arg.UserID,
		arg.Type,
		arg.RightValue,
		arg.LeftValue,
		arg.SessionID,
		arg.GripPosition,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
		arg.DeviceID,
	)
	var i Assessment
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.RightValue,
		&i.LeftValue,
		&i.SessionID,
		&i.GripPosition,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeviceID,
		&i.SyncVersion,
		&i.ServerUpdatedAt,
		&i.UserID,
	)
	return i, err
}

const upsertRepData = `-- name: UpsertRepData :one
INSERT INTO rep_datas (
  id, user_id, session_id, average_weight, is_rest, right_hand, duration, target_weight, index, grip_position,
  created_at, updated_at, deleted_at, device_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
ON CONFLICT (id) DO UPDATE SET
  session_id = EXCLUDED.session_id,
  average_weight = EXCLUDED.average_weight,
  is_rest = EXCLUDED.is_rest,
  right_hand = EXCLUDED.right_hand,
  duration = EXCLUDED.duration,
  target_weight = EXCLUDED.target_weight,
  index = EXCLUDED.index,
  grip_position = EXCLUDED.grip_position,
  updated_at = EXCLUDED.updated_at,
  deleted_at = EXCLUDED.deleted_at,
  device_id = EXCLUDED.device_id
WHERE rep_datas.user_id = $2::uuid AND EXCLUDED.updated_at > rep_datas.server_updated_at
RETURNING id, average_weight, session_id, is_rest, right_hand, duration, target_weight, index, grip_position, created_at, updated_at, deleted_at, device_id, sync_version, server_updated_at, user_id
`

type UpsertRepDataParams struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	SessionID     pgtype.UUID
	AverageWeight float32
	IsRest        bool
	RightHand     bool
	Duration      int32
	TargetWeight  float32
	Index         int32
	GripPosition  int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
	DeviceID      pgtype.UUID
}

func (q *Queries) UpsertRepData(ctx context.Context, arg UpsertRepDataParams) (RepData, error) {
	row := q.db.QueryRow(ctx, upsertRepData,
		arg.ID,
		arg.UserID,
		arg.SessionID,
		arg.AverageWeight,
		arg.IsRest,
		arg.RightHand,
		arg.Duration,
		arg.TargetWeight,
		arg.Index,
		arg.GripPosition,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
		arg.DeviceID,
	)
	var i RepData
	err := row.Scan(
		&i.ID,
		&i.AverageWeight,
		&i.SessionID,
		&i.IsRest,
		&i.RightHand,
		&i.Duration,
		&i.TargetWeight,
		&i.Index,
		&i.GripPosition,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeviceID,
		&i.SyncVersion,
		&i.ServerUpdatedAt,
		&i.UserID,
	)
	return i, err
}

const upsertRepTemplate = `-- name: UpsertRepTemplate :one
INSERT INTO rep_templates (
  id, user_id, training_id, is_rest, right_hand, duration, target_weight, index, grip_position,
  created_at, updated_at, deleted_at, device_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
ON CONFLICT (id) DO UPDATE SET
  training_id = EXCLUDED.training_id,
  is_rest = EXCLUDED.is_rest,
  right_hand = EXCLUDED.right_hand,
  duration = EXCLUDED.duration,
  target_weight = EXCLUDED.target_weight,
  index = EXCLUDED.index,
  grip_position = EXCLUDED.grip_position,
  updated_at = EXCLUDED.updated_at,
  deleted_at = EXCLUDED.deleted_at,
  device_id = EXCLUDED.device_id
WHERE rep_templates.user_id = $2::uuid AND EXCLUDED.updated_at > rep_templates.server_updated_at
RETURNING id, is_rest, right_hand, duration, training_id, target_weight, index, grip_position, created_at, updated_at, deleted_at, device_id, sync_version, server_updated_at, user_id
`

type UpsertRepTemplateParams struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	TrainingID   pgtype.UUID
	IsRest       bool
	RightHand    bool
	Duration     int32
	TargetWeight float32
	Index        int32
	GripPosition int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	DeviceID     pgtype.UUID
}

func (q *Queries) UpsertRepTemplate(ctx context.Context, arg UpsertRepTemplateParams) (RepTemplate, error) {
	row := q.db.QueryRow(ctx, upsertRepTemplate,
		arg.ID,
		arg.UserID,
		arg.TrainingID,
		arg.IsRest,
		arg.RightHand,
		arg.Duration,
		arg.TargetWeight,
		arg.Index,
		arg.GripPosition,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
		arg.DeviceID,
	)
	var i RepTemplate
	err := row.Scan(
		&i.ID,
		&i.IsRest,
		&i.RightHand,
		&i.Duration,
		&i.TrainingID,
		&i.TargetWeight,
		&i.Index,
		&i.GripPosition,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeviceID,
		&i.SyncVersion,
		&i.ServerUpdatedAt,
		&i.UserID,
	)
	return i, err
}

const upsertRepeater = `-- name: UpsertRepeater :one
INSERT INTO repeaters (
  id, user_id, sets, reps, worktime, resttime, set_rest,
  target_weight_right, target_weight_left, split_hand, grip_position,
  created_at, updated_at, deleted_at, device_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
ON CONFLICT (id) DO UPDATE SET
  sets = EXCLUDED.sets,
  reps = EXCLUDED.reps,
  worktime = EXCLUDED.worktime,
  resttime = EXCLUDED.resttime,
  set_rest = EXCLUDED.set_rest,
  target_weight_right = EXCLUDED.target_weight_right,
  target_weight_left = EXCLUDED.target_weight_left,
  split_hand = EXCLUDED.split_hand,
  grip_position = EXCLUDED.grip_position,
  updated_at = EXCLUDED.updated_at,
  deleted_at = EXCLUDED.deleted_at,
  device_id = EXCLUDED.device_id
WHERE repeaters.user_id = $2::uuid AND EXCLUDED.updated_at > repeaters.server_updated_at
RETURNING id, sets, reps, worktime, resttime, set_rest, target_weight_right, target_weight_left, split_hand, grip_position, created_at, updated_at, deleted_at, device_id, sync_version, server_updated_at, user_id
`

type UpsertRepeaterParams struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	Sets              int32
	Reps              int32
	Worktime          int32
	Resttime          int32
	SetRest           int32
	TargetWeightRight pgtype.Float4
	TargetWeightLeft  pgtype.Float4
	SplitHand         bool
	GripPosition      int32
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
	DeviceID          pgtype.UUID
}

func (q *Queries) UpsertRepeater(ctx context.Context, arg UpsertRepeaterParams) (Repeater, error) {
	row := q.db.QueryRow(ctx, upsertRepeater,
		arg.ID,
		arg.UserID,
		arg.Sets,
		arg.Reps,
		arg.Worktime,
		arg.Resttime,
		arg.SetRest,
		arg.TargetWeightRight,
		arg.TargetWeightLeft,
		arg.SplitHand,
		arg.GripPosition,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
		arg.DeviceID,
	)
	var i Repeater
	err := row.Scan(
		&i.ID,
		&i.Sets,
		&i.Reps,
		&i.Worktime,
		&i.Resttime,
		&i.SetRest,
		&i.TargetWeightRight,
		&i.TargetWeightLeft,
		&i.SplitHand,
		&i.GripPosition,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeviceID,
		&i.SyncVersion,
		&i.ServerUpdatedAt,
		&i.UserID,
	)
	return i, err
}

const upsertSession = `-- name: UpsertSession :one
INSERT INTO sessions (
  id, user_id, name, notes, date, is_assessment, session_type, duration,
  repeater_sets, repeater_reps, repeater_work_time, repeater_rest_time,
  repeater_set_rest, repeater_split_hand, created_at, updated_at, deleted_at, device_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  notes = EXCLUDED.notes,
  date = EXCLUDED.date,
  is_assessment = EXCLUDED.is_assessment,
  session_type = EXCLUDED.session_type,
  duration = EXCLUDED.duration,
  repeater_sets = EXCLUDED.repeater_sets,
  repeater_reps = EXCLUDED.repeater_reps,
  repeater_work_time = EXCLUDED.repeater_work_time,
  repeater_rest_time = EXCLUDED.repeater_rest_time,
  repeater_set_rest = EXCLUDED.repeater_set_rest,
  repeater_split_hand = EXCLUDED.repeater_split_hand,
  updated_at = EXCLUDED.updated_at,
  deleted_at = EXCLUDED.deleted_at,
  device_id = EXCLUDED.device_id
WHERE sessions.user_id = $2::uuid AND EXCLUDED.updated_at > sessions.server_updated_at
RETURNING id, user_id, name, notes, date, is_assessment, session_type, duration, repeater_sets, repeater_reps, repeater_work_time, repeater_rest_time, repeater_set_rest, repeater_split_hand, created_at, updated_at, deleted_at, device_id, sync_version, server_updated_at
`

type UpsertSessionParams struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	Name              string
	Notes             string
	Date              pgtype.Timestamptz
	IsAssessment      bool
	SessionType       int32
	Duration          int32
	RepeaterSets      pgtype.Int4
	RepeaterReps      pgtype.Int4
	RepeaterWorkTime  pgtype.Int4
	RepeaterRestTime  pgtype.Int4
	RepeaterSetRest   pgtype.Int4
	RepeaterSplitHand pgtype.Bool
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
	DeviceID          pgtype.UUID
}

func (q *Queries) UpsertSession(ctx context.Context, arg UpsertSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, upsertSession,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Notes,
		arg.Date,
		arg.IsAssessment,
		arg.SessionType,
		arg.Duration,
		arg.RepeaterSets,
		arg.RepeaterReps,
		arg.RepeaterWorkTime,
		arg.RepeaterRestTime,
		arg.RepeaterSetRest,
		arg.RepeaterSplitHand,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
		arg.DeviceID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Notes,
		&i.Date,
		&i.IsAssessment,
		&i.SessionType,
		&i.Duration,
		&i.RepeaterSets,
		&i.RepeaterReps,
		&i.RepeaterWorkTime,
		&i.RepeaterRestTime,
		&i.RepeaterSetRest,
		&i.RepeaterSplitHand,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeviceID,
		&i.SyncVersion,
		&i.ServerUpdatedAt,
	)
	return i, err
}

const upsertTraining = `-- name: UpsertTraining :one
INSERT INTO trainings (
  id, user_id, name, repeater_id, is_favorite, is_assessment,
  created_at, updated_at, deleted_at, device_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  repeater_id = EXCLUDED.repeater_id,
  is_favorite = EXCLUDED.is_favorite,
  is_assessment = EXCLUDED.is_assessment,
  updated_at = EXCLUDED.updated_at,
  deleted_at = EXCLUDED.deleted_at,
  device_id = EXCLUDED.device_id
WHERE trainings.user_id = $2::uuid AND EXCLUDED.updated_at > trainings.server_updated_at
RETURNING id, user_id, name, repeater_id, is_favorite, is_assessment, created_at, updated_at, deleted_at, device_id, sync_version, server_updated_at
`

type UpsertTrainingParams struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Name         string
	RepeaterID   pgtype.UUID
	IsFavorite   bool
	IsAssessment bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	DeviceID     pgtype.UUID
}

func (q *Queries) UpsertTraining(ctx context.Context, arg UpsertTrainingParams) (Training, error) {
	row := q.db.QueryRow(ctx, upsertTraining,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.RepeaterID,
		arg.IsFavorite,
		arg.IsAssessment,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
		arg.DeviceID,
	)
	var i Training
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.RepeaterID,
		&i.IsFavorite,
		&i.IsAssessment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeviceID,
		&i.SyncVersion,
		&i.ServerUpdatedAt,
	)
	return i, err
}
