// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignTagToExercise = `-- name: AssignTagToExercise :exec
INSERT INTO exercise_tags (exercise_id, tag_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AssignTagToExerciseParams struct {
	ExerciseID pgtype.UUID
	TagID      pgtype.UUID
}

func (q *Queries) AssignTagToExercise(ctx context.Context, arg AssignTagToExerciseParams) error {
	_, err := q.db.Exec(ctx, assignTagToExercise, arg.ExerciseID, arg.TagID)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (coach_id, name, color)
VALUES ($1, $2, $3)
RETURNING id, coach_id, name, color, created_at, updated_at
`

type CreateTagParams struct {
	CoachID pgtype.UUID
	Name    string
	Color   string
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.CoachID, arg.Name, arg.Color)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.CoachID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTag, id)
	return err
}

const getCoachExerciseTags = `-- name: GetCoachExerciseTags :many
SELECT et.exercise_id, t.id, t.name, t.color, t.created_at, t.updated_at
FROM tags t
JOIN exercise_tags et ON et.tag_id = t.id
WHERE t.coach_id = $1
ORDER BY et.exercise_id, t.name
`

type GetCoachExerciseTagsRow struct {
	ExerciseID pgtype.UUID
	ID         pgtype.UUID
	Name       string
	Color      string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) GetCoachExerciseTags(ctx context.Context, coachID pgtype.UUID) ([]GetCoachExerciseTagsRow, error) {
	rows, err := q.db.Query(ctx, getCoachExerciseTags, coachID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCoachExerciseTagsRow
	for rows.Next() {
		var i GetCoachExerciseTagsRow
		if err := rows.Scan(
			&i.ExerciseID,
			&i.ID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoachTags = `-- name: GetCoachTags :many
SELECT id, coach_id, name, color, created_at, updated_at FROM tags WHERE coach_id = $1 ORDER BY name
`

func (q *Queries) GetCoachTags(ctx context.Context, coachID pgtype.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getCoachTags, coachID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.CoachID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExerciseTags = `-- name: GetExerciseTags :many
SELECT t.id, t.coach_id, t.name, t.color, t.created_at, t.updated_at FROM tags t
JOIN exercise_tags et ON et.tag_id = t.id
WHERE et.exercise_id = $1
ORDER BY t.name
`

func (q *Queries) GetExerciseTags(ctx context.Context, exerciseID pgtype.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getExerciseTags, exerciseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.CoachID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTag = `-- name: GetTag :one
SELECT id, coach_id, name, color, created_at, updated_at FROM tags WHERE id = $1
`

func (q *Queries) GetTag(ctx context.Context, id pgtype.UUID) (Tag, error) {
	row := q.db.QueryRow(ctx, getTag, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.CoachID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unassignTagFromExercise = `-- name: UnassignTagFromExercise :exec
DELETE FROM exercise_tags WHERE exercise_id = $1 AND tag_id = $2
`

type UnassignTagFromExerciseParams struct {
	ExerciseID pgtype.UUID
	TagID      pgtype.UUID
}

func (q *Queries) UnassignTagFromExercise(ctx context.Context, arg UnassignTagFromExerciseParams) error {
	_, err := q.db.Exec(ctx, unassignTagFromExercise, arg.ExerciseID, arg.TagID)
	return err
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags SET name = $1, color = $2, updated_at = now()
WHERE id = $3
RETURNING id, coach_id, name, color, created_at, updated_at
`

type UpdateTagParams struct {
	Name  string
	Color string
	ID    pgtype.UUID
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, updateTag, arg.Name, arg.Color, arg.ID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.CoachID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
