// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trainings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTraining = `-- name: CreateTraining :one
INSERT INTO trainings (user_id, title, description, training_type, goal, comment, is_favorite)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, title, description, training_type, goal, comment, is_favorite, created_at, updated_at
`

type CreateTrainingParams struct {
	UserID       pgtype.UUID
	Title        string
	Description  pgtype.Text
	TrainingType string
	Goal         pgtype.Text
	Comment      pgtype.Text
	IsFavorite   bool
}

func (q *Queries) CreateTraining(ctx context.Context, arg CreateTrainingParams) (Training, error) {
	row := q.db.QueryRow(ctx, createTraining,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.TrainingType,
		arg.Goal,
		arg.Comment,
		arg.IsFavorite,
	)
	var i Training
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.TrainingType,
		&i.Goal,
		&i.Comment,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTrainingItem = `-- name: CreateTrainingItem :one
INSERT INTO training_items (
  training_id, parent_id, type, position,
  cycles, cycle_rest_seconds, interval_seconds,
  reps, reps_is_max, duration, rest_seconds,
  exercise_id,
  worktime_seconds, hand, granularity,
  free_text, comment, load_is_max,
  loads, left_loads, hand_positions, edge_sizes_mm,
  variable_targets,
  group_title
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7,
  $8, $9, $10, $11,
  $12,
  $13, $14, $15,
  $16, $17, $18,
  $19, $20, $21, $22,
  $23,
  $24
)
RETURNING id, training_id, parent_id, type, position, cycles, cycle_rest_seconds, interval_seconds, reps, reps_is_max, duration, rest_seconds, exercise_id, worktime_seconds, hand, granularity, free_text, comment, loads, left_loads, hand_positions, edge_sizes_mm, load_is_max, variable_targets, group_title, created_at, updated_at
`

type CreateTrainingItemParams struct {
	TrainingID       pgtype.UUID
	ParentID         pgtype.UUID
	Type             string
	Position         int32
	Cycles           pgtype.Int4
	CycleRestSeconds pgtype.Int4
	IntervalSeconds  pgtype.Int4
	Reps             pgtype.Int4
	RepsIsMax        bool
	Duration         pgtype.Int4
	RestSeconds      pgtype.Int4
	ExerciseID       pgtype.UUID
	WorktimeSeconds  pgtype.Int4
	Hand             pgtype.Text
	Granularity      pgtype.Text
	FreeText         pgtype.Text
	Comment          pgtype.Text
	LoadIsMax        bool
	Loads            []byte
	LeftLoads        []byte
	HandPositions    []byte
	EdgeSizesMm      []byte
	VariableTargets  []byte
	GroupTitle       pgtype.Text
}

func (q *Queries) CreateTrainingItem(ctx context.Context, arg CreateTrainingItemParams) (TrainingItem, error) {
	row := q.db.QueryRow(ctx, createTrainingItem,
		arg.TrainingID,
		arg.ParentID,
		arg.Type,
		arg.Position,
		arg.Cycles,
		arg.CycleRestSeconds,
		arg.IntervalSeconds,
		arg.Reps,
		arg.RepsIsMax,
		arg.Duration,
		arg.RestSeconds,
		arg.ExerciseID,
		arg.WorktimeSeconds,
		arg.Hand,
		arg.Granularity,
		arg.FreeText,
		arg.Comment,
		arg.LoadIsMax,
		arg.Loads,
		arg.LeftLoads,
		arg.HandPositions,
		arg.EdgeSizesMm,
		arg.VariableTargets,
		arg.GroupTitle,
	)
	var i TrainingItem
	err := row.Scan(
		&i.ID,
		&i.TrainingID,
		&i.ParentID,
		&i.Type,
		&i.Position,
		&i.Cycles,
		&i.CycleRestSeconds,
		&i.IntervalSeconds,
		&i.Reps,
		&i.RepsIsMax,
		&i.Duration,
		&i.RestSeconds,
		&i.ExerciseID,
		&i.WorktimeSeconds,
		&i.Hand,
		&i.Granularity,
		&i.FreeText,
		&i.Comment,
		&i.Loads,
		&i.LeftLoads,
		&i.HandPositions,
		&i.EdgeSizesMm,
		&i.LoadIsMax,
		&i.VariableTargets,
		&i.GroupTitle,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTraining = `-- name: DeleteTraining :exec
DELETE FROM trainings WHERE id = $1
`

func (q *Queries) DeleteTraining(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTraining, id)
	return err
}

const deleteTrainingItemsNotIn = `-- name: DeleteTrainingItemsNotIn :exec
DELETE FROM training_items
WHERE training_id = $1 AND NOT (id = ANY($2::uuid[]))
`

type DeleteTrainingItemsNotInParams struct {
	TrainingID pgtype.UUID
	KeptIds    []pgtype.UUID
}

func (q *Queries) DeleteTrainingItemsNotIn(ctx context.Context, arg DeleteTrainingItemsNotInParams) error {
	_, err := q.db.Exec(ctx, deleteTrainingItemsNotIn, arg.TrainingID, arg.KeptIds)
	return err
}

const getTraining = `-- name: GetTraining :one
SELECT id, user_id, title, description, training_type, goal, comment, is_favorite, created_at, updated_at FROM trainings WHERE id = $1
`

func (q *Queries) GetTraining(ctx context.Context, id pgtype.UUID) (Training, error) {
	row := q.db.QueryRow(ctx, getTraining, id)
	var i Training
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.TrainingType,
		&i.Goal,
		&i.Comment,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTrainingItemInTraining = `-- name: GetTrainingItemInTraining :one
SELECT id, training_id, parent_id, type, position, cycles, cycle_rest_seconds, interval_seconds, reps, reps_is_max, duration, rest_seconds, exercise_id, worktime_seconds, hand, granularity, free_text, comment, loads, left_loads, hand_positions, edge_sizes_mm, load_is_max, variable_targets, group_title, created_at, updated_at FROM training_items WHERE id = $1 AND training_id = $2
`

type GetTrainingItemInTrainingParams struct {
	ID         pgtype.UUID
	TrainingID pgtype.UUID
}

func (q *Queries) GetTrainingItemInTraining(ctx context.Context, arg GetTrainingItemInTrainingParams) (TrainingItem, error) {
	row := q.db.QueryRow(ctx, getTrainingItemInTraining, arg.ID, arg.TrainingID)
	var i TrainingItem
	err := row.Scan(
		&i.ID,
		&i.TrainingID,
		&i.ParentID,
		&i.Type,
		&i.Position,
		&i.Cycles,
		&i.CycleRestSeconds,
		&i.IntervalSeconds,
		&i.Reps,
		&i.RepsIsMax,
		&i.Duration,
		&i.RestSeconds,
		&i.ExerciseID,
		&i.WorktimeSeconds,
		&i.Hand,
		&i.Granularity,
		&i.FreeText,
		&i.Comment,
		&i.Loads,
		&i.LeftLoads,
		&i.HandPositions,
		&i.EdgeSizesMm,
		&i.LoadIsMax,
		&i.VariableTargets,
		&i.GroupTitle,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTrainingItems = `-- name: GetTrainingItems :many
SELECT training_items.id, training_items.training_id, training_items.parent_id, training_items.type, training_items.position, training_items.cycles, training_items.cycle_rest_seconds, training_items.interval_seconds, training_items.reps, training_items.reps_is_max, training_items.duration, training_items.rest_seconds, training_items.exercise_id, training_items.worktime_seconds, training_items.hand, training_items.granularity, training_items.free_text, training_items.comment, training_items.loads, training_items.left_loads, training_items.hand_positions, training_items.edge_sizes_mm, training_items.load_is_max, training_items.variable_targets, training_items.group_title, training_items.created_at, training_items.updated_at,
       exercises.name AS exercise_name,
       exercises.description AS exercise_description,
       exercises.video_link AS exercise_video_link
FROM training_items
LEFT JOIN exercises ON exercises.id = training_items.exercise_id
WHERE training_items.training_id = $1
ORDER BY training_items.position
`

type GetTrainingItemsRow struct {
	ID                  pgtype.UUID
	TrainingID          pgtype.UUID
	ParentID            pgtype.UUID
	Type                string
	Position            int32
	Cycles              pgtype.Int4
	CycleRestSeconds    pgtype.Int4
	IntervalSeconds     pgtype.Int4
	Reps                pgtype.Int4
	RepsIsMax           bool
	Duration            pgtype.Int4
	RestSeconds         pgtype.Int4
	ExerciseID          pgtype.UUID
	WorktimeSeconds     pgtype.Int4
	Hand                pgtype.Text
	Granularity         pgtype.Text
	FreeText            pgtype.Text
	Comment             pgtype.Text
	Loads               []byte
	LeftLoads           []byte
	HandPositions       []byte
	EdgeSizesMm         []byte
	LoadIsMax           bool
	VariableTargets     []byte
	GroupTitle          pgtype.Text
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	ExerciseName        pgtype.Text
	ExerciseDescription pgtype.Text
	ExerciseVideoLink   pgtype.Text
}

// The exercise columns travel with the item because the athlete cannot read the
// exercise itself: every /api/coach/exercises route is coach only, so a video
// the coach attached reaches them here or nowhere.
func (q *Queries) GetTrainingItems(ctx context.Context, trainingID pgtype.UUID) ([]GetTrainingItemsRow, error) {
	rows, err := q.db.Query(ctx, getTrainingItems, trainingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTrainingItemsRow
	for rows.Next() {
		var i GetTrainingItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.TrainingID,
			&i.ParentID,
			&i.Type,
			&i.Position,
			&i.Cycles,
			&i.CycleRestSeconds,
			&i.IntervalSeconds,
			&i.Reps,
			&i.RepsIsMax,
			&i.Duration,
			&i.RestSeconds,
			&i.ExerciseID,
			&i.WorktimeSeconds,
			&i.Hand,
			&i.Granularity,
			&i.FreeText,
			&i.Comment,
			&i.Loads,
			&i.LeftLoads,
			&i.HandPositions,
			&i.EdgeSizesMm,
			&i.LoadIsMax,
			&i.VariableTargets,
			&i.GroupTitle,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExerciseName,
			&i.ExerciseDescription,
			&i.ExerciseVideoLink,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrainingOwnedBy = `-- name: GetTrainingOwnedBy :one
SELECT id FROM trainings WHERE id = $1 AND user_id = $2
`

type GetTrainingOwnedByParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetTrainingOwnedBy(ctx context.Context, arg GetTrainingOwnedByParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getTrainingOwnedBy, arg.ID, arg.UserID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getTrainings = `-- name: GetTrainings :many
SELECT t.id, t.user_id, t.title, t.description, t.training_type, t.goal, t.comment, t.is_favorite, t.created_at, t.updated_at, d.id AS assessment_id, d.label, d.prompt, d.unit, d.per_hand
FROM trainings t
LEFT JOIN assessment_definitions d ON d.training_id = t.id
WHERE t.user_id = $1
  AND ($2::bool IS NULL
       OR (d.id IS NOT NULL) = $2::bool)
ORDER BY t.title
`

type GetTrainingsParams struct {
	UserID       pgtype.UUID
	IsAssessment pgtype.Bool
}

type GetTrainingsRow struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Title        string
	Description  pgtype.Text
	TrainingType string
	Goal         pgtype.Text
	Comment      pgtype.Text
	IsFavorite   bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	AssessmentID pgtype.UUID
	Label        pgtype.Text
	Prompt       pgtype.Text
	Unit         pgtype.Text
	PerHand      pgtype.Bool
}

// @is_assessment is null for the whole library, true for the assessments alone
// and false for the trainings that are not one.
func (q *Queries) GetTrainings(ctx context.Context, arg GetTrainingsParams) ([]GetTrainingsRow, error) {
	rows, err := q.db.Query(ctx, getTrainings, arg.UserID, arg.IsAssessment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTrainingsRow
	for rows.Next() {
		var i GetTrainingsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.TrainingType,
			&i.Goal,
			&i.Comment,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssessmentID,
			&i.Label,
			&i.Prompt,
			&i.Unit,
			&i.PerHand,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTraining = `-- name: UpdateTraining :one
UPDATE trainings
SET title = $1, description = $2, training_type = $3,
    goal = $4, comment = $5, is_favorite = $6, updated_at = now()
WHERE id = $7
RETURNING id, user_id, title, description, training_type, goal, comment, is_favorite, created_at, updated_at
`

type UpdateTrainingParams struct {
	Title        string
	Description  pgtype.Text
	TrainingType string
	Goal         pgtype.Text
	Comment      pgtype.Text
	IsFavorite   bool
	ID           pgtype.UUID
}

func (q *Queries) UpdateTraining(ctx context.Context, arg UpdateTrainingParams) (Training, error) {
	row := q.db.QueryRow(ctx, updateTraining,
		arg.Title,
		arg.Description,
		arg.TrainingType,
		arg.Goal,
		arg.Comment,
		arg.IsFavorite,
		arg.ID,
	)
	var i Training
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.TrainingType,
		&i.Goal,
		&i.Comment,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTrainingItem = `-- name: UpdateTrainingItem :one
UPDATE training_items
SET parent_id = $1, type = $2, position = $3,
    cycles = $4, cycle_rest_seconds = $5,
    interval_seconds = $6,
    reps = $7, reps_is_max = $8, duration = $9,
    rest_seconds = $10,
    exercise_id = $11,
    worktime_seconds = $12, hand = $13, granularity = $14,
    free_text = $15, comment = $16, load_is_max = $17,
    loads = $18, left_loads = $19, hand_positions = $20,
    edge_sizes_mm = $21,
    variable_targets = $22,
    group_title = $23,
    updated_at = now()
WHERE id = $24 AND training_id = $25
RETURNING id, training_id, parent_id, type, position, cycles, cycle_rest_seconds, interval_seconds, reps, reps_is_max, duration, rest_seconds, exercise_id, worktime_seconds, hand, granularity, free_text, comment, loads, left_loads, hand_positions, edge_sizes_mm, load_is_max, variable_targets, group_title, created_at, updated_at
`

type UpdateTrainingItemParams struct {
	ParentID         pgtype.UUID
	Type             string
	Position         int32
	Cycles           pgtype.Int4
	CycleRestSeconds pgtype.Int4
	IntervalSeconds  pgtype.Int4
	Reps             pgtype.Int4
	RepsIsMax        bool
	Duration         pgtype.Int4
	RestSeconds      pgtype.Int4
	ExerciseID       pgtype.UUID
	WorktimeSeconds  pgtype.Int4
	Hand             pgtype.Text
	Granularity      pgtype.Text
	FreeText         pgtype.Text
	Comment          pgtype.Text
	LoadIsMax        bool
	Loads            []byte
	LeftLoads        []byte
	HandPositions    []byte
	EdgeSizesMm      []byte
	VariableTargets  []byte
	GroupTitle       pgtype.Text
	ID               pgtype.UUID
	TrainingID       pgtype.UUID
}

// Scoped to the training so an id belonging to another one, and therefore
// possibly to another coach, updates nothing and is refused by the caller.
func (q *Queries) UpdateTrainingItem(ctx context.Context, arg UpdateTrainingItemParams) (TrainingItem, error) {
	row := q.db.QueryRow(ctx, updateTrainingItem,
		arg.ParentID,
		arg.Type,
		arg.Position,
		arg.Cycles,
		arg.CycleRestSeconds,
		arg.IntervalSeconds,
		arg.Reps,
		arg.RepsIsMax,
		arg.Duration,
		arg.RestSeconds,
		arg.ExerciseID,
		arg.WorktimeSeconds,
		arg.Hand,
		arg.Granularity,
		arg.FreeText,
		arg.Comment,
		arg.LoadIsMax,
		arg.Loads,
		arg.LeftLoads,
		arg.HandPositions,
		arg.EdgeSizesMm,
		arg.VariableTargets,
		arg.GroupTitle,
		arg.ID,
		arg.TrainingID,
	)
	var i TrainingItem
	err := row.Scan(
		&i.ID,
		&i.TrainingID,
		&i.ParentID,
		&i.Type,
		&i.Position,
		&i.Cycles,
		&i.CycleRestSeconds,
		&i.IntervalSeconds,
		&i.Reps,
		&i.RepsIsMax,
		&i.Duration,
		&i.RestSeconds,
		&i.ExerciseID,
		&i.WorktimeSeconds,
		&i.Hand,
		&i.Granularity,
		&i.FreeText,
		&i.Comment,
		&i.Loads,
		&i.LeftLoads,
		&i.HandPositions,
		&i.EdgeSizesMm,
		&i.LoadIsMax,
		&i.VariableTargets,
		&i.GroupTitle,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
