// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trainings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTraining = `-- name: CreateTraining :one
INSERT INTO trainings (user_id, name, repeater_id, is_favorite, is_assessment)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, repeater_id, is_favorite, is_assessment
`

type CreateTrainingParams struct {
	UserID       pgtype.UUID
	Name         string
	RepeaterID   pgtype.Int4
	IsFavorite   bool
	IsAssessment bool
}

func (q *Queries) CreateTraining(ctx context.Context, arg CreateTrainingParams) (Training, error) {
	row := q.db.QueryRow(ctx, createTraining,
		arg.UserID,
		arg.Name,
		arg.RepeaterID,
		arg.IsFavorite,
		arg.IsAssessment,
	)
	var i Training
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.RepeaterID,
		&i.IsFavorite,
		&i.IsAssessment,
	)
	return i, err
}

const deleteTraining = `-- name: DeleteTraining :exec
DELETE FROM trainings WHERE id = $1
`

func (q *Queries) DeleteTraining(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTraining, id)
	return err
}

const getTraining = `-- name: GetTraining :one
SELECT id, user_id, name, repeater_id, is_favorite, is_assessment FROM trainings WHERE id = $1
`

func (q *Queries) GetTraining(ctx context.Context, id int32) (Training, error) {
	row := q.db.QueryRow(ctx, getTraining, id)
	var i Training
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.RepeaterID,
		&i.IsFavorite,
		&i.IsAssessment,
	)
	return i, err
}

const getUserFavoriteTrainings = `-- name: GetUserFavoriteTrainings :many
SELECT id, user_id, name, repeater_id, is_favorite, is_assessment FROM trainings WHERE user_id = $1 AND is_favorite = true ORDER BY name
`

func (q *Queries) GetUserFavoriteTrainings(ctx context.Context, userID pgtype.UUID) ([]Training, error) {
	rows, err := q.db.Query(ctx, getUserFavoriteTrainings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Training
	for rows.Next() {
		var i Training
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.RepeaterID,
			&i.IsFavorite,
			&i.IsAssessment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTrainings = `-- name: GetUserTrainings :many
SELECT id, user_id, name, repeater_id, is_favorite, is_assessment FROM trainings WHERE user_id = $1 ORDER BY name
`

func (q *Queries) GetUserTrainings(ctx context.Context, userID pgtype.UUID) ([]Training, error) {
	rows, err := q.db.Query(ctx, getUserTrainings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Training
	for rows.Next() {
		var i Training
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.RepeaterID,
			&i.IsFavorite,
			&i.IsAssessment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTraining = `-- name: UpdateTraining :one
UPDATE trainings
SET name = $2, is_favorite = $3
WHERE id = $1
RETURNING id, user_id, name, repeater_id, is_favorite, is_assessment
`

type UpdateTrainingParams struct {
	ID         int32
	Name       string
	IsFavorite bool
}

func (q *Queries) UpdateTraining(ctx context.Context, arg UpdateTrainingParams) (Training, error) {
	row := q.db.QueryRow(ctx, updateTraining, arg.ID, arg.Name, arg.IsFavorite)
	var i Training
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.RepeaterID,
		&i.IsFavorite,
		&i.IsAssessment,
	)
	return i, err
}
