// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trainings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTraining = `-- name: CreateTraining :one
INSERT INTO trainings (user_id, title, description, training_type, goal, comment, is_favorite)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, title, description, training_type, goal, comment, is_favorite, created_at, updated_at
`

type CreateTrainingParams struct {
	UserID       pgtype.UUID
	Title        string
	Description  pgtype.Text
	TrainingType string
	Goal         pgtype.Text
	Comment      pgtype.Text
	IsFavorite   bool
}

func (q *Queries) CreateTraining(ctx context.Context, arg CreateTrainingParams) (Training, error) {
	row := q.db.QueryRow(ctx, createTraining,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.TrainingType,
		arg.Goal,
		arg.Comment,
		arg.IsFavorite,
	)
	var i Training
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.TrainingType,
		&i.Goal,
		&i.Comment,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTrainingItem = `-- name: CreateTrainingItem :one
INSERT INTO training_items (
  training_id, parent_id, type, position,
  cycles, cycle_rest_seconds,
  reps, duration, rest_seconds,
  exercise_id,
  worktime_seconds, hand, granularity,
  free_text, comment, load_is_max,
  loads, left_loads, hand_positions, edge_sizes_mm,
  group_title
) VALUES (
  $1, $2, $3, $4,
  $5, $6,
  $7, $8, $9,
  $10,
  $11, $12, $13,
  $14, $15, $16,
  $17, $18, $19, $20,
  $21
)
RETURNING id, training_id, parent_id, type, position, cycles, cycle_rest_seconds, reps, duration, rest_seconds, exercise_id, worktime_seconds, hand, granularity, free_text, comment, loads, left_loads, hand_positions, edge_sizes_mm, load_is_max, group_title, created_at, updated_at
`

type CreateTrainingItemParams struct {
	TrainingID       pgtype.UUID
	ParentID         pgtype.UUID
	Type             string
	Position         int32
	Cycles           pgtype.Int4
	CycleRestSeconds pgtype.Int4
	Reps             pgtype.Int4
	Duration         pgtype.Int4
	RestSeconds      pgtype.Int4
	ExerciseID       pgtype.UUID
	WorktimeSeconds  pgtype.Int4
	Hand             pgtype.Text
	Granularity      pgtype.Text
	FreeText         pgtype.Text
	Comment          pgtype.Text
	LoadIsMax        bool
	Loads            []byte
	LeftLoads        []byte
	HandPositions    []byte
	EdgeSizesMm      []byte
	GroupTitle       pgtype.Text
}

func (q *Queries) CreateTrainingItem(ctx context.Context, arg CreateTrainingItemParams) (TrainingItem, error) {
	row := q.db.QueryRow(ctx, createTrainingItem,
		arg.TrainingID,
		arg.ParentID,
		arg.Type,
		arg.Position,
		arg.Cycles,
		arg.CycleRestSeconds,
		arg.Reps,
		arg.Duration,
		arg.RestSeconds,
		arg.ExerciseID,
		arg.WorktimeSeconds,
		arg.Hand,
		arg.Granularity,
		arg.FreeText,
		arg.Comment,
		arg.LoadIsMax,
		arg.Loads,
		arg.LeftLoads,
		arg.HandPositions,
		arg.EdgeSizesMm,
		arg.GroupTitle,
	)
	var i TrainingItem
	err := row.Scan(
		&i.ID,
		&i.TrainingID,
		&i.ParentID,
		&i.Type,
		&i.Position,
		&i.Cycles,
		&i.CycleRestSeconds,
		&i.Reps,
		&i.Duration,
		&i.RestSeconds,
		&i.ExerciseID,
		&i.WorktimeSeconds,
		&i.Hand,
		&i.Granularity,
		&i.FreeText,
		&i.Comment,
		&i.Loads,
		&i.LeftLoads,
		&i.HandPositions,
		&i.EdgeSizesMm,
		&i.LoadIsMax,
		&i.GroupTitle,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTraining = `-- name: DeleteTraining :exec
DELETE FROM trainings WHERE id = $1
`

func (q *Queries) DeleteTraining(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTraining, id)
	return err
}

const deleteTrainingItems = `-- name: DeleteTrainingItems :exec
DELETE FROM training_items WHERE training_id = $1
`

func (q *Queries) DeleteTrainingItems(ctx context.Context, trainingID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTrainingItems, trainingID)
	return err
}

const getTraining = `-- name: GetTraining :one
SELECT id, user_id, title, description, training_type, goal, comment, is_favorite, created_at, updated_at FROM trainings WHERE id = $1
`

func (q *Queries) GetTraining(ctx context.Context, id pgtype.UUID) (Training, error) {
	row := q.db.QueryRow(ctx, getTraining, id)
	var i Training
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.TrainingType,
		&i.Goal,
		&i.Comment,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTrainingItems = `-- name: GetTrainingItems :many
SELECT training_items.id, training_items.training_id, training_items.parent_id, training_items.type, training_items.position, training_items.cycles, training_items.cycle_rest_seconds, training_items.reps, training_items.duration, training_items.rest_seconds, training_items.exercise_id, training_items.worktime_seconds, training_items.hand, training_items.granularity, training_items.free_text, training_items.comment, training_items.loads, training_items.left_loads, training_items.hand_positions, training_items.edge_sizes_mm, training_items.load_is_max, training_items.group_title, training_items.created_at, training_items.updated_at, exercises.name AS exercise_name
FROM training_items
LEFT JOIN exercises ON exercises.id = training_items.exercise_id
WHERE training_items.training_id = $1
ORDER BY training_items.position
`

type GetTrainingItemsRow struct {
	ID               pgtype.UUID
	TrainingID       pgtype.UUID
	ParentID         pgtype.UUID
	Type             string
	Position         int32
	Cycles           pgtype.Int4
	CycleRestSeconds pgtype.Int4
	Reps             pgtype.Int4
	Duration         pgtype.Int4
	RestSeconds      pgtype.Int4
	ExerciseID       pgtype.UUID
	WorktimeSeconds  pgtype.Int4
	Hand             pgtype.Text
	Granularity      pgtype.Text
	FreeText         pgtype.Text
	Comment          pgtype.Text
	Loads            []byte
	LeftLoads        []byte
	HandPositions    []byte
	EdgeSizesMm      []byte
	LoadIsMax        bool
	GroupTitle       pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	ExerciseName     pgtype.Text
}

func (q *Queries) GetTrainingItems(ctx context.Context, trainingID pgtype.UUID) ([]GetTrainingItemsRow, error) {
	rows, err := q.db.Query(ctx, getTrainingItems, trainingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTrainingItemsRow
	for rows.Next() {
		var i GetTrainingItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.TrainingID,
			&i.ParentID,
			&i.Type,
			&i.Position,
			&i.Cycles,
			&i.CycleRestSeconds,
			&i.Reps,
			&i.Duration,
			&i.RestSeconds,
			&i.ExerciseID,
			&i.WorktimeSeconds,
			&i.Hand,
			&i.Granularity,
			&i.FreeText,
			&i.Comment,
			&i.Loads,
			&i.LeftLoads,
			&i.HandPositions,
			&i.EdgeSizesMm,
			&i.LoadIsMax,
			&i.GroupTitle,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExerciseName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrainings = `-- name: GetTrainings :many
SELECT id, user_id, title, description, training_type, goal, comment, is_favorite, created_at, updated_at FROM trainings WHERE user_id = $1 ORDER BY title
`

func (q *Queries) GetTrainings(ctx context.Context, userID pgtype.UUID) ([]Training, error) {
	rows, err := q.db.Query(ctx, getTrainings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Training
	for rows.Next() {
		var i Training
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.TrainingType,
			&i.Goal,
			&i.Comment,
			&i.IsFavorite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTraining = `-- name: UpdateTraining :one
UPDATE trainings
SET title = $1, description = $2, training_type = $3,
    goal = $4, comment = $5, is_favorite = $6, updated_at = now()
WHERE id = $7
RETURNING id, user_id, title, description, training_type, goal, comment, is_favorite, created_at, updated_at
`

type UpdateTrainingParams struct {
	Title        string
	Description  pgtype.Text
	TrainingType string
	Goal         pgtype.Text
	Comment      pgtype.Text
	IsFavorite   bool
	ID           pgtype.UUID
}

func (q *Queries) UpdateTraining(ctx context.Context, arg UpdateTrainingParams) (Training, error) {
	row := q.db.QueryRow(ctx, updateTraining,
		arg.Title,
		arg.Description,
		arg.TrainingType,
		arg.Goal,
		arg.Comment,
		arg.IsFavorite,
		arg.ID,
	)
	var i Training
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.TrainingType,
		&i.Goal,
		&i.Comment,
		&i.IsFavorite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
