// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_bodyweights.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserBodyweight = `-- name: CreateUserBodyweight :one
INSERT INTO user_bodyweights (user_id, weight_kg, measured_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, weight_kg, measured_at, created_at
`

type CreateUserBodyweightParams struct {
	UserID     pgtype.UUID
	WeightKg   float32
	MeasuredAt pgtype.Timestamptz
}

func (q *Queries) CreateUserBodyweight(ctx context.Context, arg CreateUserBodyweightParams) (UserBodyweight, error) {
	row := q.db.QueryRow(ctx, createUserBodyweight, arg.UserID, arg.WeightKg, arg.MeasuredAt)
	var i UserBodyweight
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WeightKg,
		&i.MeasuredAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUserBodyweight = `-- name: DeleteUserBodyweight :exec
DELETE FROM user_bodyweights
WHERE id = $1 AND user_id = $2
`

type DeleteUserBodyweightParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteUserBodyweight(ctx context.Context, arg DeleteUserBodyweightParams) error {
	_, err := q.db.Exec(ctx, deleteUserBodyweight, arg.ID, arg.UserID)
	return err
}

const getUserBodyweights = `-- name: GetUserBodyweights :many
SELECT id, user_id, weight_kg, measured_at, created_at FROM user_bodyweights
WHERE user_id = $1
ORDER BY measured_at DESC, created_at DESC
LIMIT $2
`

type GetUserBodyweightsParams struct {
	UserID   pgtype.UUID
	RowLimit int32
}

func (q *Queries) GetUserBodyweights(ctx context.Context, arg GetUserBodyweightsParams) ([]UserBodyweight, error) {
	rows, err := q.db.Query(ctx, getUserBodyweights, arg.UserID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserBodyweight
	for rows.Next() {
		var i UserBodyweight
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WeightKg,
			&i.MeasuredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserLatestBodyweight = `-- name: GetUserLatestBodyweight :one
SELECT id, user_id, weight_kg, measured_at, created_at FROM user_bodyweights
WHERE user_id = $1
ORDER BY measured_at DESC, created_at DESC
LIMIT 1
`

func (q *Queries) GetUserLatestBodyweight(ctx context.Context, userID pgtype.UUID) (UserBodyweight, error) {
	row := q.db.QueryRow(ctx, getUserLatestBodyweight, userID)
	var i UserBodyweight
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WeightKg,
		&i.MeasuredAt,
		&i.CreatedAt,
	)
	return i, err
}
