// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAdminUser = `-- name: CreateAdminUser :one
INSERT INTO users (email, firstname, lastname, password, is_admin, email_verified) VALUES ($1, $2, $3, $4, true, true) RETURNING id, email, password, firstname, lastname, is_admin, is_coach, coach_validated, email_verified, verification_token, verification_token_expires_at, verification_email_sent_at, created_at
`

type CreateAdminUserParams struct {
	Email     string
	Firstname string
	Lastname  string
	Password  string
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createAdminUser,
		arg.Email,
		arg.Firstname,
		arg.Lastname,
		arg.Password,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Firstname,
		&i.Lastname,
		&i.IsAdmin,
		&i.IsCoach,
		&i.CoachValidated,
		&i.EmailVerified,
		&i.VerificationToken,
		&i.VerificationTokenExpiresAt,
		&i.VerificationEmailSentAt,
		&i.CreatedAt,
	)
	return i, err
}

const createCoachUser = `-- name: CreateCoachUser :one
INSERT INTO users (email, firstname, lastname, password, is_coach) VALUES ($1, $2, $3, $4, true) RETURNING id, email, password, firstname, lastname, is_admin, is_coach, coach_validated, email_verified, verification_token, verification_token_expires_at, verification_email_sent_at, created_at
`

type CreateCoachUserParams struct {
	Email     string
	Firstname string
	Lastname  string
	Password  string
}

func (q *Queries) CreateCoachUser(ctx context.Context, arg CreateCoachUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createCoachUser,
		arg.Email,
		arg.Firstname,
		arg.Lastname,
		arg.Password,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Firstname,
		&i.Lastname,
		&i.IsAdmin,
		&i.IsCoach,
		&i.CoachValidated,
		&i.EmailVerified,
		&i.VerificationToken,
		&i.VerificationTokenExpiresAt,
		&i.VerificationEmailSentAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, firstname, lastname, password) VALUES ($1, $2, $3, $4) RETURNING id, email, password, firstname, lastname, is_admin, is_coach, coach_validated, email_verified, verification_token, verification_token_expires_at, verification_email_sent_at, created_at
`

type CreateUserParams struct {
	Email     string
	Firstname string
	Lastname  string
	Password  string
}

// queries/users.sql
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Firstname,
		arg.Lastname,
		arg.Password,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Firstname,
		&i.Lastname,
		&i.IsAdmin,
		&i.IsCoach,
		&i.CoachValidated,
		&i.EmailVerified,
		&i.VerificationToken,
		&i.VerificationTokenExpiresAt,
		&i.VerificationEmailSentAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getPendingCoaches = `-- name: GetPendingCoaches :many
SELECT id, email, password, firstname, lastname, is_admin, is_coach, coach_validated, email_verified, verification_token, verification_token_expires_at, verification_email_sent_at, created_at FROM users WHERE is_coach = true AND coach_validated = false AND email_verified = true ORDER BY created_at ASC
`

func (q *Queries) GetPendingCoaches(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getPendingCoaches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Password,
			&i.Firstname,
			&i.Lastname,
			&i.IsAdmin,
			&i.IsCoach,
			&i.CoachValidated,
			&i.EmailVerified,
			&i.VerificationToken,
			&i.VerificationTokenExpiresAt,
			&i.VerificationEmailSentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password, firstname, lastname, is_admin, is_coach, coach_validated, email_verified, verification_token, verification_token_expires_at, verification_email_sent_at, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Firstname,
		&i.Lastname,
		&i.IsAdmin,
		&i.IsCoach,
		&i.CoachValidated,
		&i.EmailVerified,
		&i.VerificationToken,
		&i.VerificationTokenExpiresAt,
		&i.VerificationEmailSentAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password, firstname, lastname, is_admin, is_coach, coach_validated, email_verified, verification_token, verification_token_expires_at, verification_email_sent_at, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Firstname,
		&i.Lastname,
		&i.IsAdmin,
		&i.IsCoach,
		&i.CoachValidated,
		&i.EmailVerified,
		&i.VerificationToken,
		&i.VerificationTokenExpiresAt,
		&i.VerificationEmailSentAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByVerificationToken = `-- name: GetUserByVerificationToken :one
SELECT id, email, password, firstname, lastname, is_admin, is_coach, coach_validated, email_verified, verification_token, verification_token_expires_at, verification_email_sent_at, created_at FROM users WHERE verification_token = $1 AND verification_token_expires_at > NOW()
`

func (q *Queries) GetUserByVerificationToken(ctx context.Context, verificationToken pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByVerificationToken, verificationToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Firstname,
		&i.Lastname,
		&i.IsAdmin,
		&i.IsCoach,
		&i.CoachValidated,
		&i.EmailVerified,
		&i.VerificationToken,
		&i.VerificationTokenExpiresAt,
		&i.VerificationEmailSentAt,
		&i.CreatedAt,
	)
	return i, err
}

const getVerificationEmailSentAt = `-- name: GetVerificationEmailSentAt :one
SELECT verification_email_sent_at FROM users WHERE email = $1
`

func (q *Queries) GetVerificationEmailSentAt(ctx context.Context, email string) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getVerificationEmailSentAt, email)
	var verification_email_sent_at pgtype.Timestamptz
	err := row.Scan(&verification_email_sent_at)
	return verification_email_sent_at, err
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT id, email, password, firstname, lastname, is_admin, is_coach, coach_validated, email_verified, verification_token, verification_token_expires_at, verification_email_sent_at, created_at FROM users ORDER BY created_at DESC
`

func (q *Queries) ListAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Password,
			&i.Firstname,
			&i.Lastname,
			&i.IsAdmin,
			&i.IsCoach,
			&i.CoachValidated,
			&i.EmailVerified,
			&i.VerificationToken,
			&i.VerificationTokenExpiresAt,
			&i.VerificationEmailSentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectCoach = `-- name: RejectCoach :exec
UPDATE users SET is_coach = false, coach_validated = false WHERE id = $1
`

func (q *Queries) RejectCoach(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, rejectCoach, id)
	return err
}

const setVerificationToken = `-- name: SetVerificationToken :exec
UPDATE users SET verification_token = $2, verification_token_expires_at = $3, verification_email_sent_at = NOW() WHERE id = $1
`

type SetVerificationTokenParams struct {
	ID                         pgtype.UUID
	VerificationToken          pgtype.Text
	VerificationTokenExpiresAt pgtype.Timestamptz
}

func (q *Queries) SetVerificationToken(ctx context.Context, arg SetVerificationTokenParams) error {
	_, err := q.db.Exec(ctx, setVerificationToken, arg.ID, arg.VerificationToken, arg.VerificationTokenExpiresAt)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password = $2 WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID       pgtype.UUID
	Password string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.Password)
	return err
}

const validateCoach = `-- name: ValidateCoach :exec
UPDATE users SET coach_validated = true WHERE id = $1 AND is_coach = true
`

func (q *Queries) ValidateCoach(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, validateCoach, id)
	return err
}

const verifyUserEmail = `-- name: VerifyUserEmail :exec
UPDATE users SET email_verified = true, verification_token = NULL, verification_token_expires_at = NULL WHERE id = $1
`

func (q *Queries) VerifyUserEmail(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, verifyUserEmail, id)
	return err
}
